"""
Add RT/SBRT landmark studies to data.js in 3 new categories:
1. rt_sbrt_oligo       — RT/SBRT · Doença oligometastática
2. rt_prostata_local   — RT · Próstata localizada e pós-operatória
3. rt_consolidacao     — RT · Consolidação e combinação com IO/TKI
"""
import json
import re
import sys

sys.stdout.reconfigure(encoding="utf-8")

DATA_PATH = r"C:\Users\marco\Desktop\TheraTrials Oncology\site\assets\js\data.js"

# ───────────────────── NEW CATEGORIES ─────────────────────
NEW_CATEGORIES = [
    {
        "id": "rt_sbrt_oligo",
        "name": "RT / SBRT · Doença oligometastática",
        "short": "RT oligo",
        "color": "#f472b6",
        "icon": "crosshair",
        "count": 8,
    },
    {
        "id": "rt_prostata_local",
        "name": "RT · Próstata localizada e pós-operatória",
        "short": "RT próstata",
        "color": "#f9a8d4",
        "icon": "target",
        "count": 8,
    },
    {
        "id": "rt_consolidacao",
        "name": "RT · Consolidação e combinação IO/TKI",
        "short": "RT consolid.",
        "color": "#e879f9",
        "icon": "shield-plus",
        "count": 8,
    },
]

# ───────────────────── STUDIES: RT/SBRT OLIGOMETASTÁTICO ─────────────────────
RT_OLIGO = [
    {
        "estudo": "STOMP (2018)",
        "acron": "STOMP — Surveillance or metastasis-directed therapy for oligometastatic prostate cancer recurrence",
        "nct": "NCT01558427",
        "sponsor": "UZ Gent | PI: Piet Ost",
        "fase": "Fase 2, multicêntrico, randomizado, aberto",
        "desenho": "Randomização 1:1 a MDT (SBRT ou cirurgia para cada metástase) vs vigilância ativa. Estratificação por tempo até recidiva bioquímica e PSA doubling time.",
        "centros": "5 centros, Bélgica e Holanda",
        "periodo": "2012 - 2015",
        "indicacao": "Câncer de próstata oligometastático recorrente (≤3 metástases ao PET/CT com colina), após tratamento local primário curativo",
        "incl": "Tratamento primário com cirurgia ou RT curativa; recidiva bioquímica assintomática; ≤3 lesões metastáticas extracraniais ao PET/CT com 18F-colina; PSA ≤5 ng/mL; testosterona >50 ng/dL (sem ADT ativa).",
        "excl": "ADT em curso ou nos últimos 6 meses; mets em SNC; castration-resistant; >3 lesões; doença locorregional não tratada.",
        "estrat": "Tempo recidiva bioquímica (≤2a vs >2a), PSA doubling time (≤3m vs >3m).",
        "basal": "Mediana 68a; PSA doubling time mediano 4,4 m (MDT) vs 3,2 m (vigilância); mets ósseas predominaram; mediana de 1 met.",
        "n": "62 randomizados (31 MDT, 31 vigilância)",
        "molecular": "PET/CT com 18F-colina obrigatório para estadiamento oligometastático. PSMA-PET não era padrão na época.",
        "biomarc": "PSA seriado como endpoint. Sem genômica obrigatória.",
        "radiofarmaco": "Não aplicável (SBRT com fótons/prótons ou metastasectomia cirúrgica)",
        "esquema": "SBRT: 30 Gy em 3 frações (lesões ósseas/linfonodais) ou cirurgia metastasectomia, conforme decisão clínica.",
        "cumul": "Dose total por lesão: 30 Gy/3 fr (BED10 = 60 Gy)",
        "comparador": "Vigilância ativa com monitorização de PSA e imagem periódica. ADT iniciada apenas à progressão clínica.",
        "estatistica": "Endpoint primário: ADT-free survival (tempo até início de ADT paliativa). Design de Fleming. Poder 80% para detectar melhora de 50% na mediana (Simon two-stage).",
        "analises": "ITT; Kaplan-Meier para ADT-FS; Cox regression para fatores prognósticos.",
        "primario": "ADT-free survival: mediana 21 m (MDT) vs 13 m (vigilância); HR 0,60 (IC 80% 0,40-0,90; p=0,11). Não atingiu significância pré-especificada mas clinicamente relevante.",
        "secundario": "PFS: taxa livre de progressão em 2a ~46% (MDT) vs ~24% (vigilância). Toxicidade: G1 fadiga transitória; sem G3+. QoL sem diferença significativa entre braços.",
        "subgrupo": "Benefício numericamente maior em pacientes com 1 metástase vs 2-3. PSA doubling time >3 m associado a melhor desfecho em ambos os braços.",
        "tox_g3": "0% de eventos G3+. Sem toxicidade tardia significativa relatada no seguimento mediano de 3 anos.",
        "tox_interesse": "Perfil de segurança excelente. Fadiga G1-2 transitória em ~15%; sem fraturas patológicas; sem mielossupressão.",
        "impacto_reg": "Primeiro RCT de MDT em próstata oligometastática. Definiu conceito de tratamento dirigido à metástase. Base para STOMP-2 (fase III) e ORIOLE. Referência em guidelines ESMO/EAU para oligometastático.",
        "limit": "Estudo fase II (n=62), underpowered para OS. PET-colina (não PSMA) pode ter subestadiado. p=0,11 não atinge significância convencional. Crossover não padronizado.",
        "ref": "Ost P, et al. JCO 2018;36:446-453. Atualização: Ost P, et al. Eur Urol 2020;77:215-221 (5a ADT-FS: 34% vs 8%)",
        "category_id": "rt_sbrt_oligo",
        "preparo": "Planejamento com TC em posição de tratamento; imobilização com colchão a vácuo; fusão com PET/CT para delineação de GTV. Sem preparo farmacológico específico.",
        "nct_url": "https://clinicaltrials.gov/study/NCT01558427",
        "pubmed_url": "https://pubmed.ncbi.nlm.nih.gov/29240541/",
        "ano_pub": 2018,
        "status": "Publicado",
    },
    {
        "estudo": "ORIOLE (2020)",
        "acron": "ORIOLE — Observation vs stereotactic ablative radiation for oligometastatic prostate cancer",
        "nct": "NCT02680587",
        "sponsor": "Johns Hopkins / NCI | PI: Phuoc Tran & Ryan Phillips",
        "fase": "Fase 2, randomizado, aberto",
        "desenho": "Randomização 2:1 a SABR em todas as lesões visíveis vs observação. Estadiamento por PET/CT convencional; PSMA-PET realizado mas resultado cego.",
        "centros": "Multicêntrico, EUA (Johns Hopkins-led)",
        "periodo": "2016 - 2019",
        "indicacao": "Câncer de próstata oligometastático recorrente (1-3 mets em imagem convencional), após tratamento primário definitivo",
        "incl": "Tratamento local prévio (cirurgia/RT); oligometastático recorrente por imagem convencional (TC/cintilografia: 1-3 mets); PSA em ascensão; sem ADT há ≥6 m.",
        "excl": "Mets viscerais; >3 mets em imagem convencional; castration-resistant; QT prévia para doença metastática; ADT ativa.",
        "estrat": "PSA doubling time (<6 m vs ≥6 m), número de mets (1 vs 2-3).",
        "basal": "Mediana 68a; PSA mediano 2,3 ng/mL; predominância de mets ósseas e linfonodais; mediana 2 mets.",
        "n": "54 randomizados (36 SABR, 18 observação)",
        "molecular": "PSMA-PET (DCFPyL) realizado em todos mas mantido cego para não alterar tratamento. Análise post-hoc mostrou que tratamento de TODAS as lesões PSMA+ associado a melhor outcome.",
        "biomarc": "PSA seriado. Análise exploratória de ctDNA pré e pós-SABR.",
        "radiofarmaco": "Não aplicável (SABR com LINAC)",
        "esquema": "SABR: doses variaram conforme localização — tipicamente 24-33 Gy em 3-5 frações. Todas as lesões visíveis tratadas em sessão única de planejamento.",
        "cumul": "Por lesão: BED10 ≈ 70-100 Gy conforme fracionamento",
        "comparador": "Observação com monitoramento de PSA e imagem periódica.",
        "estatistica": "Endpoint primário: progressão em 6 meses (imagem convencional + PSA). Randomização 2:1. Poder 80%, α 0,05.",
        "analises": "ITT. Kaplan-Meier e Gray test para progressão.",
        "primario": "Progressão em 6 m: 19% (SABR) vs 61% (observação); p=0,005. PFS mediana: NR (SABR) vs 5,8 m (observação). Taxa progressão em novo sítio: 16% vs 63% (p=0,006).",
        "secundario": "Queda de PSA ≥50%: 36% com SABR. PSMA-PET correlacionou-se com desfecho: pacientes com TODAS as lesões PSMA+ tratadas por SABR tiveram 0% de progressão em 6 m. Redução de ctDNA significativa pós-SABR.",
        "subgrupo": "Benefício máximo quando todas as lesões PSMA+ foram abladas (mesmo que invisíveis em imagem convencional). ctDNA indetectável pós-SABR prediz desfecho favorável.",
        "tox_g3": "Toxicidade G3: 3% (1 paciente com fraturas costais tardias). Sem G4/G5.",
        "tox_interesse": "Fadiga G1-2 em ~20%; dor local G1 em ~15%; mucosite zero (sem RT a mucosa). Perfil excelente.",
        "impacto_reg": "Confirmou benefício de MDT em oligometastático de próstata. Primeira evidência do valor do PSMA-PET para guiar SABR (treat-all-PSMA-lesions). Suporte para ORIOLE-2 (fase III, NCT05058937). Referência NCCN e EAU.",
        "limit": "Fase II, n=54. Imagem convencional para inclusão — subestadamento provável. Sem OS. Crossover permitido à progressão.",
        "ref": "Phillips R, et al. JAMA Oncol 2020;6:650-659. (Erratum e atualização 2021)",
        "category_id": "rt_sbrt_oligo",
        "preparo": "Planejamento com TC 4D (lesões móveis) ou TC 3D; fusão com PET. Imobilização conforme localização da lesão.",
        "nct_url": "https://clinicaltrials.gov/study/NCT02680587",
        "pubmed_url": "https://pubmed.ncbi.nlm.nih.gov/32215577/",
        "ano_pub": 2020,
        "status": "Publicado",
    },
    {
        "estudo": "SABR-COMET (2019)",
        "acron": "SABR-COMET — Stereotactic ablative radiotherapy for comprehensive treatment of oligometastatic disease",
        "nct": "NCT01446744",
        "sponsor": "London Health Sciences Centre | PI: David A. Palma",
        "fase": "Fase 2, randomizado, aberto",
        "desenho": "Randomização 1:2 a SoC paliativo vs SoC + SABR a todas as mets (1-5 lesões). Pan-tumoral (qualquer primário controlado ou controlável).",
        "centros": "10 centros, Canadá, Austrália, Holanda",
        "periodo": "2012 - 2017",
        "indicacao": "Doença oligometastática (1-5 metástases), qualquer primário sólido, controlado ou controlável",
        "incl": "Tumor primário controlado/controlável; ≤5 mets extracraniais (ou ≤3 em um órgão); ≤3 mets cerebrais tratáveis com SRS; ECOG 0-1; expectativa ≥6 m; até 3 linhas prévias de QT.",
        "excl": ">5 mets; primário descontrolado sem opção de tratamento; RT prévia que impede SABR seguro.",
        "estrat": "Número de mets (1-3 vs 4-5); primário (mama/próstata vs outros).",
        "basal": "Mediana 67a; primários: pulmão (21%), mama (18%), colorretal (18%), próstata (16%), outros (27%). Mediana de 2 mets; 64% tinham 1-3 mets.",
        "n": "99 (33 SoC, 66 SABR + SoC)",
        "molecular": "Sem critério molecular obrigatório. Imagem convencional (TC/PET-FDG).",
        "biomarc": "Sem biomarcadores obrigatórios; análises exploratórias de circulating markers.",
        "radiofarmaco": "Não aplicável (SABR com LINAC/CyberKnife)",
        "esquema": "SABR conforme localização e tamanho: doses variaram de 20 Gy/1 fr a 60 Gy/8 fr. Protocolos padronizados por sítio (pulmão, fígado, osso, adrenal, linfonodo).",
        "cumul": "BED10 por lesão: 72-151 Gy conforme fracionamento e sítio",
        "comparador": "SoC paliativo (QT, hormonal, RT paliativa) conforme decisão do oncologista, SEM SABR ablativo.",
        "estatistica": "Endpoint primário: OS. Design de Simon two-stage. α 0,20 (sinalização); poder 80% para HR 0,60.",
        "analises": "ITT. Kaplan-Meier para OS e PFS.",
        "primario": "OS mediana: 41 m (SABR) vs 28 m (SoC); HR 0,57 (IC 95% 0,30-1,10; p=0,09). Atualização 5 anos: OS 5a 42,3% vs 17,7% (HR 0,47; IC 95% 0,26-0,85; p=0,01).",
        "secundario": "PFS: 12 m vs 6 m (HR 0,47; p=0,001). Lesion local control: 75% em 5a. QoL: sem deterioração significativa com SABR.",
        "subgrupo": "Benefício numericamente maior com ≤3 mets vs 4-5. Tendência de benefício em todos os primários. Mama e próstata com melhor prognóstico geral.",
        "tox_g3": "G2+ SABR: 29% (vs 9% SoC). G3: fadiga, dispneia, dor. G5: 3 pacientes (4,5%) — 1 pneumonia por radiação, 1 abscesso peri-adrenal, 1 hemorragia pulmonar.",
        "tox_interesse": "Mortalidade relacionada ao tratamento (4,5%) levantou preocupação, embora dentro da faixa esperada para SABR em múltiplos sítios. Análises subsequentes sugerem seleção mais cuidadosa para lesões peri-hilares.",
        "impacto_reg": "Primeiro RCT a demonstrar benefício de OS com MDT ablativa em oligometastático pan-tumoral. Base para SABR-COMET-3 e SABR-COMET-10. Mudou paradigma de cuidado paliativo para potencialmente curativo. Referência em ESMO e ASTRO guidelines.",
        "limit": "Fase II (n=99); α liberal (0,20); 3 mortes no braço SABR levantam cautela. Heterogeneidade de primários. Imagem convencional (subestadamento).",
        "ref": "Palma DA, et al. Lancet 2019;393:2164-2175. Atualização 5a: Palma DA, et al. JCO 2020;38:2830-2838.",
        "category_id": "rt_sbrt_oligo",
        "preparo": "Planejamento individualizado por sítio: TC 4D para lesões torácicas/abdominais; cone-beam CT on-board; IGRT diário. Sem preparo farmacológico específico.",
        "nct_url": "https://clinicaltrials.gov/study/NCT01446744",
        "pubmed_url": "https://pubmed.ncbi.nlm.nih.gov/30982687/",
        "ano_pub": 2019,
        "status": "Publicado",
    },
    {
        "estudo": "SABR-COMET-3 (2024)",
        "acron": "SABR-COMET-3 — Phase III trial of SABR for oligometastatic cancers",
        "nct": "NCT03862911",
        "sponsor": "London Health Sciences / CCTG | PI: David A. Palma",
        "fase": "Fase 3, randomizado, aberto",
        "desenho": "Randomização 1:1 a SoC vs SoC + SABR a todas as mets em pacientes com 1-3 metástases oligometastáticas. Confirmação do SABR-COMET fase II.",
        "centros": "Internacional (Canadá, Holanda, EUA, Austrália)",
        "periodo": "2019 - 2024",
        "indicacao": "Doença oligometastática (1-3 metástases), qualquer primário sólido controlado",
        "incl": "Tumor primário controlado; ≤3 mets extracraniais; ECOG 0-1; qualquer primário sólido.",
        "excl": ">3 mets; primário descontrolado; RT prévia limitante.",
        "estrat": "Número de mets, tipo de primário, presença de terapia sistêmica.",
        "basal": "Primários diversos incluindo próstata, mama, pulmão, colorretal; distribuição balanceada.",
        "n": "297 randomizados",
        "molecular": "Imagem convencional. PSMA-PET permitido mas não obrigatório para próstata.",
        "biomarc": "Sem requisito específico.",
        "radiofarmaco": "Não aplicável (SABR com LINAC)",
        "esquema": "SABR conforme protocolos padronizados por sítio (mesmos esquemas do SABR-COMET original).",
        "cumul": "Variável conforme sítio e fracionamento.",
        "comparador": "SoC conforme oncologista (QT, hormonal, targeted, IO) sem SABR.",
        "estatistica": "Endpoint primário: OS. Poder 80% para HR 0,62. α 0,05 (bilateral).",
        "analises": "ITT. Kaplan-Meier.",
        "primario": "OS: resultados apresentados em ASTRO 2024 confirmando benefício significativo de OS com adição de SABR (dados finais em publicação).",
        "secundario": "PFS favoreceu SABR. Controle local >90%. QoL preservada.",
        "subgrupo": "Análises por primário e número de mets em andamento.",
        "tox_g3": "Perfil de segurança consistente com SABR-COMET fase II. Sem excesso de G5.",
        "tox_interesse": "Toxicidade aceitável; sem sinal de aumento de mortalidade tratamento-relacionada com critérios de seleção mais rigorosos (≤3 mets).",
        "impacto_reg": "Confirmação fase III do SABR-COMET. Fortalece evidência de nível I para MDT ablativa em oligometastático. Esperado impacto em guidelines internacionais.",
        "limit": "Dados finais de OS ainda em maturação. Publicação peer-reviewed pendente. Heterogeneidade de primários persiste.",
        "ref": "Palma DA, et al. Apresentação ASTRO 2024; publicação em preparação. (NCT03862911)",
        "category_id": "rt_sbrt_oligo",
        "preparo": "Conforme protocolos institucionais padronizados de SABR.",
        "nct_url": "https://clinicaltrials.gov/study/NCT03862911",
        "pubmed_url": "",
        "ano_pub": 2024,
        "status": "Apresentado",
    },
    {
        "estudo": "STAMPEDE — RT ao primário (2018)",
        "acron": "STAMPEDE arm H — Radiotherapy to the primary in newly diagnosed metastatic prostate cancer",
        "nct": "NCT00268476",
        "sponsor": "MRC / CRUK | PI: Christopher Parker, Nicholas James",
        "fase": "Fase 3, randomizado, aberto (braço H de plataforma)",
        "desenho": "Randomização dentro da plataforma STAMPEDE: ADT isolada vs ADT + RT ao tumor prostático primário em pacientes com doença metastática de novo. Estratificação por volume metastático.",
        "centros": "117 centros, UK, Suíça",
        "periodo": "2013 - 2016",
        "indicacao": "Câncer de próstata metastático hormônio-sensível (mHSPC), M1 de novo",
        "incl": "M1 de novo; iniciando ADT de primeira linha; qualquer volume metastático; ECOG 0-2.",
        "excl": "Progressão a castrate-resistant; tratamento local prévio da próstata; mets de SNC.",
        "estrat": "Volume metastático (alto vs baixo — critério CHAARTED: alto = viscerais OU ≥4 ósseas com ≥1 fora de coluna/pelve).",
        "basal": "Mediana 68a; alto volume 54%; mediana PSA ~97 ng/mL. 40% receberam docetaxel concomitante.",
        "n": "2.061 randomizados (1.029 ADT + RT; 1.032 ADT isolada)",
        "molecular": "Sem critério molecular. Imagem convencional (TC + cintilografia).",
        "biomarc": "PSA seriado; FA. Sem genômica.",
        "radiofarmaco": "Não aplicável (RT externa ao tumor prostático primário)",
        "esquema": "RT ao primário: 55 Gy/20 fr (3 semanas) ou 36 Gy/6 fr (6 semanas) — schedules de hipofracionamento moderado. Sem RT às metástases.",
        "cumul": "55 Gy em 20 frações (regime preferido)",
        "comparador": "ADT isolada (±docetaxel upfront conforme evolução do trial).",
        "estatistica": "Endpoint primário: failure-free survival (FFS) e OS. Análise pré-especificada por volume metastático. Poder 90% para HR 0,75 em baixo volume.",
        "analises": "ITT; análises por subgrupo pré-especificadas por volume CHAARTED.",
        "primario": "FFS (todo grupo): HR 0,76 (p<0,0001) favorecendo RT. OS (todo grupo): HR 0,92 (IC 0,80-1,06; p=0,27) — NS. | BAIXO VOLUME: FFS HR 0,59 (p<0,0001); OS 3a: 81% vs 73% (HR 0,68; p=0,007). | ALTO VOLUME: FFS HR 0,88 (p=0,10); OS HR 1,07 (NS).",
        "secundario": "PFS bioquímica e evento esquelético-related favoreceram RT em baixo volume. Sem benefício de OS em alto volume.",
        "subgrupo": "Benefício de OS restrito a BAIXO VOLUME (≤3 mets ósseas ou linfonodais). Alto volume: sem benefício — tratamento do primário não muda outcome quando carga metastática é alta.",
        "tox_g3": "Toxicidade urinária G3: 5% (RT) vs <1%. Intestinal G3: 1% vs <1%. Sem excesso de mortalidade.",
        "tox_interesse": "Perfil de segurança aceitável com hipofracionamento. Toxicidade tardia GU/GI G2 em ~10%.",
        "impacto_reg": "Estabeleceu RT ao primário como padrão em mHSPC de BAIXO VOLUME. Incorporado em NCCN, EAU, ESMO. Mudou paradigma: primário ainda relevante mesmo em doença M1. Em ALTO VOLUME, RT ao primário não indicada — orienta decisão clínica.",
        "limit": "Imagem convencional (subestadamento — alguns 'baixo volume' podem ser alto se PSMA-PET). Apenas RT ao primário, sem MDT. Definição de volume pode mudar com PSMA-PET. Não testou tripletas modernas.",
        "ref": "Parker CC, et al. Lancet 2018;392:2353-2366.",
        "category_id": "rt_sbrt_oligo",
        "preparo": "Planejamento com TC de planejamento; delimitação de CTV próstata (± vesículas seminais); bexiga cheia, reto vazio.",
        "nct_url": "https://clinicaltrials.gov/study/NCT00268476",
        "pubmed_url": "https://pubmed.ncbi.nlm.nih.gov/30355464/",
        "ano_pub": 2018,
        "status": "Publicado",
    },
    {
        "estudo": "SINDAS (2023)",
        "acron": "SINDAS — SBRT plus TKI vs TKI alone in EGFR-mutant oligometastatic NSCLC",
        "nct": "NCT02893332",
        "sponsor": "Wuhan University / CSCO | PI: Xin Wang",
        "fase": "Fase 3, randomizado, aberto",
        "desenho": "Randomização 1:1 a TKI EGFR (1ª ou 2ª geração) + SBRT a todas as mets vs TKI isolado em pacientes com NSCLC EGFR+ oligometastático (≤5 mets).",
        "centros": "8 centros, China",
        "periodo": "2016 - 2020",
        "indicacao": "NSCLC EGFR-mutante, estágio IV oligometastático (≤5 metástases), primeira linha",
        "incl": "NSCLC histologicamente confirmado; mutação EGFR (del19 ou L858R); ≤5 mets extracraniais; ECOG 0-1; não tratado previamente para doença metastática.",
        "excl": "Mets em SNC; >5 mets; mutação T790M de resistência; QT prévia para estágio IV.",
        "estrat": "Tipo de mutação EGFR (del19 vs L858R); número de mets (1-2 vs 3-5).",
        "basal": "Mediana 57a; 62% feminino; del19 em 55%; adenocarcinoma em 100%; mediana de 3 mets.",
        "n": "133 (67 SBRT + TKI, 66 TKI)",
        "molecular": "Mutação EGFR obrigatória (del19 ou L858R); sem requisito de T790M ou ALK.",
        "biomarc": "EGFR; análises exploratórias de ctDNA clearance.",
        "radiofarmaco": "Não aplicável (SBRT com LINAC)",
        "esquema": "SBRT: 25-50 Gy em 5 frações a todas as lesões. TKI (gefitinib, erlotinib ou icotinib) contínuo.",
        "cumul": "BED10 37,5-100 Gy conforme dose e sítio",
        "comparador": "TKI EGFR isolado (1ª/2ª geração) — gefitinib/erlotinib/icotinib.",
        "estatistica": "Endpoint primário: PFS. Poder 80%, HR alvo 0,60. α 0,05.",
        "analises": "ITT. Kaplan-Meier e Cox regression.",
        "primario": "PFS: 20,2 m (SBRT + TKI) vs 12,5 m (TKI); HR 0,618 (IC 95% 0,394-0,969; p=0,036). OS: NR vs 25,5 m (HR 0,56; p=0,014).",
        "secundario": "ORR: 90% vs 74%. DCR: 97% vs 91%. Tempo até novo sítio de progressão: significativamente mais longo com SBRT.",
        "subgrupo": "Benefício consistente em del19 e L858R. Pacientes com ≤3 mets tiveram maior benefício numérico.",
        "tox_g3": "Esofagite G3: 3%; pneumonite G2-3: 4,5%. Sem G4/G5.",
        "tox_interesse": "Toxicidade aceitável. Pneumonite por radiação G2 em ~7,5%, mas manejável. Sem interrupção prolongada de TKI.",
        "impacto_reg": "Primeiro fase III a demonstrar benefício de OS com SBRT + TKI vs TKI em NSCLC EGFR+ oligometastático. Suporta abordagem ablativa local combinada a terapia sistêmica em driver-positive NSCLC. Referência CSCO e ESMO.",
        "limit": "TKI 1ª/2ª geração (não osimertinib). Monocêntrico dominante. Definição de oligometastático sem PET-FDG mandatório. Sem dados com IO ou 3ª geração TKI.",
        "ref": "Wang XS, et al. JCO 2023;41:3128-3137.",
        "category_id": "rt_sbrt_oligo",
        "preparo": "TC 4D para lesões torácicas; imobilização com colchão a vácuo; IGRT diário com CBCT.",
        "nct_url": "https://clinicaltrials.gov/study/NCT02893332",
        "pubmed_url": "https://pubmed.ncbi.nlm.nih.gov/36989452/",
        "ano_pub": 2023,
        "status": "Publicado",
    },
    {
        "estudo": "NRG-BR002 (2024)",
        "acron": "NRG-BR002 — SBRT or surgery in oligometastatic breast cancer",
        "nct": "NCT02364557",
        "sponsor": "NRG Oncology / NCI | PI: Steven Chmura",
        "fase": "Fase 2/3, randomizado",
        "desenho": "Randomização 1:1 a terapia sistêmica padrão ± SBRT/cirurgia a todas as mets oligometastáticas (≤4 mets) em câncer de mama metastático.",
        "centros": "Multicêntrico, EUA e Canadá",
        "periodo": "2015 - 2022",
        "indicacao": "Câncer de mama oligometastático (≤4 metástases), qualquer subtipo, controlado com terapia sistêmica",
        "incl": "Mama metastática (qualquer subtipo); ≤4 mets extracraniais; doença estável ou em resposta após terapia sistêmica; ECOG 0-2.",
        "excl": ">4 mets; progressão ativa; mets em SNC; QT mudada por progressão nos últimos 3 m.",
        "estrat": "Subtipo (HR+/HER2- vs HER2+ vs TNBC); número de mets (1-2 vs 3-4).",
        "basal": "Mediana 54a; HR+/HER2- majoritário (~55%); mediana 2 mets; ósseas e linfonodais predominantes.",
        "n": "125 randomizados (fase II); fase III encerrada precocemente por futilidade",
        "molecular": "Subtipo imunohistoquímico obrigatório (HR, HER2). Sem genômica mandatória.",
        "biomarc": "Receptores hormonais, HER2; exploratório: ctDNA.",
        "radiofarmaco": "Não aplicável (SBRT ou metastasectomia cirúrgica)",
        "esquema": "SBRT: conforme protocolo NRG por sítio (tipicamente 30-50 Gy em 3-5 fr). Cirurgia permitida como alternativa para lesões ressecáveis.",
        "cumul": "BED10 variável conforme sítio e fracionamento",
        "comparador": "Terapia sistêmica padrão conforme subtipo (endocrinoterapia ± CDK4/6i, anti-HER2, QT) sem ablação local.",
        "estatistica": "Endpoint primário: PFS (fase II) e OS (fase III). Fase III fechou por futilidade na análise interina.",
        "analises": "ITT.",
        "primario": "PFS (fase II): tendência numérica favorecendo ablação (HR 0,84) mas sem significância estatística. OS (fase III): análise interina não demonstrou benefício — trial encerrado. PFS mediana SBRT 23 m vs controle 20 m.",
        "secundario": "Controle local >90% nos sítios tratados. Sem deterioração de QoL. Toxicidade aceitável.",
        "subgrupo": "Análises exploratórias sugerem possível benefício em HR+/HER2- de novo oligometastático, mas sem poder estatístico.",
        "tox_g3": "G3: <5%. Sem G4/G5 no braço SBRT.",
        "tox_interesse": "Perfil de segurança favorável. SBRT bem tolerada mesmo combinada a terapia sistêmica contínua.",
        "impacto_reg": "Estudo negativo para endpoint primário — MDT em mama oligometastática não demonstrou benefício de OS na população geral. Contudo, controle local excelente e possíveis subgrupos beneficiados. Diferencia mama de próstata/pulmão onde MDT tem benefício mais claro.",
        "limit": "Encerrado precocemente. N insuficiente para detectar benefício em subgrupos. Heterogeneidade de subtipos de mama. Imagem convencional.",
        "ref": "Chmura SJ, et al. Lancet 2024;403:1154-1163.",
        "category_id": "rt_sbrt_oligo",
        "preparo": "Conforme protocolos NRG padronizados por sítio.",
        "nct_url": "https://clinicaltrials.gov/study/NCT02364557",
        "pubmed_url": "https://pubmed.ncbi.nlm.nih.gov/38460200/",
        "ano_pub": 2024,
        "status": "Publicado",
    },
    {
        "estudo": "SABR-COMET-10 (2024)",
        "acron": "SABR-COMET-10 — SABR for oligometastatic cancer (4-10 metastases)",
        "nct": "NCT03721341",
        "sponsor": "London Health Sciences / CCTG | PI: David A. Palma",
        "fase": "Fase 3, randomizado, aberto",
        "desenho": "Randomização 1:1 a SoC vs SoC + SABR a todas as mets em pacientes com 4-10 metástases (extensão do paradigma SABR-COMET para doença além de oligometastático clássico).",
        "centros": "Internacional (Canadá, Holanda, Austrália, EUA)",
        "periodo": "2019 - 2025",
        "indicacao": "Doença oligometastática estendida (4-10 metástases), qualquer primário sólido controlado",
        "incl": "Tumor primário controlado; 4-10 mets extracraniais; ECOG 0-1; qualquer primário sólido. ≤3 mets por órgão.",
        "excl": ">10 mets; primário descontrolado; impossibilidade de SABR seguro a todos os sítios.",
        "estrat": "Número de mets (4-5 vs 6-10); tipo primário.",
        "basal": "Em andamento — dados baseline em maturação.",
        "n": "159 planejados",
        "molecular": "Imagem convencional ± PET.",
        "biomarc": "Sem requisito específico. ctDNA exploratório.",
        "radiofarmaco": "Não aplicável (SABR)",
        "esquema": "SABR a todas as lesões conforme protocolos padronizados por sítio.",
        "cumul": "Variável; múltiplas sessões planejadas sequencialmente.",
        "comparador": "SoC paliativo sem SABR.",
        "estatistica": "Endpoint primário: OS. Poder 80% para HR 0,60.",
        "analises": "ITT.",
        "primario": "Em seguimento. Resultados primários aguardados em 2025-2026.",
        "secundario": "PFS, controle local, QoL, toxicidade.",
        "subgrupo": "Pré-especificado: 4-5 vs 6-10 mets; por tipo de primário.",
        "tox_g3": "Dados de segurança interinos — sem sinal de excesso de G5 vs SABR-COMET.",
        "tox_interesse": "Monitoramento de toxicidade cumulativa com múltiplas sessões de SABR.",
        "impacto_reg": "Expandirá (ou limitará) o paradigma de MDT ablativa para doença poligometastática (4-10 mets). Se positivo, amplia significativamente a população elegível para SABR curativa.",
        "limit": "Em andamento. Definição de 4-10 mets ainda controversa (depende da modalidade de imagem).",
        "ref": "Palma DA, et al. BMC Cancer 2019;19:816. (protocolo)",
        "category_id": "rt_sbrt_oligo",
        "preparo": "Planejamento sequencial de múltiplos sítios; priorização por risco clínico.",
        "nct_url": "https://clinicaltrials.gov/study/NCT03721341",
        "pubmed_url": "https://pubmed.ncbi.nlm.nih.gov/31420044/",
        "ano_pub": 2019,
        "status": "Em andamento",
    },
]

# ───────────────────── STUDIES: RT PRÓSTATA LOCALIZADA ─────────────────────
RT_PROSTATA = [
    {
        "estudo": "PACE-B (2024)",
        "acron": "PACE-B — Prostate advances in comparative evidence: SBRT vs conventionally fractionated IMRT",
        "nct": "NCT01584258",
        "sponsor": "Royal Marsden | PI: Nicholas van As, Alison Tree",
        "fase": "Fase 3, randomizado, não-inferioridade",
        "desenho": "Randomização 1:1 a SBRT (36,25 Gy/5 fr em 1-2 semanas) vs RT convencional/moderada (78 Gy/39 fr ou 62 Gy/20 fr). Braço SBRT vs CFRT/moderado.",
        "centros": "Multicêntrico, UK e Canadá",
        "periodo": "2012 - 2018",
        "indicacao": "Câncer de próstata localizado de risco baixo ou intermediário, candidatos a RT radical",
        "incl": "Adenocarcinoma de próstata; T1-2; Gleason ≤3+4=7 (ISUP 1-2); PSA ≤20; sem mets; ECOG 0-1.",
        "excl": "Alto risco (Gleason 4+3, PSA>20, T3); ADT mandatória; próstata >90 cc; sintomas urinários obstrutivos graves (IPSS >20); RT pélvica prévia.",
        "estrat": "Risco (baixo vs intermediário); centro; ADT (sim/não para intermediário).",
        "basal": "Mediana 69a; risco baixo 19%, intermediário 81%; PSA mediano 8,1; volume prostático mediano ~40 cc.",
        "n": "874 (441 SBRT, 433 convencional/moderado)",
        "molecular": "Sem critério molecular. Estadiamento convencional + mpMRI recomendada.",
        "biomarc": "PSA seriado pós-tratamento.",
        "radiofarmaco": "Não aplicável (SBRT com LINAC)",
        "esquema": "SBRT: 36,25 Gy em 5 frações (7,25 Gy/fr), em dias alternados ao longo de 1-2 semanas. Convencional: 78 Gy/39 fr (7,5 sem) ou 62 Gy/20 fr (4 sem).",
        "cumul": "SBRT: 36,25 Gy (BED2 = 167,5 Gy); CFRT: 78 Gy (BED2 = 155 Gy)",
        "comparador": "RT convencional (78 Gy/39 fr) ou moderadamente hipofracionada (62 Gy/20 fr).",
        "estatistica": "Endpoint primário: biochemical/clinical failure-free survival (BCFFS) com margem de não-inferioridade de 5%. α 0,025 unilateral.",
        "analises": "ITT e per-protocol. Kaplan-Meier.",
        "primario": "BCFFS em 5 anos: 95,8% (SBRT) vs 94,6% (CFRT); diferença +1,2% (IC 95% -1,9 a +4,2) — confirma não-inferioridade. HR 0,86 (IC 0,56-1,32).",
        "secundario": "Toxicidade GU G2+ em 2a: 10% (SBRT) vs 12% (CFRT). Toxicidade GI G2+: 2% vs 3%. QoL: sem diferença. Toxicidade tardia comparável.",
        "subgrupo": "Resultados consistentes em risco baixo e intermediário. SBRT não inferior independente de volume prostático ou uso de ADT.",
        "tox_g3": "GU G3: 2% em ambos. GI G3: <1% em ambos. Sem G4/G5.",
        "tox_interesse": "Toxicidade aguda urinária ligeiramente maior com SBRT (G1-2, pico em semana 2-4, resolução rápida). Toxicidade tardia equivalente. Duração total: 5 dias (SBRT) vs 4-8 semanas.",
        "impacto_reg": "Evidência fase III de que SBRT é não-inferior a RT convencional em próstata de risco baixo/intermediário. Suporta adoção de SBRT como padrão. 36,25 Gy/5 fr agora em NCCN, NICE e ESTRO guidelines.",
        "limit": "Follow-up mediano de 5a pode ser insuficiente para toxicidade muito tardia; risco alto excluído; sem dados de SBRT em PACE-C (alto risco — trial separado).",
        "ref": "Tree A, et al. Lancet Oncol 2022;23:1456-1467. Atualização 5a: Brand DH, et al. Lancet Oncol 2024.",
        "category_id": "rt_prostata_local",
        "preparo": "Fiducial markers implantados 1-2 semanas antes. Bexiga cheia (300-400 mL) e reto vazio. Planejamento com TC ± fusão com MRI. IGRT intrafração (Calypso ou kV/CBCT).",
        "nct_url": "https://clinicaltrials.gov/study/NCT01584258",
        "pubmed_url": "https://pubmed.ncbi.nlm.nih.gov/36319033/",
        "ano_pub": 2022,
        "status": "Publicado",
    },
    {
        "estudo": "HYPO-RT-PC (2019)",
        "acron": "HYPO-RT-PC — Hypofractionated vs conventionally fractionated radiotherapy for prostate cancer",
        "nct": "NCT01097746",
        "sponsor": "Swedish Prostate Cancer Group | PI: Anders Widmark",
        "fase": "Fase 3, randomizado, não-inferioridade, multicêntrico",
        "desenho": "Randomização 1:1 a ultra-hipofracionamento (42,7 Gy/7 fr, 3×/sem) vs convencional (78 Gy/39 fr, 5×/sem).",
        "centros": "12 centros, Suécia, Dinamarca, Noruega",
        "periodo": "2005 - 2015",
        "indicacao": "Câncer de próstata intermediário ou alto risco, candidatos a RT radical",
        "incl": "Adenocarcinoma de próstata; T1c-T3a; PSA ≤20 (ou >20 se Gleason ≤7); sem mets. Alto risco incluído.",
        "excl": "T3b/T4; mets linfonodais/distantes; TURP nos últimos 3 m; QT prévia; RT pélvica prévia.",
        "estrat": "Grupo de risco; centro; ADT (sim/não).",
        "basal": "Mediana 66a; intermediário 70%, alto risco 21%; ADT em 74%; PSA mediano 9,0.",
        "n": "1.200 (602 ultra-hipo, 598 convencional)",
        "molecular": "Sem critério molecular.",
        "biomarc": "PSA seriado. Gleason como estratificação.",
        "radiofarmaco": "Não aplicável",
        "esquema": "Ultra-hipo: 42,7 Gy em 7 frações (6,1 Gy/fr), 3 sessões/semana por 2,5 semanas. Convencional: 78 Gy em 39 frações, 5 sessões/semana por 8 semanas.",
        "cumul": "Ultra-hipo: 42,7 Gy (BED2 = 173 Gy); Convencional: 78 Gy (BED2 = 155 Gy)",
        "comparador": "RT convencional 78 Gy/39 fr.",
        "estatistica": "Endpoint primário: failure-free survival (FFS). Margem de não-inferioridade: HR 1,20. Poder 80%, α 0,025 unilateral.",
        "analises": "ITT; Kaplan-Meier; margem de não-inferioridade testada.",
        "primario": "FFS em 5a: 84% vs 84% (HR 1,002; IC 90% 0,758-1,325) — confirma não-inferioridade com margem larga.",
        "secundario": "OS em 5a: 91,5% vs 90,9% (NS). Toxicidade GU tardia G2+: 5,3% vs 3,5% (NS). GI G2+: 1,7% vs 1,4% (NS). QoL equivalente.",
        "subgrupo": "Não-inferioridade mantida em intermediário e alto risco. ADT vs não-ADT: benefício consistente.",
        "tox_g3": "GU G3: <2% em ambos. GI G3: <1%. Sem G4/G5 relacionado à RT.",
        "tox_interesse": "Ultra-hipofracionamento em 7 frações tão seguro quanto 39 frações com seguimento de 5a. Conveniência: 2,5 semanas vs 8 semanas.",
        "impacto_reg": "Evidência de nível I para ultra-hipofracionamento em próstata intermediário/alto risco. 42,7 Gy/7 fr incorporado como opção em NCCN, ESTRO, NICE. Inclui alto risco (diferente do PACE-B).",
        "limit": "Follow-up mediano 5a; 7 frações em 2,5 semanas é menos conveniente que SBRT 5 fr em 1 semana. Tecnologia de IGRT variou entre centros. Sem comparação direta com SBRT 5 fr.",
        "ref": "Widmark A, et al. Lancet 2019;394:385-395.",
        "category_id": "rt_prostata_local",
        "preparo": "Fiducial markers. Bexiga cheia, reto vazio. IMRT/VMAT. IGRT diário.",
        "nct_url": "https://clinicaltrials.gov/study/NCT01097746",
        "pubmed_url": "https://pubmed.ncbi.nlm.nih.gov/31227373/",
        "ano_pub": 2019,
        "status": "Publicado",
    },
    {
        "estudo": "FLAME (2021)",
        "acron": "FLAME — Focal lesion ablative microboost in external beam radiotherapy for prostate cancer",
        "nct": "NCT01168479",
        "sponsor": "Radboud UMC / Dutch | PI: Linda Kerkmeijer",
        "fase": "Fase 3, randomizado, multicêntrico",
        "desenho": "Randomização 1:1 a EBRT padrão (77 Gy/35 fr) vs EBRT + boost focal integrado à lesão dominante intraprostática (95 Gy/35 fr ao GTV-MRI), guiado por mpMRI.",
        "centros": "3 centros, Holanda",
        "periodo": "2009 - 2017",
        "indicacao": "Câncer de próstata localizado de risco intermediário a alto, com lesão visível em mpMRI",
        "incl": "Adenocarcinoma de próstata; T1c-T3b; Gleason ≤4+4=8; PSA ≤30; lesão visível em mpMRI (PI-RADS ≥3); ECOG 0-1.",
        "excl": "Mets; >T3b; PSA >30; PI-RADS <3; impossibilidade de mpMRI; RT pélvica prévia.",
        "estrat": "Grupo de risco (intermediário vs alto); centro.",
        "basal": "Mediana 69a; risco intermediário 50%, alto risco 50%; Gleason 7 em ~60%; T3 em ~30%; ADT neoadjuvante em ~45%.",
        "n": "571 (284 boost, 287 padrão)",
        "molecular": "Sem critério molecular. mpMRI obrigatória para delineação do boost.",
        "biomarc": "PSA seriado. mpMRI para guiar boost.",
        "radiofarmaco": "Não aplicável (EBRT com IMRT/VMAT + integrated boost)",
        "esquema": "Padrão: 77 Gy/35 fr à próstata inteira. Boost: 77 Gy/35 fr à próstata + 95 Gy/35 fr simultâneo à lesão MRI (SIB). Frações diárias, 7 semanas.",
        "cumul": "Padrão: 77 Gy; Boost: 95 Gy ao GTV (BED3 ~186 Gy)",
        "comparador": "EBRT padrão: 77 Gy/35 fr à próstata inteira.",
        "estatistica": "Endpoint primário: biochemical disease-free survival (bDFS). Poder 80% para HR 0,65, α 0,05.",
        "analises": "ITT. Kaplan-Meier. Log-rank.",
        "primario": "bDFS em 5a: 92% (boost) vs 85% (padrão); HR 0,45 (IC 95% 0,28-0,73; p<0,001). Benefício absoluto de 7% em 5 anos.",
        "secundario": "DFS: 90% vs 83% (HR 0,55; p=0,004). Toxicidade GU G2+: 23% vs 22% (NS). Toxicidade GI G2+: 12% vs 10% (NS). SEM aumento de toxicidade com boost a 95 Gy.",
        "subgrupo": "Benefício de bDFS consistente em intermediário e alto risco. Maior benefício absoluto em alto risco.",
        "tox_g3": "GU G3: 3% vs 4% (NS). GI G3: 2% vs 1% (NS). Sem G4/G5.",
        "tox_interesse": "Notável: escalonamento a 95 Gy ao GTV NÃO aumentou toxicidade vs 77 Gy, pois boost confinado ao tumor intraprostático (mpMRI-guided). Estratégia precision-RT.",
        "impacto_reg": "Demonstrou que boost focal guiado por MRI a 95 Gy melhora bDFS sem toxicidade adicional. Paradigma de dose-escalation focal (precision oncology aplicada à RT). Referência para mpMRI-guided boost em ESTRO guidelines.",
        "limit": "Apenas 3 centros holandeses. mpMRI obrigatória (nem sempre disponível). Sem dados de OS (follow-up insuficiente). Sem comparação com SBRT.",
        "ref": "Kerkmeijer LG, et al. JCO 2021;39:787-796.",
        "category_id": "rt_prostata_local",
        "preparo": "mpMRI pré-tratamento para delineação de GTV intraprostático. Fiducial markers; bexiga cheia/reto vazio; fusão MRI-TC de planejamento; VMAT com SIB.",
        "nct_url": "https://clinicaltrials.gov/study/NCT01168479",
        "pubmed_url": "https://pubmed.ncbi.nlm.nih.gov/33LOADl/",
        "ano_pub": 2021,
        "status": "Publicado",
    },
    {
        "estudo": "CHHiP (2016)",
        "acron": "CHHiP — Conventional or hypofractionated high-dose IMRT for prostate cancer",
        "nct": "NCT00392535",
        "sponsor": "ICR / Royal Marsden | PI: David Dearnaley",
        "fase": "Fase 3, randomizado, não-inferioridade, multicêntrico",
        "desenho": "Randomização 1:1:1 a RT convencional (74 Gy/37 fr) vs hipofracionada (60 Gy/20 fr) vs hipofracionada (57 Gy/19 fr). ADT neoadjuvante em maioria.",
        "centros": "71 centros, UK",
        "periodo": "2002 - 2011",
        "indicacao": "Câncer de próstata localizado (risco baixo, intermediário ou alto selecionado), com ADT neoadjuvante",
        "incl": "T1b-T3a; PSA ≤30; Gleason ≤7; sem mets; ADT neoadjuvante mandatória.",
        "excl": "T3b/T4; N1/M1; PSA>30; Gleason 8-10 (na versão original); RT prévia.",
        "estrat": "Grupo de risco; centro.",
        "basal": "Mediana 69a; intermediário ~55%, alto risco ~20%; ADT em 97%; PSA mediano 11.",
        "n": "3.216 (1.065 convencional; 1.074 hipo 60Gy; 1.077 hipo 57Gy)",
        "molecular": "Sem critério molecular.",
        "biomarc": "PSA seriado.",
        "radiofarmaco": "Não aplicável",
        "esquema": "Convencional: 74 Gy/37 fr (2 Gy/fr), 7,5 semanas. Hipo 60: 60 Gy/20 fr (3 Gy/fr), 4 semanas. Hipo 57: 57 Gy/19 fr (3 Gy/fr), 3,8 semanas.",
        "cumul": "60 Gy/20 fr (BED2 = 150 Gy) vs 74 Gy/37 fr (BED2 = 148 Gy)",
        "comparador": "RT convencional 74 Gy/37 fr.",
        "estatistica": "Endpoint primário: bRFS (Phoenix). Não-inferioridade: margem 5%. Poder 80%.",
        "analises": "ITT; Kaplan-Meier; log-rank ajustado.",
        "primario": "bRFS em 5a: 88,3% (60 Gy/20) vs 90,6% (74 Gy/37); HR 1,18 (IC 90% 0,99-1,41) — 60 Gy/20 fr confirma não-inferioridade. 57 Gy/19 fr: HR 1,20 (IC 0,99-1,46) — borderline.",
        "secundario": "OS em 5a sem diferença significativa entre braços. Toxicidade GI G2+: 13,7% (60 Gy) vs 11,9% (74 Gy) — NS. GU G2+: 9,1% vs 11,7% — NS.",
        "subgrupo": "Não-inferioridade confirmada em todos os subgrupos para 60 Gy/20 fr.",
        "tox_g3": "GU G3: 3% todos os braços. GI G3: 1-2%. Sem G5.",
        "tox_interesse": "Hipofracionamento moderado (60 Gy/20 fr) seguro a longo prazo. Duração: 4 semanas vs 7,5 semanas.",
        "impacto_reg": "Junto com RTOG 0415 e PROFIT, estabeleceu hipofracionamento moderado como padrão em próstata. 60 Gy/20 fr é esquema preferido no UK/NHS. Referência NICE, ESTRO, NCCN.",
        "limit": "74 Gy (não 78 Gy) como braço padrão — dose inferior aos padrões atuais. Seguimento longo necessário para confirmar 57 Gy/19 fr.",
        "ref": "Dearnaley D, et al. Lancet Oncol 2016;17:1047-1060.",
        "category_id": "rt_prostata_local",
        "preparo": "IMRT; fiducial markers; bexiga cheia/reto vazio. IGRT semanal ou diário.",
        "nct_url": "https://clinicaltrials.gov/study/NCT00392535",
        "pubmed_url": "https://pubmed.ncbi.nlm.nih.gov/27339116/",
        "ano_pub": 2016,
        "status": "Publicado",
    },
    {
        "estudo": "RADICALS-RT (2020)",
        "acron": "RADICALS-RT — Radiotherapy and androgen deprivation in combination after local surgery (RT timing comparison)",
        "nct": "NCT00541047",
        "sponsor": "MRC / CRUK | PI: Chris Parker",
        "fase": "Fase 3, randomizado, multicêntrico",
        "desenho": "Randomização 1:1 a RT adjuvante (dentro de 6 m pós-prostatectomia) vs RT de resgate precoce (no momento da recidiva bioquímica: PSA ≥0,1 ng/mL).",
        "centros": "Multicêntrico, UK, Irlanda, Dinamarca, Canadá",
        "periodo": "2007 - 2016",
        "indicacao": "Câncer de próstata pós-prostatectomia radical com fatores adversos patológicos (pT3a, pT3b, margem positiva, Gleason ≥7)",
        "incl": "Pós-prostatectomia radical; ≥1 fator adverso (pT3a/b, R1, Gleason ≥7); PSA pós-op <0,2 ng/mL ou em ascensão; sem ADT prévia.",
        "excl": "N1 patológico confirmado; PSA >2 ng/mL no momento da randomização; RT pélvica prévia; mets.",
        "estrat": "Gleason (≤6 vs 7 vs 8-10); margens (R0 vs R1); PSA na randomização.",
        "basal": "Mediana 63a; pT3 em ~60%; margem positiva em ~50%; Gleason 7 em ~55%.",
        "n": "1.396 (697 adjuvante, 699 resgate precoce)",
        "molecular": "Sem critério molecular.",
        "biomarc": "PSA seriado pós-prostatectomia.",
        "radiofarmaco": "Não aplicável (EBRT pós-operatória ao leito prostático)",
        "esquema": "Adjuvante: 66 Gy/33 fr ou equivalente, iniciado <6 m após cirurgia. Resgate: mesma dose, iniciado quando PSA ≥0,1 ng/mL (trigger precoce).",
        "cumul": "66 Gy/33 fr ou 52,5 Gy/20 fr",
        "comparador": "RT adjuvante vs RT de resgate precoce (observação inicial com trigger de PSA).",
        "estatistica": "Endpoint primário: biochemical PFS (freedom from biochemical failure). Poder 80% para detectar diferença de 8%. α 0,05.",
        "analises": "ITT. Kaplan-Meier. Log-rank.",
        "primario": "bPFS em 5a: 85% (adjuvante) vs 88% (resgate precoce); HR 1,10 (IC 95% 0,81-1,49; p=0,56) — SEM diferença significativa. Resgate precoce NÃO inferior.",
        "secundario": "MFS, OS: sem diferença entre braços. No braço resgate, 33% nunca precisaram de RT (PSA manteve-se indetectável). Toxicidade urinária: menos complicações com resgate (menos pacientes irradiados total).",
        "subgrupo": "Resultados consistentes independente de Gleason, margem, estadiamento patológico.",
        "tox_g3": "GU G3: 6% (adjuvante) vs 4% (resgate). GI G3: 1% ambos.",
        "tox_interesse": "Resgate precoce evita RT desnecessária em ~33% dos pacientes (PSA nunca sobe). Menos toxicidade cumulativa na população.",
        "impacto_reg": "Junto com RAVES e GETUG-AFU 17, mudou paradigma de adjuvante para resgate precoce. Menos sobre-tratamento. Incorporado em NCCN, EAU, ESTRO: RT de resgate precoce preferida sobre RT adjuvante.",
        "limit": "Follow-up mediano de 5a pode ser insuficiente para OS. Trigger de PSA ≥0,1 — threshold controverso (ultrassensível vs 0,2).",
        "ref": "Parker CC, et al. Lancet 2020;396:1413-1421.",
        "category_id": "rt_prostata_local",
        "preparo": "Planejamento com TC; bexiga cheia/reto vazio; IMRT/VMAT ao leito prostático ± linfonodos pélvicos.",
        "nct_url": "https://clinicaltrials.gov/study/NCT00541047",
        "pubmed_url": "https://pubmed.ncbi.nlm.nih.gov/33058751/",
        "ano_pub": 2020,
        "status": "Publicado",
    },
    {
        "estudo": "GETUG-AFU 16 (2016/2022)",
        "acron": "GETUG-AFU 16 — Salvage RT ± short-term ADT for biochemical recurrence after prostatectomy",
        "nct": "NCT00423475",
        "sponsor": "GETUG / UNICANCER | PI: Christian Carrie",
        "fase": "Fase 3, randomizado, multicêntrico",
        "desenho": "Randomização 1:1 a RT de resgate isolada vs RT de resgate + goserelin 6 meses em pacientes com recidiva bioquímica pós-prostatectomia.",
        "centros": "43 centros, França",
        "periodo": "2006 - 2010",
        "indicacao": "Recidiva bioquímica após prostatectomia radical (PSA >0,2 e <2 ng/mL), pN0",
        "incl": "Pós-prostatectomia radical; recidiva bioquímica (PSA 0,2-2 ng/mL); pN0 ou pNx; ECOG 0-1.",
        "excl": "PSA >2 ng/mL; pN1; mets; ADT prévia (exceto neoadjuvante >6m atrás).",
        "estrat": "PSA na inclusão (<0,5 vs ≥0,5 ng/mL); estadiamento patológico; Gleason.",
        "basal": "Mediana 63a; PSA mediano 0,3 ng/mL; pT3 em ~60%; Gleason ≥7 em ~75%; margem positiva em ~45%.",
        "n": "743 (374 RT + ADT; 369 RT isolada)",
        "molecular": "Sem critério molecular.",
        "biomarc": "PSA seriado.",
        "radiofarmaco": "Não aplicável (EBRT + goserelin)",
        "esquema": "RT de resgate ao leito prostático: 66 Gy/33 fr. ADT: goserelin 10,8 mg SC q3m × 2 doses (6 meses total), iniciado 2 m antes da RT.",
        "cumul": "66 Gy; Goserelin 6 meses",
        "comparador": "RT de resgate isolada (66 Gy) sem ADT.",
        "estatistica": "Endpoint primário: PFS (event-free survival). Poder 80%, HR 0,73, α 0,05.",
        "analises": "ITT. Kaplan-Meier.",
        "primario": "PFS em 5a: 80% (RT + ADT) vs 62% (RT isolada); HR 0,54 (IC 95% 0,43-0,68; p<0,0001). PFS em 10a (atualização 2022): 64% vs 49% (HR 0,55). MFS em 10a: 75% vs 69% (HR 0,73; p=0,04).",
        "secundario": "Atualização 2022: OS tendeu a favorecer combo (HR 0,69; p=0,09) mas sem significância convencional. QoL: toxicidade hormonal transitória.",
        "subgrupo": "Benefício em todos os subgrupos. Pacientes com PSA ≥0,5 e Gleason ≥7 se beneficiam mais.",
        "tox_g3": "Toxicidade hormonal (hot flashes, fadiga) como esperado. GU G3: 2%. GI G3: <1%.",
        "tox_interesse": "ADT curta (6m) tolerável; qualidade de vida retorna ao baseline em 6-12m pós-ADT.",
        "impacto_reg": "Primeira evidência fase III de benefício de ADT curta combinada a RT de resgate. ADT 6 meses durante RT de resgate agora em NCCN, EAU, ESTRO como recomendação. Junto com RTOG 9601 e RADICALS-HD, definiu padrão.",
        "limit": "66 Gy (inferior a doses modernas de 70+ Gy). Sem RT a linfonodos pélvicos. PSA threshold ≤2 — pacientes com carga maior não representados.",
        "ref": "Carrie C, et al. Lancet Oncol 2016;17:747-756. Atualização 10a: Carrie C, et al. Lancet Oncol 2019;20:1740-1749.",
        "category_id": "rt_prostata_local",
        "preparo": "Goserelin iniciado 2 m antes da RT. Planejamento com TC; leito prostático ± vesículas seminais.",
        "nct_url": "https://clinicaltrials.gov/study/NCT00423475",
        "pubmed_url": "https://pubmed.ncbi.nlm.nih.gov/27160475/",
        "ano_pub": 2016,
        "status": "Publicado",
    },
    {
        "estudo": "ARTISTIC (2023)",
        "acron": "ARTISTIC — Adjuvant radiotherapy and androgen deprivation: a meta-analysis of RADICALS-RT, RAVES, GETUG-AFU 17",
        "nct": "",
        "sponsor": "MRC CTU / Meta-análise colaborativa | PI: Chris Parker",
        "fase": "Meta-análise de 3 RCTs fase III (IPD)",
        "desenho": "Meta-análise com dados individuais dos 3 maiores RCTs comparando RT adjuvante vs RT de resgate precoce: RADICALS-RT (NCT00541047), RAVES (NCT00860652), GETUG-AFU 17 (NCT00667069). Total de 2.153 pacientes.",
        "centros": "Multicêntrico internacional (UK, Austrália, França)",
        "periodo": "Dados dos 3 trials: 2006-2019",
        "indicacao": "Câncer de próstata pós-prostatectomia com fatores adversos — adjuvante vs resgate precoce",
        "incl": "Conforme cada trial: pós-prostatectomia com fatores adversos (pT3, R1, Gleason alto).",
        "excl": "Conforme cada trial.",
        "estrat": "Margem cirúrgica; Gleason; PSA pós-op; trial de origem.",
        "basal": "2.153 pacientes totais; mediana 64a; pT3 ~60%; R1 ~50%.",
        "n": "2.153 (pool de 3 RCTs)",
        "molecular": "Sem critério molecular.",
        "biomarc": "PSA.",
        "radiofarmaco": "Não aplicável",
        "esquema": "RT adjuvante: 64-66 Gy iniciada <6 m pós-cirurgia. RT de resgate: mesma dose, trigger por PSA (>0,1-0,4 conforme trial).",
        "cumul": "64-66 Gy",
        "comparador": "RT adjuvante (imediata) vs RT de resgate precoce (triggered por PSA).",
        "estatistica": "Endpoint primário: event-free survival (EFS). Meta-análise com IPD; teste de interação; análise de subgrupos.",
        "analises": "IPD meta-analysis. Fixed-effect model.",
        "primario": "EFS em 5a: sem diferença significativa entre adjuvante vs resgate precoce (HR 0,95; IC 95% 0,80-1,14; p=0,60). No braço resgate, 39% nunca precisaram de RT.",
        "secundario": "MFS e OS sem diferença significativa. Toxicidade urinária: menos frequente com resgate (exposição reduzida). Sem heterogeneidade entre trials.",
        "subgrupo": "Nenhum subgrupo (Gleason, margens, T-stage) mostrou benefício da RT adjuvante. Mesmo pT3b/Gleason 8-10 tiveram resultados equivalentes.",
        "tox_g3": "Incidência cumulativa de toxicidade menor no braço resgate (menos pacientes irradiados desnecessariamente).",
        "tox_interesse": "39% dos pacientes randomizados para resgate NUNCA precisaram de RT — evitou tratamento desnecessário.",
        "impacto_reg": "Evidência definitiva de nível I (meta-análise IPD, >2.000 pacientes) que RT adjuvante pós-prostatectomia NÃO é superior a resgate precoce. Mudou paradigma globalmente. NCCN, EAU, ESTRO recomendam resgate precoce como abordagem padrão.",
        "limit": "Follow-up mediano ~5a (pode subestimar recidivas tardias). Nenhum trial usou PSMA-PET para estadiamento pré-resgate. Doses de RT ligeiramente inferiores às modernas.",
        "ref": "Vale CL, et al. Lancet 2023;401:1283-1292.",
        "category_id": "rt_prostata_local",
        "preparo": "Conforme protocolos individuais de cada trial.",
        "nct_url": "",
        "pubmed_url": "https://pubmed.ncbi.nlm.nih.gov/37003289/",
        "ano_pub": 2023,
        "status": "Publicado",
    },
    {
        "estudo": "SPORT (2024)",
        "acron": "SPORT — Single-fraction vs multi-fraction prostate SBRT",
        "nct": "NCT04249349",
        "sponsor": "Weill Cornell / PI: Jonathan Tward",
        "fase": "Fase 2, randomizado",
        "desenho": "Randomização 1:1 a SBRT fração única (24 Gy/1 fr) vs SBRT em 5 frações (40 Gy/5 fr) para próstata de risco baixo e intermediário favorável.",
        "centros": "Multicêntrico, EUA",
        "periodo": "2020 - 2024",
        "indicacao": "Câncer de próstata localizado de risco baixo ou intermediário favorável",
        "incl": "T1-T2b; Gleason ≤3+4; PSA ≤15; sem mets; próstata <80 cc.",
        "excl": "Alto risco; mets; TURP recente; próstata >80 cc; IPSS >20.",
        "estrat": "Risco; centro.",
        "basal": "Resultados preliminares — dados em maturação.",
        "n": "~168 planejados",
        "molecular": "Sem critério molecular.",
        "biomarc": "PSA seriado.",
        "radiofarmaco": "Não aplicável (SBRT)",
        "esquema": "Fração única: 24 Gy em 1 sessão. Multi-fração: 40 Gy em 5 frações (dias alternados, ~10 dias).",
        "cumul": "24 Gy (BED2 = 312 Gy) vs 40 Gy (BED2 = 200 Gy)",
        "comparador": "SBRT 5 frações (40 Gy/5 fr) — padrão de SBRT prostática.",
        "estatistica": "Endpoint primário: toxicidade GU G2+ em 6 meses. Não-inferioridade.",
        "analises": "ITT; comparação de toxicidade.",
        "primario": "Resultados preliminares de toxicidade em 6 meses: perfis semelhantes entre fração única e 5 frações. Seguimento oncológico em maturação.",
        "secundario": "bRFS, QoL, toxicidade tardia — em andamento.",
        "subgrupo": "Em maturação.",
        "tox_g3": "Dados preliminares: sem excesso de G3+ com fração única.",
        "tox_interesse": "Fronteira do ultra-hipofracionamento: próstata inteira em 1 única sessão. Viabilidade depende de IGRT intrafração sofisticado (MR-Linac ou Calypso).",
        "impacto_reg": "Se confirmado, poderá estabelecer SBRT em fração única como opção para próstata de baixo risco — conveniência máxima. Conceito de 'one-stop-shop' para próstata.",
        "limit": "Fase II; follow-up curto; seleção restrita (baixo risco e intermediário favorável). Tecnologia intrafração essencial.",
        "ref": "Tward J, et al. ASTRO 2024 (apresentação); trial em andamento.",
        "category_id": "rt_prostata_local",
        "preparo": "Hydrogel rectal spacer recomendado; MR-Linac ou Calypso para tracking intrafração; bexiga protocolo; imobilização.",
        "nct_url": "https://clinicaltrials.gov/study/NCT04249349",
        "pubmed_url": "",
        "ano_pub": 2024,
        "status": "Em andamento",
    },
]

# ───────────────────── STUDIES: RT CONSOLIDAÇÃO ─────────────────────
RT_CONSOLIDACAO = [
    {
        "estudo": "PACIFIC (2017/2022)",
        "acron": "PACIFIC — Durvalumab after chemoradiotherapy in unresectable stage III NSCLC",
        "nct": "NCT02125461",
        "sponsor": "AstraZeneca | PI: Scott Antonia",
        "fase": "Fase 3, randomizado, duplo-cego, placebo-controlado",
        "desenho": "Randomização 2:1 a durvalumab (anti-PD-L1) vs placebo após quimiorradioterapia definitiva com platina em NSCLC estágio III irressecável sem progressão.",
        "centros": "235 centros, 26 países",
        "periodo": "2014 - 2016",
        "indicacao": "NSCLC estágio III irressecável, sem progressão após quimiorradioterapia definitiva à base de platina",
        "incl": "NSCLC estágio III confirmado histologicamente; irressecável; ≥2 ciclos de QT à base de platina concomitante a RT (54-66 Gy); sem progressão pós-CRT; ECOG 0-1; randomizado em ≤42 dias pós-CRT.",
        "excl": "Doença autoimune ativa; pneumonite de radiação G2+; progressão após CRT; mets distantes.",
        "estrat": "Sexo; idade; tabagismo.",
        "basal": "Mediana 64a; 75% sexo masculino; não-escamoso 46%, escamoso 46%; PD-L1 ≥1% em ~63%.",
        "n": "713 (476 durvalumab, 237 placebo)",
        "molecular": "PD-L1 determinado (TC 73/22C3) mas inclusão independente de PD-L1; EGFR/ALK não excluídos.",
        "biomarc": "PD-L1 (TC 73/22C3); análises exploratórias de TMB e gene expression.",
        "radiofarmaco": "Não aplicável (IO pós-CRT)",
        "esquema": "Durvalumab 10 mg/kg IV q2sem por até 12 meses, iniciado ≤42 dias após última dose de RT.",
        "cumul": "Até 12 meses de durvalumab",
        "comparador": "Placebo IV q2sem por até 12 meses.",
        "estatistica": "Endpoints co-primários: PFS e OS. Poder 90% para PFS HR 0,67. α controlado.",
        "analises": "ITT. Kaplan-Meier. Sequencial para PFS → OS.",
        "primario": "PFS: 16,8 m vs 5,6 m (HR 0,52; IC 95% 0,42-0,65; p<0,001). OS (atualização 5a): 5a OS 42,9% vs 33,4% (HR 0,72; IC 0,59-0,89; p=0,002). Benefício sustentado.",
        "secundario": "ORR: 30% vs 17,8%. Duração de resposta: NR vs 18,4 m. TTDMo: 28,3 vs 16,2 m. Mets cerebrais: menores com durvalumab.",
        "subgrupo": "Benefício em todos os subgrupos de PD-L1 (≥1% maior benefício); escamoso e não-escamoso. PD-L1 <1%: benefício de PFS presente mas menor.",
        "tox_g3": "AE G3/4: 30,5% vs 26,1%. Pneumonite qualquer grau: 33,9% vs 24,8%; G3/4: 3,4% vs 2,6%.",
        "tox_interesse": "Pneumonite é o AE de interesse principal (combinação RT + IO); maioria G1-2. Endocrinopatias IO-relacionadas: tireoide (10%). Descontinuação por AE: 15,4% vs 9,8%.",
        "impacto_reg": "PACIFIC estabeleceu durvalumab pós-CRT como padrão global em NSCLC estágio III irressecável. Aprovação FDA (Fev/2018), EMA, ANVISA. Incorporado em NCCN, ESMO, SBOC. Maior avanço em NSCLC estágio III em décadas.",
        "limit": "PD-L1 <1% com benefício questionável (EMA restringiu a PD-L1 ≥1%). Sem comparação direta com IO + CRT concomitante (PACIFIC-2). EGFR/ALK positivos incluídos mas sem benefício claro.",
        "ref": "Antonia SJ, et al. NEJM 2017;377:1919-1929. Atualização 5a: Spigel DR, et al. JCO 2022;40:1301-1311.",
        "category_id": "rt_consolidacao",
        "preparo": "Início ≤42 dias pós-última fração de RT. Confirmar ausência de pneumonite G2+ antes de iniciar. Monitorar função tireoidiana e hepática.",
        "nct_url": "https://clinicaltrials.gov/study/NCT02125461",
        "pubmed_url": "https://pubmed.ncbi.nlm.nih.gov/28885881/",
        "ano_pub": 2017,
        "status": "Publicado",
    },
    {
        "estudo": "LAURA (2024)",
        "acron": "LAURA — Osimertinib after CRT in unresectable EGFR-mutant stage III NSCLC",
        "nct": "NCT03521154",
        "sponsor": "AstraZeneca | PI: Shun Lu",
        "fase": "Fase 3, randomizado, duplo-cego, placebo-controlado",
        "desenho": "Randomização 2:1 a osimertinib vs placebo após CRT definitiva em NSCLC EGFR-mutante estágio III irressecável.",
        "centros": "Multicêntrico internacional",
        "periodo": "2019 - 2023",
        "indicacao": "NSCLC EGFR-mutante (del19/L858R) estágio III irressecável, sem progressão após CRT definitiva",
        "incl": "NSCLC estágio III irressecável; mutação EGFR (del19 ou L858R); sem progressão pós-CRT; ECOG 0-1.",
        "excl": "Progressão pós-CRT; T790M prévia; pneumonite G2+.",
        "estrat": "Mutação EGFR (del19 vs L858R); estágio (IIIA vs IIIB/C); etnia.",
        "basal": "Mediana 61a; 60% feminino; Ásia 64%; del19 em 55%; IIIb/C em 62%.",
        "n": "216 (143 osimertinib, 73 placebo)",
        "molecular": "Mutação EGFR (del19/L858R) obrigatória. Teste central.",
        "biomarc": "EGFR mutação; ctDNA exploratório.",
        "radiofarmaco": "Não aplicável (TKI pós-CRT)",
        "esquema": "Osimertinib 80 mg VO 1×/dia até progressão ou toxicidade inaceitável.",
        "cumul": "Contínuo até progressão",
        "comparador": "Placebo 1×/dia.",
        "estatistica": "Endpoint primário: PFS (por investigador). Poder 80% para HR 0,55.",
        "analises": "ITT. Kaplan-Meier.",
        "primario": "PFS: 39,1 m (osimertinib) vs 5,6 m (placebo); HR 0,16 (IC 95% 0,10-0,24; p<0,001). Benefício dramático.",
        "secundario": "ORR: 57% vs 33%. Intracranial PFS: HR 0,17. OS imatura no momento da publicação. QoL: mantida.",
        "subgrupo": "Benefício consistente em del19 e L858R; todas as etnias; IIIA vs IIIB/C.",
        "tox_g3": "AE G3+: 35% vs 12%. Pneumonite de radiação G3: 3% vs 4%. Diarreia G3: 3%.",
        "tox_interesse": "Pneumonite (IO-like pattern com TKI pós-RT) em ~30% qualquer grau; maioria G1-2 e manejável. Rash G3: 3%. Intervalo QTc monitorado.",
        "impacto_reg": "Estabelece osimertinib como novo padrão pós-CRT em NSCLC EGFR-mutante estágio III (substitui durvalumab nesse subgrupo). Aprovação FDA (Jun/2024). NCCN incorporou.",
        "limit": "OS imatura. Duração de tratamento indefinida (custo). Interseção com PACIFIC em EGFR-mutante (PACIFIC sem benefício claro em EGFR+).",
        "ref": "Lu S, et al. NEJM 2024;391:585-597.",
        "category_id": "rt_consolidacao",
        "preparo": "Confirmar EGFR del19/L858R. Iniciar ≤6 semanas pós-CRT. Monitorar pneumonite, função hepática, QTc.",
        "nct_url": "https://clinicaltrials.gov/study/NCT03521154",
        "pubmed_url": "https://pubmed.ncbi.nlm.nih.gov/38828946/",
        "ano_pub": 2024,
        "status": "Publicado",
    },
    {
        "estudo": "KEYNOTE-799 (2023)",
        "acron": "KEYNOTE-799 — Pembrolizumab + CRT in unresectable locally advanced NSCLC",
        "nct": "NCT03631784",
        "sponsor": "Merck/MSD | PI: Corinne Faivre-Finn",
        "fase": "Fase 2, aberto, braço único (2 coortes)",
        "desenho": "Dois coortes: A (escamoso e não-escamoso com carboplatina-paclitaxel + RT + pembro) e B (não-escamoso com cisplatina-pemetrexed + RT + pembro). Pembrolizumab concomitante à CRT seguido de manutenção.",
        "centros": "Multicêntrico internacional",
        "periodo": "2018 - 2022",
        "indicacao": "NSCLC estágio III irressecável, pembrolizumab concomitante (não sequencial) à CRT",
        "incl": "NSCLC estágio III irressecável; ECOG 0-1; sem contraindicação a CRT; PD-L1 avaliado.",
        "excl": "Doença autoimune ativa; pneumonite prévia; EGFR/ALK positivos.",
        "estrat": "Histologia (coorte A vs B).",
        "basal": "Coorte A: 112 pacientes; Coorte B: 56 pacientes. Mediana ~65a.",
        "n": "216 (coorte A: 112; coorte B: 56; demais em expansão)",
        "molecular": "PD-L1 avaliado. EGFR/ALK excluídos.",
        "biomarc": "PD-L1 (22C3); TMB exploratório.",
        "radiofarmaco": "Não aplicável (IO concomitante a CRT)",
        "esquema": "Pembro 200 mg IV q3sem × 17 ciclos (1 ano). CRT: QT à base de platina + RT 60 Gy/30 fr. Pembro inicia ciclo 1 concomitante à CRT.",
        "cumul": "Até 17 ciclos de pembro",
        "comparador": "Sem braço comparador (fase II).",
        "estatistica": "Endpoint primário: ORR (RECIST 1.1) e segurança (taxa de pneumonite G3+).",
        "analises": "Full analysis set.",
        "primario": "ORR: Coorte A: 71,4% | Coorte B: 75,0%. Pneumonite G3+: 8,0% (Coorte A), 5,4% (Coorte B) — aceitável.",
        "secundario": "PFS mediana: Coorte A: ~30 m; Coorte B: ~27 m. DOR mediana: ~24 m. Taxas de PFS superiores ao controle histórico do PACIFIC.",
        "subgrupo": "Benefício em PD-L1 ≥1% e PD-L1 <1%. Escamoso e não-escamoso responderam.",
        "tox_g3": "AE G3+: ~55%. Pneumonite G3+: 5-8%. Esofagite G3: ~7%.",
        "tox_interesse": "Pneumonite G3+ (5-8%) ligeiramente maior que PACIFIC (3,4%) mas manejável. Esofagite aumentada (IO concomitante potencia toxicidade mucosa). Descontinuação de pembro por AE ~15%.",
        "impacto_reg": "Sugere que IO concomitante (não apenas sequencial como PACIFIC) é viável e pode melhorar desfechos. Base para KEYLYNK-012 (fase III, NCT04205773). Conceito de IO-CRT concomitante em evolução.",
        "limit": "Fase II sem braço comparador. Comparação indireta com PACIFIC. Toxicidade pulmonar aumentada merece atenção. Aguarda confirmação fase III.",
        "ref": "Jabbour SK, et al. JCO 2023;41:1997-2008.",
        "category_id": "rt_consolidacao",
        "preparo": "CRT padrão com planejamento IMRT/VMAT; dose pulmonar V20 <35%. Monitoramento de pneumonite intensificado.",
        "nct_url": "https://clinicaltrials.gov/study/NCT03631784",
        "pubmed_url": "https://pubmed.ncbi.nlm.nih.gov/36623248/",
        "ano_pub": 2023,
        "status": "Publicado",
    },
    {
        "estudo": "PACIFIC-2 (em andamento)",
        "acron": "PACIFIC-2 — Durvalumab concurrent with CRT in unresectable stage III NSCLC",
        "nct": "NCT03519971",
        "sponsor": "AstraZeneca | PI: Jay Bradbury",
        "fase": "Fase 3, randomizado, duplo-cego",
        "desenho": "Randomização 1:1 a durvalumab concomitante + CRT seguido de durvalumab de manutenção vs placebo + CRT seguido de durvalumab de manutenção. Testa se durvalumab concomitante (ao invés de apenas sequencial) adiciona benefício.",
        "centros": "Multicêntrico internacional",
        "periodo": "2018 - 2025",
        "indicacao": "NSCLC estágio III irressecável — durvalumab concomitante vs apenas sequencial a CRT",
        "incl": "NSCLC estágio III irressecável; sem mutações-alvo actionable; ECOG 0-1.",
        "excl": "EGFR/ALK mutante; doença autoimune; pneumonite prévia.",
        "estrat": "PD-L1 (≥1% vs <1%); estágio (IIIA vs IIIB/C); histologia.",
        "basal": "Em andamento — dados baseline em maturação.",
        "n": "~840 planejados",
        "molecular": "PD-L1 avaliado; EGFR/ALK excluídos.",
        "biomarc": "PD-L1; ctDNA exploratório.",
        "radiofarmaco": "Não aplicável",
        "esquema": "Ambos braços recebem durvalumab de manutenção pós-CRT (12 meses). Braço experimental: durvalumab também concomitante à CRT.",
        "cumul": "Durvalumab concomitante + manutenção vs manutenção apenas",
        "comparador": "Placebo concomitante + CRT, seguido de durvalumab de manutenção (padrão PACIFIC).",
        "estatistica": "Endpoint primário: PFS. Poder 80%, HR ~0,75.",
        "analises": "ITT.",
        "primario": "Em andamento — resultados primários esperados 2025.",
        "secundario": "OS, ORR, DOR, toxicidade, QoL.",
        "subgrupo": "Pré-especificados: PD-L1, histologia, estágio.",
        "tox_g3": "Monitoramento de pneumonite G3+ como segurança primária.",
        "tox_interesse": "Risco teórico de pneumonite aumentada com IO concomitante a RT torácica.",
        "impacto_reg": "Definirá se IO concomitante adiciona benefício ao paradigma PACIFIC de IO sequencial. Se positivo, muda padrão de cuidado globalmente.",
        "limit": "Em andamento. Risco de pneumonite com IO concomitante é concern principal.",
        "ref": "NCT03519971; protocolo registrado em ClinicalTrials.gov.",
        "category_id": "rt_consolidacao",
        "preparo": "Conforme protocolo PACIFIC adaptado para concomitância.",
        "nct_url": "https://clinicaltrials.gov/study/NCT03519971",
        "pubmed_url": "",
        "ano_pub": 2025,
        "status": "Em andamento",
    },
    {
        "estudo": "ADRIATIC (2024)",
        "acron": "ADRIATIC — Durvalumab ± tremelimumab after CRT in limited-stage SCLC",
        "nct": "NCT03703297",
        "sponsor": "AstraZeneca | PI: David R. Spigel",
        "fase": "Fase 3, randomizado, duplo-cego",
        "desenho": "Randomização 1:1:1 a durvalumab vs durvalumab + tremelimumab vs placebo como consolidação após CRT definitiva em SCLC estágio limitado (LS-SCLC).",
        "centros": "Multicêntrico internacional",
        "periodo": "2018 - 2023",
        "indicacao": "SCLC estágio limitado (LS-SCLC), sem progressão após CRT definitiva à base de platina",
        "incl": "SCLC estágio limitado histologicamente confirmado; sem progressão pós-CRT (4 ciclos platina-etoposide + RT torácica); ECOG 0-1; PCI permitido.",
        "excl": "Estágio extenso; progressão pós-CRT; doença autoimune.",
        "estrat": "PCI (sim/não); estágio (I-II vs III).",
        "basal": "Mediana 62a; PCI realizado em ~57%; estágio III em ~70%.",
        "n": "730 (264 durvalumab, 200 durva + treme, 266 placebo)",
        "molecular": "Sem critério molecular (SCLC tem poucas alterações targetable).",
        "biomarc": "Exploratório: PD-L1, TMB, ctDNA.",
        "radiofarmaco": "Não aplicável (IO consolidação)",
        "esquema": "Durvalumab 1.500 mg IV q4sem por até 24 meses. ± Tremelimumab 75 mg q4sem × 4 doses.",
        "cumul": "Até 24 meses de durvalumab",
        "comparador": "Placebo IV q4sem.",
        "estatistica": "Endpoints co-primários: OS (durva vs placebo) e PFS (durva vs placebo). Hierárquico.",
        "analises": "ITT. Kaplan-Meier.",
        "primario": "OS (durva vs placebo): HR 0,73 (IC 95% 0,57-0,93; p=0,0104) — mediana 55,9 vs 33,4 m. PFS: HR 0,76 (p=0,02). Primeiro tratamento a melhorar OS em LS-SCLC em >30 anos.",
        "secundario": "Durva + treme: OS HR 0,74 (p=0,03) vs placebo — similar a durva isolado. Sem benefício adicional claro do tremelimumab.",
        "subgrupo": "Benefício consistente com/sem PCI. Estágio III benefício similar a I-II.",
        "tox_g3": "AE G3/4: 24,4% (durva) vs 24,2% (placebo). Pneumonite G3: 2,6% vs 0,8%.",
        "tox_interesse": "Pneumonite G3+ baixa (~3%). Endocrinopatias IO-related: tireoidite em 12%. Perfil de segurança favorável pós-CRT torácica.",
        "impacto_reg": "Primeiro tratamento a melhorar OS em LS-SCLC desde PCI (1999). Durvalumab pós-CRT agora é novo padrão em LS-SCLC. Aprovação FDA esperada 2025. Paradigma PACIFIC expandido para SCLC limitado.",
        "limit": "PCI não obrigatório (uso variou). Tremelimumab sem benefício adicional claro. Follow-up limitado para toxicidade muito tardia.",
        "ref": "Spigel DR, et al. NEJM 2024;391:1313-1327.",
        "category_id": "rt_consolidacao",
        "preparo": "Confirmação de ausência de progressão pós-CRT. PCI completado antes da randomização (se indicado). Monitorar função tireoidiana.",
        "nct_url": "https://clinicaltrials.gov/study/NCT03703297",
        "pubmed_url": "https://pubmed.ncbi.nlm.nih.gov/39321357/",
        "ano_pub": 2024,
        "status": "Publicado",
    },
    {
        "estudo": "EVEREST / NRG-GU003 (2023)",
        "acron": "EVEREST — Escalated vs standard dose salvage RT + ADT for prostate cancer after prostatectomy",
        "nct": "NCT01978379",
        "sponsor": "NRG Oncology | PI: Mark Hallman",
        "fase": "Fase 3, randomizado, dose-escalation",
        "desenho": "Randomização 1:1 a RT de resgate dose padrão (64,8 Gy) vs dose escalada (70,2 Gy) ao leito prostático. ADT (4-6 meses) em subgrupo selecionado.",
        "centros": "Multicêntrico, EUA e Canadá",
        "periodo": "2014 - 2019",
        "indicacao": "Câncer de próstata com recidiva bioquímica pós-prostatectomia, candidato a RT de resgate",
        "incl": "Pós-prostatectomia; recidiva bioquímica (PSA 0,1-4,0 ng/mL); pT2-3; N0/Nx; sem mets.",
        "excl": "PSA >4; pN1; mets; RT prévia; doença locorregional macroscópica.",
        "estrat": "ADT (sim/não); PSA (<0,5 vs ≥0,5); Gleason (≤7 vs ≥8); margem.",
        "basal": "Mediana 64a; PSA mediano 0,35 ng/mL; pT3 em ~55%; Gleason 7 em ~55%.",
        "n": "460 (229 padrão, 231 escalada)",
        "molecular": "Sem critério molecular.",
        "biomarc": "PSA seriado.",
        "radiofarmaco": "Não aplicável",
        "esquema": "Padrão: 64,8 Gy/36 fr (1,8 Gy/fr). Escalada: 70,2 Gy/39 fr (1,8 Gy/fr). IMRT/VMAT obrigatório.",
        "cumul": "70,2 Gy (braço escalado)",
        "comparador": "RT de resgate dose padrão: 64,8 Gy/36 fr.",
        "estatistica": "Endpoint primário: freedom from progression (FFP). Poder 80%, HR 0,70, α 0,05.",
        "analises": "ITT. Kaplan-Meier.",
        "primario": "FFP em 5a: 75,9% (70,2 Gy) vs 68,6% (64,8 Gy); HR 0,73 (IC 95% 0,53-1,01; p=0,055) — borderline. PSA-PFS: HR 0,65 (p=0,01) favorecendo dose escalada.",
        "secundario": "MFS: sem diferença significativa no follow-up atual. Toxicidade GU tardia G2+: 19% vs 15% (NS). Toxicidade GI G2+: 4% vs 3% (NS).",
        "subgrupo": "Pacientes com PSA ≥0,5 e Gleason ≥8 podem se beneficiar mais da dose escalada.",
        "tox_g3": "GU G3: 3% vs 2%. GI G3: <1%. Perfil aceitável.",
        "tox_interesse": "Dose escalada (70,2 Gy) tolerável com IMRT/VMAT moderna. Incremento de toxicidade pequeno.",
        "impacto_reg": "Suporta dose escalada (70,2 Gy) como opção no resgate pós-prostatectomia. Informará atualização de guidelines sobre dose ótima de resgate. NRG/ASTRO.",
        "limit": "p=0,055 para endpoint primário. Follow-up ainda curto para OS e MFS. Sem PSMA-PET para estadiamento.",
        "ref": "Hallman MA, et al. JCO 2023;41:4055-4062.",
        "category_id": "rt_consolidacao",
        "preparo": "IMRT/VMAT obrigatório; bexiga cheia/reto vazio; planejamento com fusão MRI recomendada.",
        "nct_url": "https://clinicaltrials.gov/study/NCT01978379",
        "pubmed_url": "https://pubmed.ncbi.nlm.nih.gov/37467449/",
        "ano_pub": 2023,
        "status": "Publicado",
    },
    {
        "estudo": "SCORAD-III (2022)",
        "acron": "SCORAD-III — Single-fraction vs multi-fraction RT for painful bone metastases",
        "nct": "NCT01248585",
        "sponsor": "Dutch Bone Metastasis Study Group | PI: Yvette van der Linden",
        "fase": "Fase 3, randomizado, não-inferioridade",
        "desenho": "Randomização 1:1 a fração única (8 Gy × 1) vs múltiplas frações (24 Gy/6 fr ou 20 Gy/5 fr) para mets ósseas dolorosas complicadas (com massa tecidual mole ou risco de fratura/compressão).",
        "centros": "Multicêntrico, Holanda e UK",
        "periodo": "2011 - 2018",
        "indicacao": "Metástases ósseas dolorosas complicadas (componente de partes moles ou risco neurológico/fratura)",
        "incl": "Met óssea dolorosa complicada: massa de partes moles ≥5 cm, ou risco de fratura patológica, ou compressão medular (sem indicação cirúrgica de emergência). Qualquer primário.",
        "excl": "Compressão medular com indicação cirúrgica imediata; RT prévia ao mesmo sítio.",
        "estrat": "Indicação (partes moles vs risco fratura vs compressão); sítio; primário.",
        "basal": "Múltiplos primários (pulmão 28%, mama 22%, próstata 20%); idade mediana 66a; massa de partes moles em 55%.",
        "n": "470 (236 fração única, 234 multi-frações)",
        "molecular": "Sem critério molecular.",
        "biomarc": "Sem biomarcadores.",
        "radiofarmaco": "Não aplicável (RT paliativa externa)",
        "esquema": "Fração única: 8 Gy × 1. Multi-frações: 24 Gy/6 fr ou 20 Gy/5 fr.",
        "cumul": "8 Gy vs 20-24 Gy",
        "comparador": "Multi-frações (24 Gy/6 fr ou 20 Gy/5 fr) — padrão para mets complicadas.",
        "estatistica": "Endpoint primário: resposta de dor em 9 semanas (escala VAS). Não-inferioridade: margem 10%.",
        "analises": "ITT.",
        "primario": "Resposta de dor: 53% (fração única) vs 56% (multi-frações); diferença -3% (IC 95% -12 a +6%) — confirma não-inferioridade de fração única mesmo em mets complicadas.",
        "secundario": "Retratamento necessário: 6% (fração única) vs 2% (multi-frações) — maior com fração única como esperado. Qualidade de vida: equivalente. Sobrevida: sem diferença.",
        "subgrupo": "Não-inferioridade mantida em todos os subtipos de complicação (partes moles, risco fratura, compressão).",
        "tox_g3": "Mínima em ambos. Fratura patológica: 3% vs 2% (NS).",
        "tox_interesse": "Sem aumento de fratura patológica com fração única. Conveniência: 1 visita vs 5-6.",
        "impacto_reg": "Demonstra que fração única é não-inferior mesmo em mets ósseas COMPLICADAS (antes restrita a não-complicadas). Simplifica tratamento paliativo globalmente. Reduz carga ao paciente.",
        "limit": "Taxas de retratamento maiores com fração única (esperado). Follow-up limitado pela população (paliativa). Definição de complicada variou.",
        "ref": "van der Linden YM, et al. Lancet Oncol 2023;24:e160. Rich SE, et al. JCO 2018;36:2802-2810.",
        "category_id": "rt_consolidacao",
        "preparo": "Planejamento simples; sem imobilização sofisticada. Analgesia adequada antes e durante.",
        "nct_url": "https://clinicaltrials.gov/study/NCT01248585",
        "pubmed_url": "https://pubmed.ncbi.nlm.nih.gov/30118434/",
        "ano_pub": 2022,
        "status": "Publicado",
    },
    {
        "estudo": "STARS / ROSEL (2015)",
        "acron": "STARS / ROSEL — SBRT vs lobectomy for operable stage I NSCLC",
        "nct": "NCT00840749",
        "sponsor": "MD Anderson (STARS) / Dutch (ROSEL) | PI: Jack A. Roth, Joe Y. Chang",
        "fase": "Fase 2/3, randomizado (análise pooled de 2 RCTs encerrados precocemente)",
        "desenho": "Randomização a SBRT (54 Gy/3 fr ou 50 Gy/4 fr) vs lobectomia com dissecção linfonodal mediastinal em NSCLC estágio I operável. Ambos os trials encerraram por recrutamento lento; dados poolados.",
        "centros": "STARS: MD Anderson (EUA); ROSEL: Holanda (multicêntrico)",
        "periodo": "2009 - 2013 (ambos encerrados precocemente)",
        "indicacao": "NSCLC estágio I periférico (T1-T2a N0), candidatos operáveis (medically operable)",
        "incl": "NSCLC T1-T2a N0 (≤5 cm); medicamente operáveis; ECOG 0-1; PET-FDG negativo para N2.",
        "excl": "Tumores centrais; N1/N2 confirmado; inoperáveis por comorbidade.",
        "estrat": "Tamanho tumoral; centro.",
        "basal": "Mediana 67a; T1 em ~70%; tumor mediano 2,5 cm; PFTs normais (operáveis).",
        "n": "58 (análise pooled: 31 SBRT, 27 cirurgia)",
        "molecular": "Sem critério molecular. PET-FDG para estadiamento.",
        "biomarc": "Sem biomarcadores obrigatórios.",
        "radiofarmaco": "Não aplicável (SBRT)",
        "esquema": "SBRT: STARS — 54 Gy/3 fr; ROSEL — 54 Gy/3 fr (periférico) ou 60 Gy/5 fr (semi-central). Cirurgia: lobectomia + dissecção linfonodal.",
        "cumul": "54 Gy/3 fr (BED10 = 151,2 Gy)",
        "comparador": "Lobectomia com dissecção linfonodal mediastinal (padrão cirúrgico).",
        "estatistica": "Análise pooled exploratória. Não powered para comparação definitiva.",
        "analises": "ITT pooled.",
        "primario": "OS em 3a: 95% (SBRT) vs 79% (cirurgia); HR 0,14 (IC 95% 0,017-1,190; p=0,037). Resultado controverso pelo n pequeno.",
        "secundario": "rPFS em 3a: 86% vs 80%. Mortalidade perioperatória cirúrgica: 4% (1 paciente). Toxicidade SBRT: G3 10% (dor torácica, dispneia). Controle local SBRT: 100% em 3a.",
        "subgrupo": "N muito pequeno para subgrupos.",
        "tox_g3": "SBRT: G3 10% (dor torácica). Cirurgia: mortalidade perioperatória 4%, complicações pós-op 44%.",
        "tox_interesse": "SBRT sem mortalidade perioperatória vs 4% com cirurgia. Morbidade pós-op significativa com lobectomia (complicações em 44%).",
        "impacto_reg": "Primeiro (e provocativo) RCT comparando SBRT vs cirurgia em NSCLC operável. Lançou debate global SBRT vs cirurgia. Base para VALOR (NCT02984761), STABLE-MATES, e ensaios SABRTooth. Não muda padrão por n pequeno, mas prova equipoise para randomização.",
        "limit": "N=58 (muito pequeno). Encerrado precocemente. Análise pooled de 2 trials diferentes. Resultado de OS controverso. Sem endpoint patológico (upstaging cirúrgico em 30% dos pacientes na prática clínica).",
        "ref": "Chang JY, et al. Lancet Oncol 2015;16:630-637.",
        "category_id": "rt_consolidacao",
        "preparo": "PET-FDG para estadiamento. TC 4D; imobilização; IGRT com CBCT. Fiduciais opcionais.",
        "nct_url": "https://clinicaltrials.gov/study/NCT00840749",
        "pubmed_url": "https://pubmed.ncbi.nlm.nih.gov/25981812/",
        "ano_pub": 2015,
        "status": "Publicado",
    },
]

# ───────────────────── MERGE INTO data.js ─────────────────────
with open(DATA_PATH, "r", encoding="utf-8") as f:
    content = f.read()

import json, re

match = re.search(r"window\.THERA_DATA\s*=\s*(\{.*\})", content, re.DOTALL)
if not match:
    raise ValueError("Could not parse THERA_DATA from data.js")

data = json.loads(match.group(1))

print(f"Before: {len(data['categories'])} categories, {len(data['studies'])} studies")

# Add new categories
for cat in NEW_CATEGORIES:
    if not any(c["id"] == cat["id"] for c in data["categories"]):
        data["categories"].append(cat)
        print(f"  Added category: {cat['id']} ({cat['name']})")
    else:
        print(f"  Category already exists: {cat['id']}")

# Add studies and set derived fields
all_new = RT_OLIGO + RT_PROSTATA + RT_CONSOLIDACAO
for study in all_new:
    cat_id = study["category_id"]
    cat = next((c for c in data["categories"] if c["id"] == cat_id), None)
    if cat:
        study["category_name"] = cat["name"]
        study["category_short"] = cat["short"]
        study["category_color"] = cat["color"]

    existing_uids = {s["uid"] for s in data["studies"] if "uid" in s}
    idx = sum(1 for s in data["studies"] if s.get("category_id") == cat_id)
    study["uid"] = f"{cat_id}_{idx}"

    while study["uid"] in existing_uids:
        idx += 1
        study["uid"] = f"{cat_id}_{idx}"

    data["studies"].append(study)

# Update category counts
for cat in data["categories"]:
    count = sum(1 for s in data["studies"] if s.get("category_id") == cat["id"])
    cat["count"] = count

print(f"After: {len(data['categories'])} categories, {len(data['studies'])} studies")

# Count new studies per category
for cat in NEW_CATEGORIES:
    cnt = sum(1 for s in all_new if s["category_id"] == cat["id"])
    print(f"  {cat['id']}: {cnt} studies")

# Write back
header = content[:match.start()]
footer = content[match.end():]
json_str = json.dumps(data, ensure_ascii=False)
output = header + "window.THERA_DATA = " + json_str + footer

with open(DATA_PATH, "w", encoding="utf-8") as f:
    f.write(output)

print(f"\nDone! Written to {DATA_PATH}")
