
  // ============== CABEÇA E PESCOÇO · CEC ==============
  {
    id: 'nct06525220',
    nome: 'HN1',
    titulo: 'A Phase 3 Study to Evaluate Petosemtamab Plus Pembrolizumab vs Pembrolizumab in First-line Treatment of Head and Neck Cancer (LiGeR - HN1)',
    nct: 'NCT06525220',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'cabeca_pescoco',
    neoplasia_label: 'Cabeça e pescoço · CEC',
    subtipo: '',
    linha_terapeutica: '1ª linha',
    cenario_clinico: '1ª linha',
    modalidade: ["bispecífico", "combinação", "imunoterapia"],
    biomarcadores: ["PD-L1"],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Petosemtamab + Pembrolizumab',
    comparador: 'Braço controle conforme protocolo',
    racional: 'This is a Phase 3 randomized, open-label study to evaluate the efficacy and safety of petosemtamab plus pembrolizumab vs pembrolizumab in first-line treatment of recurrent or metastatic PD-L1+ head and neck squamous cell carcinoma.',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Belo Horizonte / MG", "São Paulo / SP", "Natal / RN", "Rio de Janeiro / RJ", "Recife / PE", "Porto Alegre / RS"],
    estados: ["MG", "PE", "RJ", "RN", "RS", "SP"],
    cidades: ["Natal", "Rio de Janeiro", "Recife", "Porto Alegre", "São Paulo", "Belo Horizonte"],
    patrocinador: 'Merus B.V.',
    fonte_url: 'https://clinicaltrials.gov/study/NCT06525220',
    contato_url: 'https://clinicaltrials.gov/study/NCT06525220',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct07276399',
    nome: 'NCT07276399',
    titulo: 'A Study of Amivantamab in Addition to Standard of Care Agents (SOC) Compared With SOC Alone in Participants With Recurrent/Metastatic Head and Neck Cancer',
    nct: 'NCT07276399',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'cabeca_pescoco',
    neoplasia_label: 'Cabeça e pescoço · CEC',
    subtipo: '',
    linha_terapeutica: 'Recidivado / refratário',
    cenario_clinico: 'Recidivado / refratário',
    modalidade: ["bispecífico", "combinação", "imunoterapia", "quimioterapia"],
    biomarcadores: [],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Amivantamab + Pembrolizumab + Carboplatin + 5-Flurouracil',
    comparador: 'Braço controle conforme protocolo',
    racional: 'The purpose of this study is to compare anti-tumor activity of amivantamab in addition to pembrolizumab and carboplatin versus pembrolizumab, 5-fluorouracil (FU), and platinum therapy (carboplatin or cisplatin) in participants with refractory/metasta',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["São José do Rio Preto / SP", "Jaú / SP", "São Paulo / SP", "Natal / RN", "Vitória / ES", "Porto Alegre / RS"],
    estados: ["ES", "RN", "RS", "SP"],
    cidades: ["Vitória", "Natal", "Porto Alegre", "São Paulo", "São José do Rio Preto", "Jaú"],
    patrocinador: 'Janssen Research & Development, LLC',
    fonte_url: 'https://clinicaltrials.gov/study/NCT07276399',
    contato_url: 'https://clinicaltrials.gov/study/NCT07276399',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct05319730',
    nome: 'MK-3475',
    titulo: 'A Study to Evaluate Investigational Agents With or Without Pembrolizumab (MK-3475) in Participants With Advanced Esophageal Cancer Previously Exposed to Programmed Cell Death 1 Protein (PD-1)/ Program',
    nct: 'NCT05319730',
    fase: 'Ib/II',
    status: 'Recrutando',
    neoplasia: 'cabeca_pescoco',
    neoplasia_label: 'Cabeça e pescoço · CEC',
    subtipo: '',
    linha_terapeutica: '2ª linha',
    cenario_clinico: '2ª linha',
    modalidade: ["ADC", "combinação", "imunoterapia", "quimioterapia", "terapia-alvo"],
    biomarcadores: ["PD-L1"],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Paclitaxel + Irinotecan + Pembrolizumab + MK-4830',
    comparador: 'Braço controle conforme protocolo',
    racional: 'This is a Phase 1/2, multicenter, randomized, open-label umbrella platform study to evaluate the safety and efficacy of investigational agents with or without pembrolizumab and/or chemotherapy, for the treatment of participants with second line (2L)',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Porto Alegre / RS", "São Paulo / SP", "Natal / RN"],
    estados: ["RN", "RS", "SP"],
    cidades: ["Porto Alegre", "São Paulo", "Natal"],
    patrocinador: 'Merck Sharp & Dohme LLC',
    fonte_url: 'https://clinicaltrials.gov/study/NCT05319730',
    contato_url: 'https://clinicaltrials.gov/study/NCT05319730',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct06780111',
    nome: 'MK-3475',
    titulo: 'Substudy 06E: Umbrella Study of Combination Therapies in Esophageal Cancer (MK-3475-06E/KEYMAKER-U06)',
    nct: 'NCT06780111',
    fase: 'Ib/II',
    status: 'Recrutando',
    neoplasia: 'cabeca_pescoco',
    neoplasia_label: 'Cabeça e pescoço · CEC',
    subtipo: '',
    linha_terapeutica: '1ª linha',
    cenario_clinico: '1ª linha',
    modalidade: ["ADC", "combinação", "imunoterapia", "quimioterapia"],
    biomarcadores: [],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Pembrolizumab + I-DXd + Leucovorin + Levoleucovorin',
    comparador: 'Braço controle conforme protocolo',
    racional: 'Researchers are looking for new ways to treat esophageal squamous cell carcinoma (ESCC). ESCC is a type of cancer that starts in certain cells that line the esophagus. The esophagus is the tube that connects the throat to the stomach. This study will',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Porto Alegre / RS", "Natal / RN"],
    estados: ["RN", "RS"],
    cidades: ["Porto Alegre", "Natal"],
    patrocinador: 'Merck Sharp & Dohme LLC',
    fonte_url: 'https://clinicaltrials.gov/study/NCT06780111',
    contato_url: 'https://clinicaltrials.gov/study/NCT06780111',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct06806852',
    nome: 'HNSCC',
    titulo: 'A Study to Test Whether Treatment With BI 770371 in Combination With Pembrolizumab With or Without Cetuximab Helps People With Head and Neck Cancer Compared With Pembrolizumab Alone',
    nct: 'NCT06806852',
    fase: 'I',
    status: 'Recrutando',
    neoplasia: 'cabeca_pescoco',
    neoplasia_label: 'Cabeça e pescoço · CEC',
    subtipo: '',
    linha_terapeutica: '1ª linha',
    cenario_clinico: '1ª linha',
    modalidade: ["imunoterapia"],
    biomarcadores: [],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'BI 770371 + Pembrolizumab + Cetuximab',
    comparador: 'Braço controle conforme protocolo',
    racional: 'This study is open to adults with head and neck cancer. The purpose of this study is to find out whether combining different study medicines makes tumors shrink in people with head and neck cancer. The tested medicines in this study are antibodies t',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["São José do Rio Preto / SP", "Barretos / SP", "Natal / RN"],
    estados: ["RN", "SP"],
    cidades: ["Barretos", "São José do Rio Preto", "Natal"],
    patrocinador: 'Boehringer Ingelheim',
    fonte_url: 'https://clinicaltrials.gov/study/NCT06806852',
    contato_url: 'https://clinicaltrials.gov/study/NCT06806852',
    data_atualizacao: '2026-05-19',
  },

  // ============== CÉRVIX ==============
  {
    id: 'nct07216703',
    nome: 'MK-2870',
    titulo: 'A Clinical Study of Sacituzumab Tirumotecan (MK-2870) in Combination With Pembrolizumab (MK-3475) as First-line Maintenance Treatment of Cervical Cancer (MK-2870-036/TroFuse-036/GOG-3123/ENGOT-cx22)',
    nct: 'NCT07216703',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'cervix',
    neoplasia_label: 'Cérvix',
    subtipo: '',
    linha_terapeutica: '1ª linha',
    cenario_clinico: '1ª linha',
    modalidade: ["ADC", "anti-angiogênico", "combinação", "imunoterapia", "quimioterapia"],
    biomarcadores: ["PD-L1"],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Pembrolizumab + Sacituzumab Tirumotecan + Bevacizumab + Paclitaxel',
    comparador: 'Braço controle conforme protocolo',
    racional: 'Researchers are looking for new ways to treat metastatic cervical cancer. Cervical cancer is cancer in the cervix, the lower part of the uterus (womb). Metastatic means the cancer has spread to other parts of the body. Researchers want to learn abou',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["São José do Rio Preto / SP", "Barretos / SP", "São Paulo / SP", "Natal / RN", "Porto Alegre / RS"],
    estados: ["RN", "RS", "SP"],
    cidades: ["Natal", "Porto Alegre", "Barretos", "São Paulo", "São José do Rio Preto"],
    patrocinador: 'Merck Sharp & Dohme LLC',
    fonte_url: 'https://clinicaltrials.gov/study/NCT07216703',
    contato_url: 'https://clinicaltrials.gov/study/NCT07216703',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct06459180',
    nome: 'MK-2870',
    titulo: 'A Study to Compare Sacituzumab Tirumotecan (MK-2870) Monotherapy Versus Treatment of Physician\'s Choice as Second-line Treatment for Participants With Recurrent or Metastatic Cervical Cancer (MK-2870-',
    nct: 'NCT06459180',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'cervix',
    neoplasia_label: 'Cérvix',
    subtipo: '',
    linha_terapeutica: '2ª linha',
    cenario_clinico: '2ª linha',
    modalidade: ["ADC", "combinação", "quimioterapia"],
    biomarcadores: ["PD-L1"],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Sacituzumab Tirumotecan + Pemetrexed + Tisotumab Vedotin + Topotecan',
    comparador: 'Braço controle conforme protocolo',
    racional: 'This study will have two phases: a sacituzumab tirumotecan safety run-in and a Phase 3 portion. The safety run-in phase will be used to evaluate the efficacy and safety of sacituzumab tirumotecan at the dose for evaluation in the Phase 3 portion. The',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Curitiba / PR", "São Paulo / SP", "Rio de Janeiro / RJ", "Joinville / SC", "Porto Alegre / RS"],
    estados: ["PR", "RJ", "RS", "SC", "SP"],
    cidades: ["Joinville", "Rio de Janeiro", "Curitiba", "Porto Alegre", "São Paulo"],
    patrocinador: 'Merck Sharp & Dohme LLC',
    fonte_url: 'https://clinicaltrials.gov/study/NCT06459180',
    contato_url: 'https://clinicaltrials.gov/study/NCT06459180',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct06670911',
    nome: 'NCT06670911',
    titulo: 'Low-dose Pembrolizumab Plus Chemotherapy for the First-Line Treatment of Persistent, Recurrent, or Metastatic Cervical Cancer.',
    nct: 'NCT06670911',
    fase: 'II',
    status: 'Recrutando',
    neoplasia: 'cervix',
    neoplasia_label: 'Cérvix',
    subtipo: '',
    linha_terapeutica: '1ª linha',
    cenario_clinico: '1ª linha',
    modalidade: ["combinação", "imunoterapia", "quimioterapia"],
    biomarcadores: ["PD-L1"],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Low-dose Pembrolizumab Plus Chemotherapy (Paclitaxel plus Carboplatin or Cisplatin)',
    comparador: 'Braço controle conforme protocolo',
    racional: 'This is a phase II single-arm study of low-dose pembrolizumab (100mg, fixed-dose) plus chemotherapy in women aged 18 years or older with histologically confirmed persistent, recurrent, or metastatic cervical cancer who are ineligible for curative-int',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Rio de Janeiro / RJ"],
    estados: ["RJ"],
    cidades: ["Rio de Janeiro"],
    patrocinador: 'Instituto Nacional de Cancer, Brazil',
    fonte_url: 'https://clinicaltrials.gov/study/NCT06670911',
    contato_url: 'https://clinicaltrials.gov/study/NCT06670911',
    data_atualizacao: '2026-05-19',
  },

  // ============== ENDOMÉTRIO ==============
  {
    id: 'nct06989112',
    nome: 'T-DXd',
    titulo: 'DESTINY-Endometrial01: A Phase III Study of Trastuzumab Deruxtecan Plus Rilvegostomig or Pembrolizumab as First-Line Treatment of HER2-Expressing (IHC 3+/2+), Mismatch Repair Proficient (pMMR) Endomet',
    nct: 'NCT06989112',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'endometrio',
    neoplasia_label: 'Endométrio',
    subtipo: '',
    linha_terapeutica: '1ª linha',
    cenario_clinico: '1ª linha',
    modalidade: ["ADC", "combinação", "imunoterapia", "quimioterapia"],
    biomarcadores: ["HER2"],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Trastuzumab deruxtecan + Rilvegostomig + Pembrolizumab + Carboplatin',
    comparador: 'Braço controle conforme protocolo',
    racional: 'DESTINY-Endometrial01 will investigate the efficacy of first-line T-DXd + rilvegostomig (Arm A) and/or T-DXd+ pembrolizumab (Arm B) when compared to chemotherapy (carboplatin + paclitaxel) + pembrolizumab (Arm C), by assessment of progression free su',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Barretos / SP", "Belo Horizonte / MG", "São Paulo / SP", "Salvador / BA", "Londrina", "Rio de Janeiro / RJ", "Teresina", "Porto Alegre / RS"],
    estados: ["BA", "GO", "MG", "RJ", "RS", "SP"],
    cidades: ["Goiânia", "Teresina", "Rio de Janeiro", "Salvador", "Porto Alegre", "Barretos", "São Paulo", "Londrina", "Belo Horizonte"],
    patrocinador: 'AstraZeneca',
    fonte_url: 'https://clinicaltrials.gov/study/NCT06989112',
    contato_url: 'https://clinicaltrials.gov/study/NCT06989112',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct06952504',
    nome: 'MK-2870',
    titulo: 'A Study to Compare Sacituzumab Tirumotecan (MK-2870) in Combination With Pembrolizumab (MK-3475) Versus Pembrolizumab Alone as Treatment in Participants With Mismatch Repair Proficient Endometrial Can',
    nct: 'NCT06952504',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'endometrio',
    neoplasia_label: 'Endométrio',
    subtipo: '',
    linha_terapeutica: '1ª linha',
    cenario_clinico: '1ª linha',
    modalidade: ["ADC", "combinação", "imunoterapia", "quimioterapia"],
    biomarcadores: [],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Pembrolizumab + Carboplatin + Paclitaxel + Docetaxel',
    comparador: 'Braço controle conforme protocolo',
    racional: 'Researchers are looking for new ways to treat people with proficient mismatch repair (pMMR) endometrial cancer (EC) that is advanced or recurrent. * EC is a type of cancer that starts in the tissues inside the uterus (womb) * pMMR indicates that cer',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["São Paulo / SP", "Natal / RN", "Rio de Janeiro / RJ", "Porto Alegre / RS", "Goiânia / GO"],
    estados: ["GO", "RJ", "RN", "RS", "SP"],
    cidades: ["Goiânia", "Natal", "Rio de Janeiro", "Porto Alegre", "São Paulo"],
    patrocinador: 'Merck Sharp & Dohme LLC',
    fonte_url: 'https://clinicaltrials.gov/study/NCT06952504',
    contato_url: 'https://clinicaltrials.gov/study/NCT06952504',
    data_atualizacao: '2026-05-19',
  },

  // ============== GÁSTRICO / GEJ ==============
  {
    id: 'nct04379596',
    nome: 'T-DXd',
    titulo: 'Ph1b/2 Study of the Safety and Efficacy of T-DXd Combinations in Advanced HER2-expressing Gastric Cancer (DESTINY-Gastric03)',
    nct: 'NCT04379596',
    fase: 'II',
    status: 'Recrutando',
    neoplasia: 'gastrico',
    neoplasia_label: 'Gástrico / GEJ',
    subtipo: '',
    linha_terapeutica: 'Avançado / metastático',
    cenario_clinico: 'Avançado / metastático',
    modalidade: ["ADC", "combinação", "imunoterapia", "quimioterapia"],
    biomarcadores: ["HER2"],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Fluorouracil (5-FU) + Capecitabine + Durvalumab + Oxaliplatin',
    comparador: 'Braço controle conforme protocolo',
    racional: 'DESTINY-Gastric03 will investigate the safety, tolerability, pharmacokinetics, immunogenicity, and preliminary antitumor activity of trastuzumab deruxtecan (T-DXd) alone or in combination with chemotherapy and/or immunotherapy in HER2-expressing adva',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["São Jose Do Rio Preto / SP", "São Paulo / SP", "Natal / RN", "Londrina", "Rio de Janeiro / RJ", "Florianópolis", "Porto Alegre / RS", "Ribeirão Preto / SP"],
    estados: ["RJ", "RN", "RS", "SP"],
    cidades: ["Ribeirão Preto", "Natal", "Rio de Janeiro", "São Jose Do Rio Preto", "Porto Alegre", "São Paulo", "Santa Maria", "Londrina", "Florianópolis"],
    patrocinador: 'AstraZeneca',
    fonte_url: 'https://clinicaltrials.gov/study/NCT04379596',
    contato_url: 'https://clinicaltrials.gov/study/NCT04379596',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct06445972',
    nome: 'MK-3475',
    titulo: 'Substudy 06D: Combination Therapies in Second Line (2L) Gastroesophageal Adenocarcinoma (MK-3475-06D/Keymaker-U06)',
    nct: 'NCT06445972',
    fase: 'Ib/II',
    status: 'Recrutando',
    neoplasia: 'gastrico',
    neoplasia_label: 'Gástrico / GEJ',
    subtipo: '',
    linha_terapeutica: '1ª linha',
    cenario_clinico: '1ª linha',
    modalidade: ["ADC", "combinação", "quimioterapia"],
    biomarcadores: [],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Ramucirumab + Paclitaxel + Sacituzumab Tirumotecan + HER3-DXd',
    comparador: 'Braço controle conforme protocolo',
    racional: 'This is a phase 1/2 multicenter, open-label umbrella platform study that will evaluate the safety and efficacy of sacituzumab tirumotecan (MK-2870) plus paclitaxel versus ramucirumab plus paclitaxel, and HER3-DXD plus ramucirumab versus ramucirumab p',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Porto Alegre / RS", "São Paulo / SP", "Natal / RN"],
    estados: ["RN", "RS", "SP"],
    cidades: ["Porto Alegre", "São Paulo", "Natal"],
    patrocinador: 'Merck Sharp & Dohme LLC',
    fonte_url: 'https://clinicaltrials.gov/study/NCT06445972',
    contato_url: 'https://clinicaltrials.gov/study/NCT06445972',
    data_atualizacao: '2026-05-19',
  },

  // ============== HEPATOCARCINOMA · CHC ==============
  {
    id: 'nct06921785',
    nome: 'NCT06921785',
    titulo: 'Phase III Study of Rilvegostomig in Combination With Bevacizumab With or Without Tremelimumab as First-line Treatment of Hepatocellular Carcinoma',
    nct: 'NCT06921785',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'hcc',
    neoplasia_label: 'Hepatocarcinoma · CHC',
    subtipo: '',
    linha_terapeutica: '1ª linha',
    cenario_clinico: '1ª linha',
    modalidade: ["anti-angiogênico", "combinação", "imunoterapia"],
    biomarcadores: [],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Tremelimumab + Rilvegostomig + Bevacizumab + Atezolizumab',
    comparador: 'Braço controle conforme protocolo',
    racional: 'This is a Phase III, randomised, open-label, sponsor-blinded, 3-arm, multicentre, global study assessing the efficacy and safety of rilvegostomig in combination with bevacizumab with or without tremelimumab compared to atezolizumab in combination wit',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Barretos / SP", "São Paulo / SP", "Vitória / ES", "Porto Alegre / RS", "Santa Maria"],
    estados: ["ES", "RS", "SP"],
    cidades: ["Vitória", "Porto Alegre", "Barretos", "São Paulo", "Santa Maria"],
    patrocinador: 'AstraZeneca',
    fonte_url: 'https://clinicaltrials.gov/study/NCT06921785',
    contato_url: 'https://clinicaltrials.gov/study/NCT06921785',
    data_atualizacao: '2026-05-19',
  },

  // ============== LINFOMA ==============
  {
    id: 'nct06191744',
    nome: 'R2',
    titulo: 'Study of Subcutaneous Epcoritamab in Combination With Intravenous Rituximab and Oral Lenalidomide (R2) to Assess Adverse Events and Change in Disease Activity in Adult Participants With Previously Unt',
    nct: 'NCT06191744',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'linfoma',
    neoplasia_label: 'Linfoma',
    subtipo: '',
    linha_terapeutica: '1ª linha',
    cenario_clinico: '1ª linha',
    modalidade: ["bispecífico", "combinação", "quimioterapia"],
    biomarcadores: ["CD20"],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Epcoritamab + Prednisone + Rituximab + Lenalidomide',
    comparador: 'Braço controle conforme protocolo',
    racional: 'Follicular lymphoma (FL) is the second most common B-cell cancer and the most common type of cancer of lymphocytes. Unfortunately, this disease is incurable with conventional treatment and the disease recurs in almost all patients. This study will as',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Belo Horizonte / MG", "Brasília / DF", "Jaú / SP", "Curitiba / PR", "São Paulo / SP", "Rio de Janeiro / RJ", "Ribeirão Preto / SP"],
    estados: ["DF", "MG", "PR", "RJ", "SP"],
    cidades: ["Brasília", "Ribeirão Preto", "Rio de Janeiro", "Curitiba", "São Paulo", "Belo Horizonte", "Jaú"],
    patrocinador: 'Genmab',
    fonte_url: 'https://clinicaltrials.gov/study/NCT06191744',
    contato_url: 'https://clinicaltrials.gov/study/NCT06191744',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct06084936',
    nome: 'NCT06084936',
    titulo: 'A Study to Evaluate Glofitamab as a Single Agent vs. Investigator\'s Choice in Participants With Relapsed/Refractory Mantle Cell Lymphoma',
    nct: 'NCT06084936',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'linfoma',
    neoplasia_label: 'Linfoma',
    subtipo: '',
    linha_terapeutica: 'Recidivado / refratário',
    cenario_clinico: 'Recidivado / refratário',
    modalidade: ["bispecífico", "combinação", "quimioterapia"],
    biomarcadores: [],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Obinutuzumab + Glofitamab + Rituximab + Bendamustine',
    comparador: 'Braço controle conforme protocolo',
    racional: 'The purpose of this study is to evaluate the efficacy of glofitamab monotherapy compared with an investigator\'s choice of either rituximab plus bendamustine (BR), or lenalidomide with rituximab (R-Len) in patients with relapsed or refractory (R/R) ma',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Curitiba / PR", "São Paulo / SP", "Salvador / BA", "Rio de Janeiro / RJ", "Porto Alegre / RS"],
    estados: ["BA", "PR", "RJ", "RS", "SP"],
    cidades: ["Rio de Janeiro", "Curitiba", "Salvador", "Porto Alegre", "São Paulo"],
    patrocinador: 'Hoffmann-La Roche',
    fonte_url: 'https://clinicaltrials.gov/study/NCT06084936',
    contato_url: 'https://clinicaltrials.gov/study/NCT06084936',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct05533775',
    nome: 'NCT05533775',
    titulo: 'A Study to Evaluate Glofitamab Monotherapy and Glofitamab + Chemoimmunotherapy in Pediatric and Young Adult Participants With Relapsed/Refractory Mature B-Cell Non-Hodgkin Lymphoma',
    nct: 'NCT05533775',
    fase: 'Ib/II',
    status: 'Recrutando',
    neoplasia: 'linfoma',
    neoplasia_label: 'Linfoma',
    subtipo: '',
    linha_terapeutica: 'Recidivado / refratário',
    cenario_clinico: 'Recidivado / refratário',
    modalidade: ["bispecífico", "combinação", "quimioterapia"],
    biomarcadores: ["CD20"],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Obinutuzumab + Glofitamab + Rituximab + Ifosfamide',
    comparador: 'Braço controle conforme protocolo',
    racional: 'The purpose of this study is to evaluate the safety and efficacy of glofitamab, as monotherapy and in combination with a standard chemoimmunotherapy regimen: rituximab, ifosfamide, carboplatin, and etoposide (R-ICE) in pediatric and young adult parti',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Curitiba / PR", "São Paulo / SP"],
    estados: ["PR", "SP"],
    cidades: ["São Paulo", "Curitiba"],
    patrocinador: 'Hoffmann-La Roche',
    fonte_url: 'https://clinicaltrials.gov/study/NCT05533775',
    contato_url: 'https://clinicaltrials.gov/study/NCT05533775',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct05660395',
    nome: 'LOTIS-10',
    titulo: 'A Study to Evaluate the Pharmacokinetics and Safety of Loncastuximab Tesirine in Participants With Relapsed or Refractory Diffuse Large B-cell Lymphoma or High-grade B-cell Lymphoma With Hepatic Impai',
    nct: 'NCT05660395',
    fase: 'I',
    status: 'Recrutando',
    neoplasia: 'linfoma',
    neoplasia_label: 'Linfoma',
    subtipo: '',
    linha_terapeutica: 'Recidivado / refratário',
    cenario_clinico: 'Recidivado / refratário',
    modalidade: ["ADC"],
    biomarcadores: [],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Loncastuximab Tesirine',
    comparador: 'Braço controle conforme protocolo',
    racional: 'The primary objective of this study is to determine the recommended dosing regimen of loncastuximab tesirine in diffuse large B-cell lymphoma (DLBCL) or high-grade B-cell lymphoma (HGBCL) participants with moderate and severe hepatic impairment.',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["São Paulo / SP", "Porto Alegre / RS", "Brasília / DF"],
    estados: ["DF", "RS", "SP"],
    cidades: ["Porto Alegre", "São Paulo", "Brasília"],
    patrocinador: 'ADC Therapeutics S.A.',
    fonte_url: 'https://clinicaltrials.gov/study/NCT05660395',
    contato_url: 'https://clinicaltrials.gov/study/NCT05660395',
    data_atualizacao: '2026-05-19',
  },

  // ============== MAMA ==============
  {
    id: 'nct05950945',
    nome: 'T-DXd',
    titulo: 'Trastuzumab Deruxtecan (T-DXd) in Patients Who Have Hormone Receptor-negative and Hormone Receptor-positive HER2-low or HER2 IHC 0 Metastatic Breast Cancer',
    nct: 'NCT05950945',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'mama',
    neoplasia_label: 'Mama',
    subtipo: '',
    linha_terapeutica: 'Avançado / metastático',
    cenario_clinico: 'Avançado / metastático',
    modalidade: ["ADC"],
    biomarcadores: ["HER2"],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Trastuzumab Deruxtecan',
    comparador: 'Braço controle conforme protocolo',
    racional: 'This study will evaluate the safety and efficacy of trastuzumab deruxtecan (T-DXd) in participants with human epidermal growth factor receptor 2 (HER2)-low or HER2 immunohistochemistry (IHC) 0 (who are both hormone receptor \\[HR\\]-negative and HR-pos',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["São José do Rio Preto / SP", "Rio Grande / RS", "Santo André / SP", "Brasília / DF", "Jaú / SP", "Curitiba / PR", "São Paulo / SP", "Salvador / BA"],
    estados: ["BA", "DF", "PR", "RS", "SP"],
    cidades: ["Brasília", "Rio Grande", "Santa Catarina", "Curitiba", "Salvador", "Ijuí", "Santo André", "São José do Rio Preto", "São Paulo", "Londrina", "Riberão Preto", "Florianópolis", "Jaú"],
    patrocinador: 'Daiichi Sankyo',
    fonte_url: 'https://clinicaltrials.gov/study/NCT05950945',
    contato_url: 'https://clinicaltrials.gov/study/NCT05950945',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct06966700',
    nome: 'MK-2870',
    titulo: 'A Clinical Study of Sacituzumab Tirumotecan (Sac-TMT, MK-2870) in People With Breast Cancer (MK-2870-032)',
    nct: 'NCT06966700',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'mama',
    neoplasia_label: 'Mama',
    subtipo: '',
    linha_terapeutica: '1ª linha',
    cenario_clinico: '1ª linha',
    modalidade: ["ADC", "combinação", "imunoterapia", "quimioterapia", "terapia-alvo"],
    biomarcadores: ["TNBC"],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Sacituzumab tirumotecan + Pembrolizumab + Rescue Medication + Carboplatin',
    comparador: 'Braço controle conforme protocolo',
    racional: 'Researchers are looking for new ways to treat types of breast cancer that are both: * High-risk, which means the cancer may have a higher chance of getting worse or coming back after treatment * Early-stage, which means the cancer is in the breast o',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["São José do Rio Preto / SP", "Barretos / SP", "Passo Fundo / RS", "Blumenau / SC", "Natal / RN", "Rio de Janeiro / RJ", "Porto Alegre / RS", "Fortaleza / CE"],
    estados: ["CE", "GO", "RJ", "RN", "RS", "SC", "SP"],
    cidades: ["Goiânia", "Passo Fundo", "Blumenau", "Natal", "Rio de Janeiro", "Porto Alegre", "Barretos", "São José do Rio Preto", "Fortaleza"],
    patrocinador: 'Merck Sharp & Dohme LLC',
    fonte_url: 'https://clinicaltrials.gov/study/NCT06966700',
    contato_url: 'https://clinicaltrials.gov/study/NCT06966700',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct04862663',
    nome: 'CAPItello-292',
    titulo: 'Capivasertib + CDK4/6i + Fulvestrant for Advanced/Metastatic HR+/HER2- Breast Cancer (CAPItello-292)',
    nct: 'NCT04862663',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'mama',
    neoplasia_label: 'Mama',
    subtipo: '',
    linha_terapeutica: 'Avançado / metastático',
    cenario_clinico: 'Avançado / metastático',
    modalidade: ["terapia-alvo"],
    biomarcadores: ["HER2"],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Capivasertib + Fulvestrant + Palbociclib + Ribociclib',
    comparador: 'Braço controle conforme protocolo',
    racional: 'A Phase Ib/III Open-label, Randomised Study of Capivasertib plus CDK4/6 Inhibitors and Fulvestrant versus CDK4/6 Inhibitors and Fulvestrant in Hormone Receptor-Positive and Human Epidermal Growth Factor Receptor 2-Negative Locally Advanced, Unresecta',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Blumenau / SC", "Taubaté / SP", "São Paulo / SP", "Natal / RN", "Teresina", "Vitória / ES", "Alfenas", "Porto Velho"],
    estados: ["ES", "RN", "RS", "SC", "SP"],
    cidades: ["Teresina", "Blumenau", "Natal", "Vitória", "Porto Velho", "Taubaté", "Porto Alegre", "São Paulo", "Alfenas"],
    patrocinador: 'AstraZeneca',
    fonte_url: 'https://clinicaltrials.gov/study/NCT04862663',
    contato_url: 'https://clinicaltrials.gov/study/NCT04862663',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct06380751',
    nome: 'AZD5305',
    titulo: 'Saruparib (AZD5305) Plus Camizestrant Compared With CDK4/6 Inhibitor Plus Endocrine Therapy or Plus Camizestrant in HR-Positive, HER2-Negative (IHC 0, 1+, 2+/ ISH Non-amplified), BRCA1, BRCA2, or PALB',
    nct: 'NCT06380751',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'mama',
    neoplasia_label: 'Mama',
    subtipo: '',
    linha_terapeutica: '1ª linha',
    cenario_clinico: '1ª linha',
    modalidade: ["terapia-alvo"],
    biomarcadores: ["BRCA", "HER2"],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Saruparib (AZD5305) + Camizestrant + Abemaciclib + Ribociclib',
    comparador: 'Braço controle conforme protocolo',
    racional: 'The primary objective of the study is to measure efficacy of saruparib (AZD5305) plus camizestrant compared with physician\'s choice CDK4/6i plus ET in patients with BRCA1, BRCA2, or PALB2m, HR-positive, HER2-negative (defined as IHC 0, 1+, 2+/ ISH no',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Fortaleza / CE", "Jaú / SP", "Curitiba / PR", "São Paulo / SP", "Salvador / BA", "Porto Alegre / RS", "Cachoeira de Itapemirim", "Ribeirão Preto / SP"],
    estados: ["BA", "CE", "GO", "PR", "RS", "SP"],
    cidades: ["Ribeirão Preto", "Goiânia", "Cachoeira de Itapemirim", "Curitiba", "Salvador", "Porto Alegre", "São Paulo", "Fortaleza", "Jaú"],
    patrocinador: 'AstraZeneca',
    fonte_url: 'https://clinicaltrials.gov/study/NCT06380751',
    contato_url: 'https://clinicaltrials.gov/study/NCT06380751',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct05633654',
    nome: 'ASCENT-05',
    titulo: 'Study of Sacituzumab Govitecan-hziy and Pembrolizumab Versus Treatment of Physician\'s Choice in Patients With Triple Negative Breast Cancer Who Have Residual Invasive Disease After Surgery and Neoadju',
    nct: 'NCT05633654',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'mama',
    neoplasia_label: 'Mama',
    subtipo: '',
    linha_terapeutica: 'Perioperatório',
    cenario_clinico: 'Perioperatório',
    modalidade: ["ADC", "combinação", "imunoterapia"],
    biomarcadores: ["HER2"],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Sacituzumab govitecan-hziy (SG) + Pembrolizumab + Capecitabine',
    comparador: 'Braço controle conforme protocolo',
    racional: 'The goal of this study is to find out if the experimental product, sacituzumab govitecan-hziy (SG) in combination with pembrolizumab given after surgery, is effective and safe compared to the treatment of physician\'s choice (TPC) which includes eithe',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Brasília / DF", "Curitiba / PR", "Itajaí / PR", "São Paulo / SP", "Natal / RN", "Salvador / BA", "Teresina", "Porto Alegre / RS"],
    estados: ["BA", "DF", "PR", "RN", "RS", "SP"],
    cidades: ["Brasília", "Teresina", "Natal", "Curitiba", "Salvador", "Porto Alegre", "São Paulo", "Itajaí"],
    patrocinador: 'Gilead Sciences',
    fonte_url: 'https://clinicaltrials.gov/study/NCT05633654',
    contato_url: 'https://clinicaltrials.gov/study/NCT05633654',
    data_atualizacao: '2026-05-19',
  },

  // ============== MELANOMA ==============
  {
    id: 'nct06112314',
    nome: 'MEL-301',
    titulo: 'IMC-F106C Regimen Versus Nivolumab Regimens in Previously Untreated Advanced Melanoma (PRISM-MEL-301)',
    nct: 'NCT06112314',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'melanoma',
    neoplasia_label: 'Melanoma',
    subtipo: '',
    linha_terapeutica: '1ª linha',
    cenario_clinico: '1ª linha',
    modalidade: ["imunoterapia"],
    biomarcadores: [],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Brenetafusp + Nivolumab + Nivolumab + Relatlimab',
    comparador: 'Braço controle conforme protocolo',
    racional: 'This is a phase 3, randomized, controlled study of brenetafusp (IMC-F106C) plus nivolumab compared to standard nivolumab regimens in HLA-A\\*02:01-positive participants with previously untreated advanced melanoma.',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Barretos / SP", "Brasília / DF", "Liberdade / SP", "São Paulo / SP", "Rio de Janeiro / RJ", "Florianópolis", "Ijuí / RS", "Porto Alegre / RS"],
    estados: ["CE", "DF", "RJ", "RS", "SP"],
    cidades: ["Brasília", "Rio de Janeiro", "Porto Alegre", "Barretos", "São Paulo", "Ijuí", "Fortaleza", "Liberdade", "Florianópolis"],
    patrocinador: 'Immunocore Ltd',
    fonte_url: 'https://clinicaltrials.gov/study/NCT06112314',
    contato_url: 'https://clinicaltrials.gov/study/NCT06112314',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct04291105',
    nome: 'NCT04291105',
    titulo: 'Phase 2 Trial of Voyager V1 in Combination With Cemiplimab in Cancer Patients',
    nct: 'NCT04291105',
    fase: 'II',
    status: 'Recrutando',
    neoplasia: 'melanoma',
    neoplasia_label: 'Melanoma',
    subtipo: '',
    linha_terapeutica: '1ª linha',
    cenario_clinico: '1ª linha',
    modalidade: ["imunoterapia"],
    biomarcadores: ["PD-L1"],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'VV1 + Cemiplimab',
    comparador: 'Braço controle conforme protocolo',
    racional: 'This is a Phase 2 study designed to determine the preliminary anti-tumor activity and confirm the safety of VV1 in combination with cemiplimab. The study will enroll patients with three distinct separate tumor cohorts. The cancers types are colorecta',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Rio de Janeiro / RJ", "Barretos / SP", "Porto Alegre / RS", "Salvador / BA"],
    estados: ["BA", "RJ", "RS", "SP"],
    cidades: ["Rio de Janeiro", "Barretos", "Salvador", "Porto Alegre"],
    patrocinador: 'Vyriad, Inc.',
    fonte_url: 'https://clinicaltrials.gov/study/NCT04291105',
    contato_url: 'https://clinicaltrials.gov/study/NCT04291105',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct02332668',
    nome: 'MK-3475',
    titulo: 'A Study of Pembrolizumab (MK-3475) in Pediatric Participants With an Advanced Solid Tumor or Lymphoma (MK-3475-051/KEYNOTE-051)',
    nct: 'NCT02332668',
    fase: 'Ib/II',
    status: 'Recrutando',
    neoplasia: 'melanoma',
    neoplasia_label: 'Melanoma',
    subtipo: '',
    linha_terapeutica: 'Recidivado / refratário',
    cenario_clinico: 'Recidivado / refratário',
    modalidade: ["imunoterapia"],
    biomarcadores: ["PD-L1"],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Pembrolizumab',
    comparador: 'Braço controle conforme protocolo',
    racional: 'Researchers are looking for new ways to treat children with different types of melanoma (skin cancer), solid tumors, and lymphomas (blood cancers) that are any of these: * Advanced, which means cancer spread in the body or cannot be removed with sur',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["São Paulo / SP"],
    estados: ["SP"],
    cidades: ["São Paulo"],
    patrocinador: 'Merck Sharp & Dohme LLC',
    fonte_url: 'https://clinicaltrials.gov/study/NCT02332668',
    contato_url: 'https://clinicaltrials.gov/study/NCT02332668',
    data_atualizacao: '2026-05-19',
  },

  // ============== MIELOMA MÚLTIPLO ==============
  {
    id: 'nct06208150',
    nome: 'Tal-P',
    titulo: 'A Study Comparing Talquetamab Plus Pomalidomide, Talquetamab Plus Teclistamab, and Elotuzumab, Pomalidomide, and Dexamethasone or Pomalidomide, Bortezomib, and Dexamethasone in Participants With Relap',
    nct: 'NCT06208150',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'mieloma',
    neoplasia_label: 'Mieloma Múltiplo',
    subtipo: '',
    linha_terapeutica: 'Recidivado / refratário',
    cenario_clinico: 'Recidivado / refratário',
    modalidade: ["bispecífico", "combinação", "quimioterapia"],
    biomarcadores: [],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Talquetamab + Pomalidomide + Teclistamab + Elotuzumab',
    comparador: 'Braço controle conforme protocolo',
    racional: 'The purpose of this study is to compare the effectiveness of either talquetamab plus pomalidomide (Tal-P) or talquetamab plus teclistamab (Tal-Tec) with elotuzumab, pomalidomide, and dexamethasone (EPd) or pomalidomide, bortezomib, and dexamethasone',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["São José do Rio Preto / SP", "Brasília / DF", "Belo Horizonte / MG", "Curitiba / PR", "São Paulo / SP", "Salvador / BA", "Rio de Janeiro / RJ", "Recife / PE"],
    estados: ["BA", "DF", "MG", "PE", "PR", "RJ", "RS", "SP"],
    cidades: ["Brasília", "Rio de Janeiro", "Recife", "Curitiba", "Salvador", "Porto Alegre", "São Paulo", "São José do Rio Preto", "Caxias do Sul", "Belo Horizonte"],
    patrocinador: 'Janssen Research & Development, LLC',
    fonte_url: 'https://clinicaltrials.gov/study/NCT06208150',
    contato_url: 'https://clinicaltrials.gov/study/NCT06208150',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct05552222',
    nome: 'Tec-DR',
    titulo: 'A Study of Teclistamab in Combination With Daratumumab and Lenalidomide (Tec-DR) and Talquetamab in Combination With Daratumumab and Lenalidomide (Tal-DR) in Participants With Newly Diagnosed Multiple',
    nct: 'NCT05552222',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'mieloma',
    neoplasia_label: 'Mieloma Múltiplo',
    subtipo: '',
    linha_terapeutica: 'Avançado / metastático',
    cenario_clinico: 'Avançado / metastático',
    modalidade: ["bispecífico", "combinação", "quimioterapia"],
    biomarcadores: [],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Teclistamab + Daratumumab + Lenalidomide + Dexamethasone',
    comparador: 'Braço controle conforme protocolo',
    racional: 'The purpose of this study is to compare the efficacy of teclistamab in combination with daratumumab and lenalidomide (Tec-DR) and talquetamab in combination with daratumumab and lenalidomide (Tal-DR) versus daratumumab, lenalidomide, dexamethasone (D',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Barretos / SP", "Belo Horizonte / MG", "Curitiba / PR", "São Paulo / SP", "Natal / RN", "Salvador / BA", "Niterói", "Porto Alegre / RS"],
    estados: ["BA", "CE", "MG", "PR", "RN", "RS", "SP"],
    cidades: ["Ribeirão Preto", "Niterói", "Natal", "Curitiba", "Salvador", "Porto Alegre", "Barretos", "São Paulo", "Fortaleza", "Belo Horizonte"],
    patrocinador: 'Janssen Research & Development, LLC',
    fonte_url: 'https://clinicaltrials.gov/study/NCT05552222',
    contato_url: 'https://clinicaltrials.gov/study/NCT05552222',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct06152575',
    nome: 'EPd',
    titulo: 'MagnetisMM-32: A Study to Learn About the Study Medicine Called Elranatamab in People With Multiple Myeloma (MM) That Has Come Back After Taking Other Treatments (Including Prior Treatment With an Ant',
    nct: 'NCT06152575',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'mieloma',
    neoplasia_label: 'Mieloma Múltiplo',
    subtipo: '',
    linha_terapeutica: 'Recidivado / refratário',
    cenario_clinico: 'Recidivado / refratário',
    modalidade: ["bispecífico", "combinação", "quimioterapia"],
    biomarcadores: [],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Elranatamab + Elotuzumab + Pomalidomide + Dexamethasone',
    comparador: 'Braço controle conforme protocolo',
    racional: 'The purpose of this study is to learn about the study medicine called elranatamab.This study aims to compare elranatamab to other medicines for the treatment of MM (a type of cancer). This study is seeking participants who: * Are 18 years of age or',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Jaú / SP", "São Paulo / SP", "Salvador / BA", "Rio de Janeiro / RJ", "SP", "Niterói", "Porto Alegre / RS", "Ribeirão Preto / SP"],
    estados: ["BA", "RJ", "RS", "SP"],
    cidades: ["Ribeirão Preto", "Niterói", "Rio de Janeiro", "Salvador", "Porto Alegre", "São Paulo", "SP", "Jaú"],
    patrocinador: 'Pfizer',
    fonte_url: 'https://clinicaltrials.gov/study/NCT06152575',
    contato_url: 'https://clinicaltrials.gov/study/NCT06152575',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct06679101',
    nome: 'BRd',
    titulo: 'A Study of Belantamab Mafodotin Administered in Combination With Lenalidomide and Dexamethasone (BRd) Versus Daratumumab, Lenalidomide, and Dexamethasone (DRd) in Participants With Newly Diagnosed Mul',
    nct: 'NCT06679101',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'mieloma',
    neoplasia_label: 'Mieloma Múltiplo',
    subtipo: '',
    linha_terapeutica: 'Avançado / metastático',
    cenario_clinico: 'Avançado / metastático',
    modalidade: ["ADC", "combinação", "quimioterapia"],
    biomarcadores: [],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Belantamab mafodotin + Lenalidomide + Dexamethasone + Daratumumab',
    comparador: 'Braço controle conforme protocolo',
    racional: 'The purpose of this Phase 3 study is to evaluate if BRd prolongs progression free survival (PFS) and/or improves minimal residual disease (MRD) negative status compared with DRd in participants with TI-NDMM.',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Barretos / SP", "São Paulo / SP", "Salvador / BA", "Teresina", "Vitória / ES", "Joinville / SC", "Porto Alegre / RS"],
    estados: ["BA", "ES", "RS", "SC", "SP"],
    cidades: ["Joinville", "Teresina", "Vitória", "Salvador", "Porto Alegre", "Barretos", "São Paulo"],
    patrocinador: 'GlaxoSmithKline',
    fonte_url: 'https://clinicaltrials.gov/study/NCT06679101',
    contato_url: 'https://clinicaltrials.gov/study/NCT06679101',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct05020236',
    nome: 'PF-06863135',
    titulo: 'A Study to Learn About the Study Medicine Elranatamab Alone and With Daratumumab in People With Multiple Myeloma Who Have Received Other Treatments',
    nct: 'NCT05020236',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'mieloma',
    neoplasia_label: 'Mieloma Múltiplo',
    subtipo: '',
    linha_terapeutica: 'Recidivado / refratário',
    cenario_clinico: 'Recidivado / refratário',
    modalidade: ["bispecífico", "combinação", "quimioterapia"],
    biomarcadores: ["BCMA"],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Elranatamab + Daratumumab + Pomalidomide + Dexamethasone',
    comparador: 'Braço controle conforme protocolo',
    racional: 'The purpose of this clinical trial is to (1) learn whether the BCMA-CD3 bispecific antibody elranatamab can provide more benefit to people with multiple myeloma compared to a combination therapy including daratumumab, pomalidomide, and dexamethasone,',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["São Paulo / SP", "Salvador / BA", "Rio de Janeiro / RJ", "SP", "Porto Alegre / RS"],
    estados: ["BA", "RJ", "RS", "SP"],
    cidades: ["Rio de Janeiro", "Salvador", "Porto Alegre", "São Paulo", "SP"],
    patrocinador: 'Pfizer',
    fonte_url: 'https://clinicaltrials.gov/study/NCT05020236',
    contato_url: 'https://clinicaltrials.gov/study/NCT05020236',
    data_atualizacao: '2026-05-19',
  },

  // ============== PÂNCREAS ==============
  {
    id: 'nct07076121',
    nome: 'NCT07076121',
    titulo: 'A Study Comparing BMS-986504 in Combination With Nab-paclitaxel and Gemcitabine Versus Placebo in Combination With Nab-paclitaxel and Gemcitabine in Participants With Untreated Metastatic Pancreatic D',
    nct: 'NCT07076121',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'pancreas',
    neoplasia_label: 'Pâncreas',
    subtipo: '',
    linha_terapeutica: 'Avançado / metastático',
    cenario_clinico: 'Avançado / metastático',
    modalidade: ["combinação", "quimioterapia", "terapia-alvo"],
    biomarcadores: [],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'BMS-986504 + Gemcitabine + Nab-paclitaxel',
    comparador: 'Placebo',
    racional: 'The purpose of this study is to assess the safety and efficacy of BMS-986504, a selective, MTA-cooperative PRMT5 inhibitor, in combination with Nab-paclitaxel/Gemcitabine (nab-p/gem) versus placebo in combination with nab-p/gem, in participants with',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Barretos / SP", "Belo Horizonte / MG", "São Paulo / SP", "Salvador / BA", "Natal / RN", "Rio de Janeiro / RJ", "Santa Cruz do Sul / RS", "Vitória / ES"],
    estados: ["BA", "ES", "MG", "RJ", "RN", "RS", "SP"],
    cidades: ["Santa Cruz do Sul", "Natal", "Rio de Janeiro", "Vitória", "Salvador", "Barretos", "São Paulo", "Belo Horizonte"],
    patrocinador: 'Bristol-Myers Squibb',
    fonte_url: 'https://clinicaltrials.gov/study/NCT07076121',
    contato_url: 'https://clinicaltrials.gov/study/NCT07076121',
    data_atualizacao: '2026-05-19',
  },

  // ============== PRÓSTATA ==============
  {
    id: 'nct06136650',
    nome: 'NHA',
    titulo: 'A Study of Opevesostat (MK-5684) Versus Alternative Next-generation Hormonal Agent (NHA) in Metastatic Castration-resistant Prostate Cancer (mCRPC) Post One NHA (MK-5684-004)',
    nct: 'NCT06136650',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'prostata',
    neoplasia_label: 'Próstata',
    subtipo: '',
    linha_terapeutica: 'Avançado / metastático',
    cenario_clinico: 'Avançado / metastático',
    modalidade: ["terapia-alvo"],
    biomarcadores: [],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Opevesostat + Dexamethasone + Fludrocortisone acetate + Hydrocortisone',
    comparador: 'Braço controle conforme protocolo',
    racional: 'The purpose of this study is to assess the efficacy and safety of opevesostat plus hormone replacement therapy (HRT) compared to alternative abiraterone acetate or enzalutamide in participants with Metastatic Castration-resistant Prostate Cancer (mCR',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["São José do Rio Preto / SP", "Belo Horizonte / MG", "São Luís / MA", "Taubaté / SP", "Curitiba / PR", "Itajaí / PR", "São Paulo / SP", "Salvador / BA"],
    estados: ["BA", "CE", "ES", "MA", "MG", "PR", "RS", "SP"],
    cidades: ["Vitória", "Uberaba", "Taubaté", "Curitiba", "Salvador", "Porto Alegre", "São Paulo", "São José do Rio Preto", "Bragança Paulista", "Fortaleza", "Belo Horizonte", "São Luís", "Itajaí"],
    patrocinador: 'Merck Sharp & Dohme LLC',
    fonte_url: 'https://clinicaltrials.gov/study/NCT06136650',
    contato_url: 'https://clinicaltrials.gov/study/NCT06136650',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct06629779',
    nome: 'MEVROMETOSTAT',
    titulo: 'A Study to Learn How PF-06821497 (Mevrometostat) Works in Men With Metastatic Castration-resistant Prostate Cancer.',
    nct: 'NCT06629779',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'prostata',
    neoplasia_label: 'Próstata',
    subtipo: '',
    linha_terapeutica: 'Avançado / metastático',
    cenario_clinico: 'Avançado / metastático',
    modalidade: ["terapia-alvo"],
    biomarcadores: [],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'PF-06821497 + Enzalutamide',
    comparador: 'Placebo',
    racional: 'This study will explore whether a combination of the investigational drug PF-06821497 and enzalutamide will work better than taking enzalutamide alone in participants with mCRPC who are ARSi or abiraterone naïve.',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["São José do Rio Preto / SP", "Barretos / SP", "Santo André / SP", "Brasília / DF", "São Paulo / SP", "Natal / RN", "Salvador / BA", "Porto Alegre / RS"],
    estados: ["BA", "CE", "DF", "RN", "RS", "SP"],
    cidades: ["Brasília", "Natal", "Salvador", "Porto Alegre", "Barretos", "São Paulo", "Santo André", "São José do Rio Preto", "Fortaleza"],
    patrocinador: 'Pfizer',
    fonte_url: 'https://clinicaltrials.gov/study/NCT06629779',
    contato_url: 'https://clinicaltrials.gov/study/NCT06629779',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct06952803',
    nome: 'AZD5305',
    titulo: 'A Study of Metastases Free Survival With Saruparib vs Placebo Added to a Standard RT/ADT in Men With High-risk Prostate Cancer With a BRCA Mutation',
    nct: 'NCT06952803',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'prostata',
    neoplasia_label: 'Próstata',
    subtipo: '',
    linha_terapeutica: 'Perioperatório',
    cenario_clinico: 'Perioperatório',
    modalidade: ["terapia-alvo"],
    biomarcadores: ["BRCA"],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Saruparib + Abiraterone + Prednisolone/Prednisone + Androgen Deprivation Therapy (ADT)',
    comparador: 'Placebo',
    racional: 'The purpose of the study is to demonstrate superiority of Saruparib (AZD5305) relative to placebo added to a standard radiation therapy (RT) + androgen deprivation therapy (ADT) regimen by assessment of metastases-free survival in participants with h',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Pelotas / RS", "Jaú / SP", "Curitiba / PR", "São Paulo / SP", "Salvador / BA", "Londrina", "Rio de Janeiro / RJ", "Cachoeiro de Itapemirim"],
    estados: ["BA", "PR", "RJ", "RS", "SP"],
    cidades: ["Pelotas", "Cachoeiro de Itapemirim", "Rio de Janeiro", "Curitiba", "Salvador", "Porto Alegre", "São Paulo", "Londrina", "Jaú"],
    patrocinador: 'AstraZeneca',
    fonte_url: 'https://clinicaltrials.gov/study/NCT06952803',
    contato_url: 'https://clinicaltrials.gov/study/NCT06952803',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct07028853',
    nome: 'PF-06821497',
    titulo: 'This Study Will Explore Whether a Combination of the Investigational Drug Mevrometostat (PF-06821497) and Enzalutamide Will Work Better Than Taking Enzalutamide Alone in Participants With mCSPC Who Ar',
    nct: 'NCT07028853',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'prostata',
    neoplasia_label: 'Próstata',
    subtipo: '',
    linha_terapeutica: 'Avançado / metastático',
    cenario_clinico: 'Avançado / metastático',
    modalidade: ["terapia-alvo"],
    biomarcadores: [],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Mevrometostat + Enzalutamide',
    comparador: 'Placebo',
    racional: 'This study will explore whether a combination of the investigational drug mevrometostat (PF-06821497) and enzalutamide will work better than taking enzalutamide alone in participants with mCSPC who are ARPI naïve and have not yet received chemotherap',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["São José do Rio Preto / SP", "Santo André / SP", "Sorocaba / SP", "Curitiba / PR", "São Paulo / SP", "Ijuí / RS", "Porto Alegre / RS", "Fortaleza / CE"],
    estados: ["CE", "PR", "RS", "SP"],
    cidades: ["Curitiba", "Porto Alegre", "Ijuí", "São Paulo", "Santo André", "São José do Rio Preto", "Fortaleza", "Sorocaba"],
    patrocinador: 'Pfizer',
    fonte_url: 'https://clinicaltrials.gov/study/NCT07028853',
    contato_url: 'https://clinicaltrials.gov/study/NCT07028853',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct06136624',
    nome: 'NHA',
    titulo: 'Study of Opevesostat (MK-5684) Versus Alternative NHA in mCRPC (MK-5684-003)',
    nct: 'NCT06136624',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'prostata',
    neoplasia_label: 'Próstata',
    subtipo: '',
    linha_terapeutica: 'Avançado / metastático',
    cenario_clinico: 'Avançado / metastático',
    modalidade: ["terapia-alvo"],
    biomarcadores: [],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Opevesostat + Abiraterone acetate + Enzalutamide + Hydrocortisone',
    comparador: 'Braço controle conforme protocolo',
    racional: 'This is a phase 3, randomized, open-label study of opevesostat compared to alternative abiraterone acetate or enzalutamide in participants with metastatic castration-resistant prostate cancer (mCRPC) with respect to overall survival (OS) in participa',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Belo Horizonte / MG", "Curitiba / PR", "Itajaí / PR", "São Paulo / SP", "Salvador / BA", "Vitória / ES", "Bragança Paulista"],
    estados: ["BA", "ES", "MG", "PR", "SP"],
    cidades: ["Vitória", "Curitiba", "Salvador", "São Paulo", "Bragança Paulista", "Belo Horizonte", "Itajaí"],
    patrocinador: 'Merck Sharp & Dohme LLC',
    fonte_url: 'https://clinicaltrials.gov/study/NCT06136624',
    contato_url: 'https://clinicaltrials.gov/study/NCT06136624',
    data_atualizacao: '2026-05-19',
  },

  // ============== RIM · CCRCC ==============
  {
    id: 'nct06170788',
    nome: 'TroFuse-007',
    titulo: 'Sacituzumab Tirumotecan (MK-2870) in Combination With Pembrolizumab Versus Pembrolizumab Alone in Metastatic Non-small Cell Lung Cancer (NSCLC) With Programmed Cell Death Ligand 1 (PD-L1) Tumor Propor',
    nct: 'NCT06170788',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'rim',
    neoplasia_label: 'Rim · ccRCC',
    subtipo: '',
    linha_terapeutica: '1ª linha',
    cenario_clinico: '1ª linha',
    modalidade: ["ADC", "combinação", "imunoterapia"],
    biomarcadores: ["EGFR", "PD-L1"],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Sacituzumab tirumotecan + Pembrolizumab + Supportive care measures',
    comparador: 'Braço controle conforme protocolo',
    racional: 'The primary objective of the study is to compare sacituzumab tirumotecan combined with pembrolizumab to pembrolizumab alone with respect to overall survival (OS). The primary hypothesis is that the combination of sacituzumab tirumotecan and pembroliz',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["São José do Rio Preto / SP", "Barretos / SP", "São Paulo / SP", "Rio de Janeiro / RJ", "Porto Alegre / RS", "Santa Maria"],
    estados: ["RJ", "RS", "SP"],
    cidades: ["Rio de Janeiro", "Porto Alegre", "Barretos", "São Paulo", "São José do Rio Preto", "Santa Maria"],
    patrocinador: 'Merck Sharp & Dohme LLC',
    fonte_url: 'https://clinicaltrials.gov/study/NCT06170788',
    contato_url: 'https://clinicaltrials.gov/study/NCT06170788',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct07227402',
    nome: 'LITESPARK-033',
    titulo: 'A Clinical Study of Belzutifan and Zanzalintinib in People With Recurrent Kidney Cancer Following Adjuvant Therapy (MK-6482-033)',
    nct: 'NCT07227402',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'rim',
    neoplasia_label: 'Rim · ccRCC',
    subtipo: '',
    linha_terapeutica: 'Perioperatório',
    cenario_clinico: 'Perioperatório',
    modalidade: ["terapia-alvo"],
    biomarcadores: [],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Belzutifan + Zanzalintinib + Cabozantinib',
    comparador: 'Braço controle conforme protocolo',
    racional: 'Researchers are looking for more ways to treat advanced renal cell carcinoma (RCC) that is recurrent. Researchers want to learn if recurrent advanced renal cell carcinoma (RCC) responds (gets smaller or goes away) after treatment with belzutifan (MK-',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["São José do Rio Preto / SP", "São Paulo / SP", "Natal / RN", "Cuiabá", "Porto Alegre / RS"],
    estados: ["RN", "RS", "SP"],
    cidades: ["Natal", "Cuiabá", "Porto Alegre", "São Paulo", "São José do Rio Preto"],
    patrocinador: 'Merck Sharp & Dohme LLC',
    fonte_url: 'https://clinicaltrials.gov/study/NCT07227402',
    contato_url: 'https://clinicaltrials.gov/study/NCT07227402',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct06469944',
    nome: 'MK-3475',
    titulo: 'Substudy 06C: A Study of Investigational Agents With Pembrolizumab (MK-3475) and Chemotherapy in Participants With First-Line Locally Advanced Unresectable/Metastatic Gastroesophageal Adenocarcinoma (',
    nct: 'NCT06469944',
    fase: 'Ib/II',
    status: 'Recrutando',
    neoplasia: 'rim',
    neoplasia_label: 'Rim · ccRCC',
    subtipo: '',
    linha_terapeutica: '1ª linha',
    cenario_clinico: '1ª linha',
    modalidade: ["ADC", "combinação", "imunoterapia", "quimioterapia"],
    biomarcadores: ["HER2"],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Pembrolizumab + Sacituzumab Tirumotecan (sac-TMT) + Capecitabine + Leucovorin',
    comparador: 'Braço controle conforme protocolo',
    racional: 'This is a phase 1/2, multicenter, open-label umbrella platform study that will evaluate the safety and tolerability of investigational agents with pembrolizumab and fluoropyrimidine chemotherapy for the first-line (1L) treatment of participants with',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Porto Alegre / RS", "São Paulo / SP", "Natal / RN"],
    estados: ["RN", "RS", "SP"],
    cidades: ["Porto Alegre", "São Paulo", "Natal"],
    patrocinador: 'Merck Sharp & Dohme LLC',
    fonte_url: 'https://clinicaltrials.gov/study/NCT06469944',
    contato_url: 'https://clinicaltrials.gov/study/NCT06469944',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct07293351',
    nome: 'RCC',
    titulo: 'A Study to Evaluate the Safety, Tolerability, and Efficacy of Pumitamig Alone or in Combination With Ipilimumab or Cabozantinib in Participants With Advanced Renal Cell Carcinoma (RCC) (ROSETTA RCC-20',
    nct: 'NCT07293351',
    fase: 'Ib/II',
    status: 'Recrutando',
    neoplasia: 'rim',
    neoplasia_label: 'Rim · ccRCC',
    subtipo: '',
    linha_terapeutica: 'Avançado / metastático',
    cenario_clinico: 'Avançado / metastático',
    modalidade: ["bispecífico", "combinação", "imunoterapia", "terapia-alvo"],
    biomarcadores: [],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Pumitamig + Ipilimumab + Cabozantinib + Nivolumab',
    comparador: 'Braço controle conforme protocolo',
    racional: 'The purpose of this study is to evaluate the safety, tolerability, and efficacy of Pumitamig alone or in combination with Ipilimumab or Cabozantinib in participants with advanced Renal Cell Carcinoma (RCC)',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Brasília / DF"],
    estados: ["DF"],
    cidades: ["Brasília"],
    patrocinador: 'Bristol-Myers Squibb',
    fonte_url: 'https://clinicaltrials.gov/study/NCT07293351',
    contato_url: 'https://clinicaltrials.gov/study/NCT07293351',
    data_atualizacao: '2026-05-19',
  },

  // ============== BEXIGA / UROTELIAL ==============
  {
    id: 'nct07218380',
    nome: 'NCT07218380',
    titulo: 'A Study of Vepugratinib (LY3866288) in Participants With Cancer in the Urinary Tract',
    nct: 'NCT07218380',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'urotelial',
    neoplasia_label: 'Bexiga / Urotelial',
    subtipo: '',
    linha_terapeutica: 'Avançado / metastático',
    cenario_clinico: 'Avançado / metastático',
    modalidade: ["combinação", "imunoterapia", "terapia-alvo"],
    biomarcadores: ["FGFR"],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Vepugratinib + EV + Pembrolizumab',
    comparador: 'Placebo',
    racional: 'The purpose of this study is to test a new medicine, vepugratinib, in comparison with placebo, to see if it is safe and can help people with a bladder cancer that is advanced or has spread. Vepugratinib or placebo will be administered in combination',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Barretos / SP", "Belo Horizonte / MG", "Belém / PA", "Bento Gonçalves", "Curitiba / PR", "São Paulo / SP", "Natal / RN", "Londrina"],
    estados: ["BA", "MG", "PA", "PR", "RJ", "RN", "RS", "SP"],
    cidades: ["Bento Gonçalves", "Santa Cruz do Sul", "Natal", "Rio de Janeiro", "Belém", "Curitiba", "Salvador", "Porto Alegre", "Barretos", "São Paulo", "São Caetano do Sul", "Londrina", "João Pessoa", "Belo Horizonte"],
    patrocinador: 'Eli Lilly and Company',
    fonte_url: 'https://clinicaltrials.gov/study/NCT07218380',
    contato_url: 'https://clinicaltrials.gov/study/NCT07218380',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct06319820',
    nome: 'IR-NMIBC',
    titulo: 'A Study to Evaluate TAR-210 Versus Single Agent Intravesical Cancer Treatment in Participants With Bladder Cancer',
    nct: 'NCT06319820',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'urotelial',
    neoplasia_label: 'Bexiga / Urotelial',
    subtipo: '',
    linha_terapeutica: 'Avançado / metastático',
    cenario_clinico: 'Avançado / metastático',
    modalidade: ["quimioterapia"],
    biomarcadores: ["FGFR"],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'TAR-210 + Gemcitabine + MMC',
    comparador: 'Braço controle conforme protocolo',
    racional: 'The main purpose of this study is to compare the disease-free survival between participants receiving treatment with TAR-210 versus investigator\'s choice of intravesical chemotherapy for treatment of intermediate-risk NMIBC.',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Barretos / SP", "Santo André / SP", "São Paulo / SP", "Natal / RN", "Salvador / BA", "Campinas / SP", "Porto Alegre / RS"],
    estados: ["BA", "RN", "RS", "SP"],
    cidades: ["Campinas", "Natal", "Salvador", "Porto Alegre", "Barretos", "São Paulo", "Santo André"],
    patrocinador: 'Janssen Research & Development, LLC',
    fonte_url: 'https://clinicaltrials.gov/study/NCT06319820',
    contato_url: 'https://clinicaltrials.gov/study/NCT06319820',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct06919965',
    nome: 'BCG',
    titulo: 'A Study to Evaluate TAR-210 Versus Intravesical Chemotherapy Treatment in Participants With High Risk Non-Muscle-Invasive Bladder Cancer',
    nct: 'NCT06919965',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'urotelial',
    neoplasia_label: 'Bexiga / Urotelial',
    subtipo: '',
    linha_terapeutica: 'Avançado / metastático',
    cenario_clinico: 'Avançado / metastático',
    modalidade: ["quimioterapia"],
    biomarcadores: ["FGFR"],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'TAR-210 + Mitomycin C + Gemcitabine',
    comparador: 'Braço controle conforme protocolo',
    racional: 'The main purpose of this study is to compare the disease-free survival (the length of time after randomization that a participant survives without any signs or symptoms of the cancer returning, or progressing) between Bacillus Calmette-Guérin (BCG) t',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["São José do Rio Preto / SP", "São Paulo / SP", "Presidente Prudente / SP", "Natal / RN"],
    estados: ["RN", "SP"],
    cidades: ["São Paulo", "São José do Rio Preto", "Presidente Prudente", "Natal"],
    patrocinador: 'Janssen Research & Development, LLC',
    fonte_url: 'https://clinicaltrials.gov/study/NCT06919965',
    contato_url: 'https://clinicaltrials.gov/study/NCT06919965',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct07419295',
    nome: 'MK-2870',
    titulo: 'A Clinical Trial of Sacituzumab Tirumotecan (Sac-TMT, MK-2870) to Treat Urothelial Cancer (MK-2870-031)',
    nct: 'NCT07419295',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'urotelial',
    neoplasia_label: 'Bexiga / Urotelial',
    subtipo: '',
    linha_terapeutica: 'Avançado / metastático',
    cenario_clinico: 'Avançado / metastático',
    modalidade: ["ADC", "combinação", "quimioterapia"],
    biomarcadores: [],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Sacituzumab tirumotecan + Vinflunine + Docetaxel + Paclitaxel',
    comparador: 'Braço controle conforme protocolo',
    racional: 'Researchers are looking for new ways to treat locally advanced or metastatic urothelial cancer (UC). Current treatments for locally advanced or metastatic UC include chemotherapy, immunotherapy, and targeted therapy. Researchers want to know if givi',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["São José do Rio Preto / SP"],
    estados: ["SP"],
    cidades: ["São José do Rio Preto"],
    patrocinador: 'Merck Sharp & Dohme LLC',
    fonte_url: 'https://clinicaltrials.gov/study/NCT07419295',
    contato_url: 'https://clinicaltrials.gov/study/NCT07419295',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct06534983',
    nome: 'NCT06534983',
    titulo: 'A Study to Evaluate the Efficacy and Safety of Autogene Cevumeran With Nivolumab Versus Nivolumab Alone in Participants With High-risk Muscle-invasive Urothelial Carcinoma (MIUC)',
    nct: 'NCT06534983',
    fase: 'II',
    status: 'Recrutando',
    neoplasia: 'urotelial',
    neoplasia_label: 'Bexiga / Urotelial',
    subtipo: '',
    linha_terapeutica: 'Perioperatório',
    cenario_clinico: 'Perioperatório',
    modalidade: ["imunoterapia"],
    biomarcadores: [],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Autogene Cevumeran + Nivolumab + Saline',
    comparador: 'Braço controle conforme protocolo',
    racional: 'The main purpose of the study is to evaluate the efficacy of adjuvant treatment with autogene cevumeran plus nivolumab compared with nivolumab in participants with high risk MIUC. In this study participants will be enrolled in a safety run-in phase',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Porto Alegre / RS"],
    estados: ["RS"],
    cidades: ["Porto Alegre"],
    patrocinador: 'Hoffmann-La Roche',
    fonte_url: 'https://clinicaltrials.gov/study/NCT06534983',
    contato_url: 'https://clinicaltrials.gov/study/NCT06534983',
    data_atualizacao: '2026-05-19',
  },