
  // ============== CÉRVIX ==============
  {
    id: 'nct06525220',
    nome: 'NCT06525220',
    titulo: 'A Phase 3 Study to Evaluate Petosemtamab Plus Pembrolizumab vs Pembrolizumab in First-line Treatment of Head and Neck Cancer (LiGeR - HN1)',
    nct: 'NCT06525220',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'cervix',
    neoplasia_label: 'Cérvix',
    subtipo: '',
    linha_terapeutica: '1ª linha',
    cenario_clinico: '1ª linha',
    modalidade: ["bispecífico", "combinação", "imunoterapia"],
    biomarcadores: ["PD-L1"],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Petosemtamab + Pembrolizumab',
    comparador: 'Braço controle conforme protocolo',
    racional: 'This is a Phase 3 randomized, open-label study to evaluate the efficacy and safety of petosemtamab plus pembrolizumab vs pembrolizumab in first-line treatment of recurrent or metastatic PD-L1+ head and neck squamous cell carcinoma.',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Site 141 · Belo Horizonte", "Site 144 · Natal", "Site 140 · Porto Alegre", "Site 142 · Porto Alegre", "Site 137 · Recife"],
    estados: [],
    cidades: ["Recife", "Belo Horizonte", "Natal", "Porto Alegre", "Rio de Janeiro", "São Paulo"],
    patrocinador: 'Merus B.V.',
    fonte_url: 'https://clinicaltrials.gov/study/NCT06525220',
    contato_url: 'https://clinicaltrials.gov/study/NCT06525220',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct07276399',
    nome: 'NCT07276399',
    titulo: 'A Study of Amivantamab in Addition to Standard of Care Agents (SOC) Compared With SOC Alone in Participants With Recurrent/Metastatic Head and Neck Cancer',
    nct: 'NCT07276399',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'cervix',
    neoplasia_label: 'Cérvix',
    subtipo: '',
    linha_terapeutica: '1ª linha',
    cenario_clinico: '1ª linha',
    modalidade: ["bispecífico", "combinação", "imunoterapia", "quimioterapia"],
    biomarcadores: [],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Amivantamab + Pembrolizumab + Carboplatin + 5-Flurouracil + Cisplatin',
    comparador: 'Braço controle conforme protocolo',
    racional: 'The purpose of this study is to compare anti-tumor activity of amivantamab in addition to pembrolizumab and carboplatin versus pembrolizumab, 5-fluorouracil (FU), and platinum therapy (carboplatin or cisplatin) in participants with refractory/metasta...',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Fundacao Doutor Amaral Carvalho · Jaú", "Liga Norte Riograndense Contra O Cancer · Natal", "Irmandade da Santa Casa de Misericordia de Porto Alegre · Porto Alegre", "Fundacao Faculdade Regional de Medicina de Sao Jose Do Rio Preto - Centro Integrado de Pesquisa · São José do Rio Preto", "Hospital Alemao Oswaldo Cruz · São Paulo"],
    estados: [],
    cidades: ["São José do Rio Preto", "Natal", "Jaú", "Vitória", "Porto Alegre", "São Paulo"],
    patrocinador: 'Janssen Research & Development, LLC',
    fonte_url: 'https://clinicaltrials.gov/study/NCT07276399',
    contato_url: 'https://clinicaltrials.gov/study/NCT07276399',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct07216703',
    nome: 'MK-2870',
    titulo: 'A Clinical Study of Sacituzumab Tirumotecan (MK-2870) in Combination With Pembrolizumab (MK-3475) as First-line Maintenance Treatment of Cervical Cancer (MK-2870-036/TroFuse-036/GOG-3123/ENGOT-cx22)',
    nct: 'NCT07216703',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'cervix',
    neoplasia_label: 'Cérvix',
    subtipo: '',
    linha_terapeutica: '1ª linha',
    cenario_clinico: '1ª linha',
    modalidade: ["ADC", "anti-angiogênico", "combinação", "imunoterapia", "quimioterapia"],
    biomarcadores: ["PD-L1"],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Pembrolizumab + Sacituzumab Tirumotecan + Bevacizumab + Paclitaxel + Cisplatin + Carboplatin + Rescue Medications',
    comparador: 'Braço controle conforme protocolo',
    racional: 'Researchers are looking for new ways to treat metastatic cervical cancer. Cervical cancer is cancer in the cervix, the lower part of the uterus (womb). Metastatic means the cancer has spread to other parts of the body.

Researchers want to learn abou...',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Liga Norte Riograndense Contra o Câncer ( Site 0513) · Natal/Rio Grande do Norte", "Irmandade da Santa Casa de Misericordia de Porto Alegre ( Site 0514) · Porto Alegre/Rio Grande do Sul", "Hospital São Lucas da PUCRS ( Site 0516) · Porto Alegre/Rio Grande do Sul", "Fundação Pio XII - Hospital de Câncer de Barretos ( Site 0511) · Barretos/São Paulo", "Fundacao Faculdade Regional de Medicina de Sao Jose do Rio Preto ( Site 0512) · São José do Rio Preto/São Paulo"],
    estados: ["Rio Grande do Sul", "Rio Grande do Norte", "São Paulo"],
    cidades: ["São José do Rio Preto", "Natal", "Barretos", "Porto Alegre", "São Paulo"],
    patrocinador: 'Merck Sharp & Dohme LLC',
    fonte_url: 'https://clinicaltrials.gov/study/NCT07216703',
    contato_url: 'https://clinicaltrials.gov/study/NCT07216703',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct06459180',
    nome: 'NCT06459180',
    titulo: 'A Study to Compare Sacituzumab Tirumotecan (MK-2870) Monotherapy Versus Treatment of Physician\'s Choice as Second-line Treatment for Participants With Recurrent or Metastatic Cervical Cancer (MK-28...',
    nct: 'NCT06459180',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'cervix',
    neoplasia_label: 'Cérvix',
    subtipo: '',
    linha_terapeutica: '2ª linha',
    cenario_clinico: '2ª linha',
    modalidade: ["ADC", "combinação", "imunoterapia", "quimioterapia"],
    biomarcadores: ["PD-L1"],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Sacituzumab Tirumotecan + Pemetrexed + Tisotumab Vedotin + Topotecan + Vinorelbine + Gemcitabine + Irinotecan',
    comparador: 'Braço controle conforme protocolo',
    racional: 'This study will have two phases: a sacituzumab tirumotecan safety run-in and a Phase 3 portion. The safety run-in phase will be used to evaluate the efficacy and safety of sacituzumab tirumotecan at the dose for evaluation in the Phase 3 portion. The...',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Instituto do Câncer e Transplante de Curitiba ( Site 0205) · Curitiba/Paraná", "Hospital Moinhos de Vento-Centro de Pesquisa Clínica ( Site 0204) · Porto Alegre/Rio Grande do Sul", "Hospital do Câncer Mãe de Deus ( Site 0201) · Porto Alegre/Rio Grande do Sul", "Centro de Hematologia e Oncologia ( Site 0203) · Joinville/Santa Catarina", "IBCC - Instituto Brasileiro de Controle do Câncer-Centro de Pesquisa Clínica ( Site 0200) · São Paulo/São Paulo"],
    estados: ["Santa Catarina", "Paraná", "São Paulo", "Rio Grande do Sul"],
    cidades: ["Curitiba", "Joinville", "Porto Alegre", "Rio de Janeiro", "São Paulo"],
    patrocinador: 'Merck Sharp & Dohme LLC',
    fonte_url: 'https://clinicaltrials.gov/study/NCT06459180',
    contato_url: 'https://clinicaltrials.gov/study/NCT06459180',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct04379596',
    nome: 'T-DXd',
    titulo: 'Ph1b/2 Study of the Safety and Efficacy of T-DXd Combinations in Advanced HER2-expressing Gastric Cancer (DESTINY-Gastric03)',
    nct: 'NCT04379596',
    fase: 'II',
    status: 'Recrutando',
    neoplasia: 'cervix',
    neoplasia_label: 'Cérvix',
    subtipo: '',
    linha_terapeutica: 'Avançado / metastático',
    cenario_clinico: 'Avançado / metastático',
    modalidade: ["ADC", "combinação", "imunoterapia", "quimioterapia"],
    biomarcadores: ["HER2"],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Fluorouracil (5-FU) + Capecitabine + Durvalumab + Oxaliplatin + Trastuzumab + Trastuzumab deruxtecan + Cisplatin + Pembrolizumab + Volrustomig + Rilvegostomig',
    comparador: 'Braço controle conforme protocolo',
    racional: 'DESTINY-Gastric03 will investigate the safety, tolerability, pharmacokinetics, immunogenicity, and preliminary antitumor activity of trastuzumab deruxtecan (T-DXd) alone or in combination with chemotherapy and/or immunotherapy in HER2-expressing adva...',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Research Site · Florianópolis", "Research Site · Londrina", "Research Site · Natal", "Research Site · Porto Alegre", "Research Site · Ribeirão Preto"],
    estados: [],
    cidades: ["Londrina", "São Jose Do Rio Preto", "Ribeirão Preto", "Natal", "Florianópolis", "Santa Maria", "Porto Alegre", "Rio de Janeiro", "São Paulo"],
    patrocinador: 'AstraZeneca',
    fonte_url: 'https://clinicaltrials.gov/study/NCT04379596',
    contato_url: 'https://clinicaltrials.gov/study/NCT04379596',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct04291105',
    nome: 'NCT04291105',
    titulo: 'Phase 2 Trial of Voyager V1 in Combination With Cemiplimab in Cancer Patients',
    nct: 'NCT04291105',
    fase: 'II',
    status: 'Recrutando',
    neoplasia: 'cervix',
    neoplasia_label: 'Cérvix',
    subtipo: '',
    linha_terapeutica: '1ª linha',
    cenario_clinico: '1ª linha',
    modalidade: ["imunoterapia"],
    biomarcadores: ["PD-L1"],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'VV1 + Cemiplimab',
    comparador: 'Braço controle conforme protocolo',
    racional: 'This is a Phase 2 study designed to determine the preliminary anti-tumor activity and confirm the safety of VV1 in combination with cemiplimab. The study will enroll patients with three distinct separate tumor cohorts. The cancers types are colorecta...',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Hospital Sao Rafael · Salvador/BR", "INCA · Rio de Janeiro/Rio de Janeiro", "Hospital Moinhos de Vento · Porto Alegre/Rio Grande do Sul", "Hospital de Amor de Barretos · Barretos/São Paulo"],
    estados: ["Rio Grande do Sul", "São Paulo", "Rio de Janeiro", "BR"],
    cidades: ["Barretos", "Porto Alegre", "Rio de Janeiro", "Salvador"],
    patrocinador: 'Vyriad, Inc.',
    fonte_url: 'https://clinicaltrials.gov/study/NCT04291105',
    contato_url: 'https://clinicaltrials.gov/study/NCT04291105',
    data_atualizacao: '2026-05-19',
  },

  // ============== ENDOMÉTRIO ==============
  {
    id: 'nct06989112',
    nome: 'T-DXd',
    titulo: 'DESTINY-Endometrial01: A Phase III Study of Trastuzumab Deruxtecan Plus Rilvegostomig or Pembrolizumab as First-Line Treatment of HER2-Expressing (IHC 3+/2+), Mismatch Repair Proficient (pMMR) Endo...',
    nct: 'NCT06989112',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'endometrio',
    neoplasia_label: 'Endométrio',
    subtipo: '',
    linha_terapeutica: '1ª linha',
    cenario_clinico: '1ª linha',
    modalidade: ["ADC", "combinação", "imunoterapia", "quimioterapia"],
    biomarcadores: ["HER2", "dMMR"],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Trastuzumab deruxtecan + Rilvegostomig + Pembrolizumab + Carboplatin + Paclitaxel + Docetaxel',
    comparador: 'Braço controle conforme protocolo',
    racional: 'DESTINY-Endometrial01 will investigate the efficacy of first-line T-DXd + rilvegostomig (Arm A) and/or T-DXd+ pembrolizumab (Arm B) when compared to chemotherapy (carboplatin + paclitaxel) + pembrolizumab (Arm C), by assessment of progression free su...',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Research Site · Barretos", "Research Site · Belo Horizonte", "Research Site · Goiânia", "Research Site · Londrina", "Research Site · Porto Alegre"],
    estados: [],
    cidades: ["Londrina", "Teresina", "Belo Horizonte", "Goiânia", "Barretos", "Porto Alegre", "Rio de Janeiro", "Salvador", "São Paulo"],
    patrocinador: 'AstraZeneca',
    fonte_url: 'https://clinicaltrials.gov/study/NCT06989112',
    contato_url: 'https://clinicaltrials.gov/study/NCT06989112',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct06952504',
    nome: 'NCT06952504',
    titulo: 'A Study to Compare Sacituzumab Tirumotecan (MK-2870) in Combination With Pembrolizumab (MK-3475) Versus Pembrolizumab Alone as Treatment in Participants With Mismatch Repair Proficient Endometrial ...',
    nct: 'NCT06952504',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'endometrio',
    neoplasia_label: 'Endométrio',
    subtipo: '',
    linha_terapeutica: '1ª linha',
    cenario_clinico: '1ª linha',
    modalidade: ["ADC", "combinação", "imunoterapia", "quimioterapia"],
    biomarcadores: ["dMMR"],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Pembrolizumab + Carboplatin + Paclitaxel + Docetaxel + Sacituzumab Tirumotecan',
    comparador: 'Braço controle conforme protocolo',
    racional: 'Researchers are looking for new ways to treat people with proficient mismatch repair (pMMR) endometrial cancer (EC) that is advanced or recurrent.

* EC is a type of cancer that starts in the tissues inside the uterus (womb)
* pMMR indicates that cer...',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Hospital Araújo Jorge ( Site 0521) · Goiânia/Goiás", "Liga Norte Riograndense Contra o Câncer ( Site 0523) · Natal/Rio Grande do Norte", "Hospital São Lucas da PUCRS ( Site 0522) · Porto Alegre/Rio Grande do Sul", "IBCC - Instituto Brasileiro de Controle do Câncer ( Site 0525) · São Paulo/São Paulo", "Instituto Nacional de Câncer - INCA ( Site 0515) · Rio de Janeiro"],
    estados: ["Rio Grande do Sul", "Rio Grande do Norte", "Goiás", "São Paulo"],
    cidades: ["Goiânia", "Natal", "Porto Alegre", "Rio de Janeiro", "São Paulo"],
    patrocinador: 'Merck Sharp & Dohme LLC',
    fonte_url: 'https://clinicaltrials.gov/study/NCT06952504',
    contato_url: 'https://clinicaltrials.gov/study/NCT06952504',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct06796907',
    nome: 'NCT06796907',
    titulo: 'A Study of GSK5733584 in Combination With Anti-cancer Therapies for Advanced Solid Tumors',
    nct: 'NCT06796907',
    fase: 'Ib/II',
    status: 'Recrutando',
    neoplasia: 'endometrio',
    neoplasia_label: 'Endométrio',
    subtipo: '',
    linha_terapeutica: 'Avançado / metastático',
    cenario_clinico: 'Avançado / metastático',
    modalidade: ["anti-angiogênico", "combinação", "imunoterapia"],
    biomarcadores: [],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'GSK5733584 + Dostarlimab + Bevacizumab + Anticancer therapy 3 + Anticancer therapy 4',
    comparador: 'Braço controle conforme protocolo',
    racional: 'Advanced solid tumors are cancers that have spread to other parts of the body. While many treatments exist, most people become resistant to them, and the cancer returns. Researchers are developing new treatments that combine different medicines for t...',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["GSK Investigational Site · Natal", "GSK Investigational Site · Porto Alegre", "GSK Investigational Site · São Paulo", "GSK Investigational Site · Vitória"],
    estados: [],
    cidades: ["São Paulo", "Vitória", "Porto Alegre", "Natal"],
    patrocinador: 'GlaxoSmithKline',
    fonte_url: 'https://clinicaltrials.gov/study/NCT06796907',
    contato_url: 'https://clinicaltrials.gov/study/NCT06796907',
    data_atualizacao: '2026-05-19',
  },

  // ============== HEPATOCARCINOMA · CHC ==============
  {
    id: 'nct06921785',
    nome: 'NCT06921785',
    titulo: 'Phase III Study of Rilvegostomig in Combination With Bevacizumab With or Without Tremelimumab as First-line Treatment of Hepatocellular Carcinoma',
    nct: 'NCT06921785',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'hcc',
    neoplasia_label: 'Hepatocarcinoma · CHC',
    subtipo: '',
    linha_terapeutica: '1ª linha',
    cenario_clinico: '1ª linha',
    modalidade: ["anti-angiogênico", "combinação", "imunoterapia"],
    biomarcadores: [],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Tremelimumab + Rilvegostomig + Bevacizumab + Atezolizumab',
    comparador: 'Braço controle conforme protocolo',
    racional: 'This is a Phase III, randomised, open-label, sponsor-blinded, 3-arm, multicentre, global study assessing the efficacy and safety of rilvegostomig in combination with bevacizumab with or without tremelimumab compared to atezolizumab in combination wit...',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Research Site · Barretos", "Research Site · Porto Alegre", "Research Site · Santa Maria", "Research Site · São Paulo", "Research Site · Vitória"],
    estados: [],
    cidades: ["Barretos", "Santa Maria", "Vitória", "Porto Alegre", "São Paulo"],
    patrocinador: 'AstraZeneca',
    fonte_url: 'https://clinicaltrials.gov/study/NCT06921785',
    contato_url: 'https://clinicaltrials.gov/study/NCT06921785',
    data_atualizacao: '2026-05-19',
  },

  // ============== LINFOMA ==============
  {
    id: 'nct06191744',
    nome: 'R2',
    titulo: 'Study of Subcutaneous Epcoritamab in Combination With Intravenous Rituximab and Oral Lenalidomide (R2) to Assess Adverse Events and Change in Disease Activity in Adult Participants With Previously ...',
    nct: 'NCT06191744',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'linfoma',
    neoplasia_label: 'Linfoma',
    subtipo: '',
    linha_terapeutica: '1ª linha',
    cenario_clinico: '1ª linha',
    modalidade: ["bispecífico", "combinação", "quimioterapia"],
    biomarcadores: ["CD20"],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Epcoritamab + Prednisone + Rituximab + Lenalidomide + Doxorubicin + Vincristine + Cyclophosphamide + Obinutuzumab + Bendamustine',
    comparador: 'Braço controle conforme protocolo',
    racional: 'Follicular lymphoma (FL) is the second most common B-cell cancer and the most common type of cancer of lymphocytes. Unfortunately, this disease is incurable with conventional treatment and the disease recurs in almost all patients. This study will as...',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["DF Star /ID# 260844 · Brasília/Federal District", "Oncocentro de Minas Gerais /ID# 260973 · Belo Horizonte/Minas Gerais", "Hospital Erasto Gaertner /ID# 260871 · Curitiba/Puerto Rico", "Hospital Amaral Carvalho - Fundacao Doutor Amaral Carvalho /ID# 260828 · Jaú/São Paulo", "Hospital das Clinicas da Faculdade de Medicina de Ribeirao Preto /ID# 260843 · Ribeirão Preto/São Paulo"],
    estados: ["Puerto Rico", "Federal District", "São Paulo", "Minas Gerais"],
    cidades: ["Brasília", "Curitiba", "Ribeirão Preto", "Belo Horizonte", "Jaú", "Rio de Janeiro", "São Paulo"],
    patrocinador: 'Genmab',
    fonte_url: 'https://clinicaltrials.gov/study/NCT06191744',
    contato_url: 'https://clinicaltrials.gov/study/NCT06191744',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct06084936',
    nome: 'NCT06084936',
    titulo: 'A Study to Evaluate Glofitamab as a Single Agent vs. Investigator\'s Choice in Participants With Relapsed/Refractory Mantle Cell Lymphoma',
    nct: 'NCT06084936',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'linfoma',
    neoplasia_label: 'Linfoma',
    subtipo: '',
    linha_terapeutica: 'Recidivado / refratário',
    cenario_clinico: 'Recidivado / refratário',
    modalidade: ["bispecífico", "combinação", "quimioterapia"],
    biomarcadores: [],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Obinutuzumab + Glofitamab + Rituximab + Bendamustine + Lenalidomide + Tocilizumab',
    comparador: 'Braço controle conforme protocolo',
    racional: 'The purpose of this study is to evaluate the efficacy of glofitamab monotherapy compared with an investigator\'s choice of either rituximab plus bendamustine (BR), or lenalidomide with rituximab (R-Len) in patients with relapsed or refractory (R/R) ma...',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Hospital Sao Rafael - HSR · Salvador/Estado de Bahia", "ICTR Curitiba · Curitiba/Paraná", "Hospital Mae de Deus · Porto Alegre/Rio Grande do Sul", "Hospital Paulistano · São Paulo/São Paulo", "Hospital Alemao Oswaldo Cruz · São Paulo/São Paulo"],
    estados: ["Rio Grande do Sul", "Paraná", "São Paulo", "Estado de Bahia"],
    cidades: ["Curitiba", "Porto Alegre", "Rio de Janeiro", "Salvador", "São Paulo"],
    patrocinador: 'Hoffmann-La Roche',
    fonte_url: 'https://clinicaltrials.gov/study/NCT06084936',
    contato_url: 'https://clinicaltrials.gov/study/NCT06084936',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct06634589',
    nome: 'NCT06634589',
    titulo: 'A Study to Investigate Safety and Effectiveness of BGB-16673 in Combination With Other Agents in Participants With Relapsed or Refractory B-Cell Malignancies',
    nct: 'NCT06634589',
    fase: 'Ib/II',
    status: 'Recrutando',
    neoplasia: 'linfoma',
    neoplasia_label: 'Linfoma',
    subtipo: '',
    linha_terapeutica: 'Recidivado / refratário',
    cenario_clinico: 'Recidivado / refratário',
    modalidade: ["bispecífico"],
    biomarcadores: [],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'BGB-16673 + Sonrotoclax + Zanubrutinib + Mosunetuzumab + Glofitamab + Obinutuzumab',
    comparador: 'Braço controle conforme protocolo',
    racional: 'The purpose of this study is to measure the safety, preliminary antitumor activity, pharmacokinetics, and pharmacodynamics with BGB-16673 in combination with other agents in participants with relapsed or refractory (R/R) B-cell malignancies. This stu...',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Hospital Sirio Libanes Brasilia · Brasília", "Ensino E Terapia de Inovacao Clinica Amo Etica · Salvador", "Fundacao Faculdade Regional de Medicina de Sao Jose Do Rio Preto · São José do Rio Preto", "Sociedade Beneficente Israelita Brasileira Hospital Albert Einstein · São Paulo"],
    estados: [],
    cidades: ["São José do Rio Preto", "Brasília", "São Paulo", "Salvador"],
    patrocinador: 'BeOne Medicines',
    fonte_url: 'https://clinicaltrials.gov/study/NCT06634589',
    contato_url: 'https://clinicaltrials.gov/study/NCT06634589',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct05533775',
    nome: 'NCT05533775',
    titulo: 'A Study to Evaluate Glofitamab Monotherapy and Glofitamab + Chemoimmunotherapy in Pediatric and Young Adult Participants With Relapsed/Refractory Mature B-Cell Non-Hodgkin Lymphoma',
    nct: 'NCT05533775',
    fase: 'Ib/II',
    status: 'Recrutando',
    neoplasia: 'linfoma',
    neoplasia_label: 'Linfoma',
    subtipo: '',
    linha_terapeutica: 'Recidivado / refratário',
    cenario_clinico: 'Recidivado / refratário',
    modalidade: ["bispecífico", "combinação", "quimioterapia"],
    biomarcadores: ["CD20"],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Obinutuzumab + Glofitamab + Rituximab + Ifosfamide + Carboplatin + Etoposide + Tocilizumab',
    comparador: 'Braço controle conforme protocolo',
    racional: 'The purpose of this study is to evaluate the safety and efficacy of glofitamab, as monotherapy and in combination with a standard chemoimmunotherapy regimen: rituximab, ifosfamide, carboplatin, and etoposide (R-ICE) in pediatric and young adult parti...',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Hospital Erasto Gaertner · Curitiba/Paraná", "Graacc-Grupo de Apoio ao adolescente e a crianca com cancer · São Paulo/São Paulo"],
    estados: ["Paraná", "São Paulo"],
    cidades: ["Curitiba", "São Paulo"],
    patrocinador: 'Hoffmann-La Roche',
    fonte_url: 'https://clinicaltrials.gov/study/NCT05533775',
    contato_url: 'https://clinicaltrials.gov/study/NCT05533775',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct05660395',
    nome: 'LOTIS-10',
    titulo: 'A Study to Evaluate the Pharmacokinetics and Safety of Loncastuximab Tesirine in Participants With Relapsed or Refractory Diffuse Large B-cell Lymphoma or High-grade B-cell Lymphoma With Hepatic Im...',
    nct: 'NCT05660395',
    fase: 'I',
    status: 'Recrutando',
    neoplasia: 'linfoma',
    neoplasia_label: 'Linfoma',
    subtipo: '',
    linha_terapeutica: 'Recidivado / refratário',
    cenario_clinico: 'Recidivado / refratário',
    modalidade: ["ADC"],
    biomarcadores: [],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Loncastuximab Tesirine',
    comparador: 'Braço controle conforme protocolo',
    racional: 'The primary objective of this study is to determine the recommended dosing regimen of loncastuximab tesirine in diffuse large B-cell lymphoma (DLBCL) or high-grade B-cell lymphoma (HGBCL) participants with moderate and severe hepatic impairment.',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Hospital Sírio-Libanês - Brasília · Brasília", "Hospital Mãe de Deus - Centro Integrado de Oncologia · Porto Alegre", "Hospital Sírio-Libanês - São Paulo · São Paulo", "A Beneficência Portuguesa de São Paulo - Unidade Mirant · São Paulo", "Hospital 9 de Julho · São Paulo"],
    estados: [],
    cidades: ["Porto Alegre", "São Paulo", "Brasília"],
    patrocinador: 'ADC Therapeutics S.A.',
    fonte_url: 'https://clinicaltrials.gov/study/NCT05660395',
    contato_url: 'https://clinicaltrials.gov/study/NCT05660395',
    data_atualizacao: '2026-05-19',
  },

  // ============== MAMA ==============
  {
    id: 'nct05950945',
    nome: 'T-DXd',
    titulo: 'Trastuzumab Deruxtecan (T-DXd) in Patients Who Have Hormone Receptor-negative and Hormone Receptor-positive HER2-low or HER2 IHC 0 Metastatic Breast Cancer',
    nct: 'NCT05950945',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'mama',
    neoplasia_label: 'Mama',
    subtipo: '',
    linha_terapeutica: 'Avançado / metastático',
    cenario_clinico: 'Avançado / metastático',
    modalidade: ["ADC"],
    biomarcadores: ["HER2", "HR+", "HR-"],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Trastuzumab Deruxtecan',
    comparador: 'Braço controle conforme protocolo',
    racional: 'This study will evaluate the safety and efficacy of trastuzumab deruxtecan (T-DXd) in participants with human epidermal growth factor receptor 2 (HER2)-low or HER2 immunohistochemistry (IHC) 0 (who are both hormone receptor \[HR\]-negative and HR-pos...',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Centro de Oncologia - Unidade Brasília - Hospital Sírio Libanês · Brasília", "CIONC-Centro Integrado de Oncologia de Curitiba · Curitiba", "Hospital Erasto Gaertner - Liga Paranaense de Combate ao Câncer · Curitiba", "CEPON - Centro de Pesquisas Oncológicas de Santa Catarina · Florianópolis", "Oncosite - Centro de Pesquisa Clinica e Oncologia · Ijuí"],
    estados: [],
    cidades: ["São José do Rio Preto", "Londrina", "Brasília", "Rio Grande", "Curitiba", "Santa Catarina", "Santo André", "Jaú", "Riberão Preto", "Ijuí", "Florianópolis", "Salvador", "São Paulo"],
    patrocinador: 'Daiichi Sankyo',
    fonte_url: 'https://clinicaltrials.gov/study/NCT05950945',
    contato_url: 'https://clinicaltrials.gov/study/NCT05950945',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct06966700',
    nome: 'NCT06966700',
    titulo: 'A Clinical Study of Sacituzumab Tirumotecan (Sac-TMT, MK-2870) in People With Breast Cancer (MK-2870-032)',
    nct: 'NCT06966700',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'mama',
    neoplasia_label: 'Mama',
    subtipo: '',
    linha_terapeutica: '1ª linha',
    cenario_clinico: '1ª linha',
    modalidade: ["ADC", "combinação", "imunoterapia", "quimioterapia", "terapia-alvo"],
    biomarcadores: ["TNBC"],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Sacituzumab tirumotecan + Pembrolizumab + Rescue Medication + Carboplatin + Paclitaxel + Doxorubicin + Epirubicin + Cyclophosphamide + Capecitabine + Olaparib',
    comparador: 'Braço controle conforme protocolo',
    racional: 'Researchers are looking for new ways to treat types of breast cancer that are both:

* High-risk, which means the cancer may have a higher chance of getting worse or coming back after treatment
* Early-stage, which means the cancer is in the breast o...',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["PRONUTRIR ( Site 6120) · Fortaleza/Ceará", "Hospital Araújo Jorge ( Site 6100) · Goiânia/Goiás", "Liga Norte Riograndense Contra o Câncer ( Site 6111) · Natal/Rio Grande do Norte", "Associação Hospitalar Beneficente São Vicente de Paulo ( Site 6115) · Passo Fundo/Rio Grande do Sul", "Irmandade da Santa Casa de Misericórdia de Porto Alegre ( Site 6102) · Porto Alegre/Rio Grande do Sul"],
    estados: ["Santa Catarina", "Ceará", "Rio Grande do Sul", "Rio Grande do Norte", "Goiás", "São Paulo"],
    cidades: ["São José do Rio Preto", "Fortaleza", "Goiânia", "Natal", "Barretos", "Blumenau", "Porto Alegre", "Rio de Janeiro", "Passo Fundo"],
    patrocinador: 'Merck Sharp & Dohme LLC',
    fonte_url: 'https://clinicaltrials.gov/study/NCT06966700',
    contato_url: 'https://clinicaltrials.gov/study/NCT06966700',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct04862663',
    nome: 'CAPItello-292',
    titulo: 'Capivasertib + CDK4/6i + Fulvestrant for Advanced/Metastatic HR+/HER2- Breast Cancer (CAPItello-292)',
    nct: 'NCT04862663',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'mama',
    neoplasia_label: 'Mama',
    subtipo: '',
    linha_terapeutica: 'Avançado / metastático',
    cenario_clinico: 'Avançado / metastático',
    modalidade: ["terapia-alvo"],
    biomarcadores: ["HER2", "HR+"],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Capivasertib + Fulvestrant + Palbociclib + Ribociclib + Abemaciclib',
    comparador: 'Braço controle conforme protocolo',
    racional: 'A Phase Ib/III Open-label, Randomised Study of Capivasertib plus CDK4/6 Inhibitors and Fulvestrant versus CDK4/6 Inhibitors and Fulvestrant in Hormone Receptor-Positive and Human Epidermal Growth Factor Receptor 2-Negative Locally Advanced, Unresecta...',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Research Site · Alfenas", "Research Site · Blumenau", "Research Site · Natal", "Research Site · Porto Alegre", "Research Site · Porto Velho"],
    estados: [],
    cidades: ["Porto Velho", "Teresina", "Natal", "Blumenau", "Vitória", "Taubaté", "Alfenas", "Porto Alegre", "São Paulo"],
    patrocinador: 'AstraZeneca',
    fonte_url: 'https://clinicaltrials.gov/study/NCT04862663',
    contato_url: 'https://clinicaltrials.gov/study/NCT04862663',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct06380751',
    nome: 'AZD5305',
    titulo: 'Saruparib (AZD5305) Plus Camizestrant Compared With CDK4/6 Inhibitor Plus Endocrine Therapy or Plus Camizestrant in HR-Positive, HER2-Negative (IHC 0, 1+, 2+/ ISH Non-amplified), BRCA1, BRCA2, or P...',
    nct: 'NCT06380751',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'mama',
    neoplasia_label: 'Mama',
    subtipo: '',
    linha_terapeutica: '1ª linha',
    cenario_clinico: '1ª linha',
    modalidade: ["terapia-alvo"],
    biomarcadores: ["BRCA", "HER2", "HR+"],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Saruparib (AZD5305) + Camizestrant + Abemaciclib + Ribociclib + Palbociclib + Fulvestrant + Letrozole + Anastrozole + Exemestane',
    comparador: 'Braço controle conforme protocolo',
    racional: 'The primary objective of the study is to measure efficacy of saruparib (AZD5305) plus camizestrant compared with physician\'s choice CDK4/6i plus ET in patients with BRCA1, BRCA2, or PALB2m, HR-positive, HER2-negative (defined as IHC 0, 1+, 2+/ ISH no...',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Research Site · Cachoeira de Itapemirim", "Research Site · Curitiba", "Research Site · Fortaleza", "Research Site · Goiânia", "Research Site · Jaú"],
    estados: [],
    cidades: ["Curitiba", "Fortaleza", "Ribeirão Preto", "Goiânia", "Jaú", "Cachoeira de Itapemirim", "Porto Alegre", "Salvador", "São Paulo"],
    patrocinador: 'AstraZeneca',
    fonte_url: 'https://clinicaltrials.gov/study/NCT06380751',
    contato_url: 'https://clinicaltrials.gov/study/NCT06380751',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct05633654',
    nome: 'NCT05633654',
    titulo: 'Study of Sacituzumab Govitecan-hziy and Pembrolizumab Versus Treatment of Physician\'s Choice in Patients With Triple Negative Breast Cancer Who Have Residual Invasive Disease After Surgery and Neoa...',
    nct: 'NCT05633654',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'mama',
    neoplasia_label: 'Mama',
    subtipo: '',
    linha_terapeutica: 'Perioperatório',
    cenario_clinico: 'Perioperatório',
    modalidade: ["ADC", "combinação", "imunoterapia"],
    biomarcadores: ["HER2"],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Sacituzumab govitecan-hziy (SG) + Pembrolizumab + Capecitabine',
    comparador: 'Braço controle conforme protocolo',
    racional: 'The goal of this study is to find out if the experimental product, sacituzumab govitecan-hziy (SG) in combination with pembrolizumab given after surgery, is effective and safe compared to the treatment of physician\'s choice (TPC) which includes eithe...',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["St. de Habitações Individuais Sul QI 15 - Lago Sul, Brasília - DF, Brasil · Brasília", "Rua Myltho Anselmo da Silva, 870 - Mercês, Curitiba - PR, CEP 80510-130 · Curitiba", "R. Aderbal Ramos da Silva, 148 - Centro, Itajaí - SC, 88300-000, Brasil · Itajaí", "Av. Miguel Castro, 1355, Nossa Senhora de Nazaré, Natal/RN · Natal", "Rua Professor Annes Dias, 295 - Centro Histórico, Porto Alegre - RS, , Brasil · Porto Alegre"],
    estados: [],
    cidades: ["Brasília", "Curitiba", "Teresina", "Natal", "Porto Alegre", "Salvador", "Itajaí", "São Paulo"],
    patrocinador: 'Gilead Sciences',
    fonte_url: 'https://clinicaltrials.gov/study/NCT05633654',
    contato_url: 'https://clinicaltrials.gov/study/NCT05633654',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct06982521',
    nome: 'NCT06982521',
    titulo: 'Phase 3 Study of RLY-2608 + Fulvestrant vs Capivasertib + Fulvestrant as Treatment for Locally Advanced or Metastatic PIK3CA-mutant HR+/HER2- Breast Cancer',
    nct: 'NCT06982521',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'mama',
    neoplasia_label: 'Mama',
    subtipo: '',
    linha_terapeutica: 'Avançado / metastático',
    cenario_clinico: 'Avançado / metastático',
    modalidade: ["terapia-alvo"],
    biomarcadores: ["HER2", "HR+", "PIK3CA"],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'RLY-2608 + Capivasertib + Fulvestrant',
    comparador: 'Braço controle conforme protocolo',
    racional: 'This is a global, multicenter, open-label, randomized Phase 3 study comparing the efficacy and safety of RLY-2608 + fulvestrant to capivasertib + fulvestrant for the treatment of patients with HR+/HER2- ABC with PIK3CA mutation following recurrence o...',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Centro de Oncologia do ABC- CEON+ Unidade Sao Caetano do Sul · São Caetano do Sul/São Paulo", "Oncolinicas do Brasil Serviços Médicos S.A (Oncocentro) · Belo Horizonte", "Instituto do Câncer do Ceará · Fortaleza", "Oncoclinicas Natal- Centro de Pesquisa Oncology Natal · Natal", "Irmandade da Santa Casa de Misericórdia de Porto Alegre · Porto Alegre"],
    estados: ["São Paulo"],
    cidades: ["Fortaleza", "Belo Horizonte", "Natal", "Porto Alegre", "Rio de Janeiro", "Salvador", "São Caetano do Sul"],
    patrocinador: 'Relay Therapeutics, Inc.',
    fonte_url: 'https://clinicaltrials.gov/study/NCT06982521',
    contato_url: 'https://clinicaltrials.gov/study/NCT06982521',
    data_atualizacao: '2026-05-19',
  },

  // ============== MELANOMA ==============
  {
    id: 'nct06112314',
    nome: 'NCT06112314',
    titulo: 'IMC-F106C Regimen Versus Nivolumab Regimens in Previously Untreated Advanced Melanoma (PRISM-MEL-301)',
    nct: 'NCT06112314',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'melanoma',
    neoplasia_label: 'Melanoma',
    subtipo: '',
    linha_terapeutica: '1ª linha',
    cenario_clinico: '1ª linha',
    modalidade: ["imunoterapia"],
    biomarcadores: [],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Brenetafusp + Nivolumab + Nivolumab + Relatlimab',
    comparador: 'Braço controle conforme protocolo',
    racional: 'This is a phase 3, randomized, controlled study of brenetafusp (IMC-F106C) plus nivolumab compared to standard nivolumab regimens in HLA-A\*02:01-positive participants with previously untreated advanced melanoma.',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Centro de Pesquisa Clinica em Oncologia - Oncosite · Ijuí/Rio Grande do Sul", "Centro Gaucho Integrado de Oncologia, Hematologia, Ensino e Pesquisa Ltda · Porto Alegre/Rio Grande do Sul", "Fundacao Pio XII - Hospital de Cancer de Barretos - Hospital de Amor · Barretos", "Hospital Sirio-Libanes (HSL) - Centro de Oncologia - Brasilia · Brasília", "Centro de Pesquisas Oncologicas (CEPON) · Florianópolis"],
    estados: ["Rio Grande do Sul"],
    cidades: ["Brasília", "Fortaleza", "Barretos", "Ijuí", "Florianópolis", "Liberdade", "Porto Alegre", "Rio de Janeiro", "São Paulo"],
    patrocinador: 'Immunocore Ltd',
    fonte_url: 'https://clinicaltrials.gov/study/NCT06112314',
    contato_url: 'https://clinicaltrials.gov/study/NCT06112314',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct02332668',
    nome: 'MK-3475',
    titulo: 'A Study of Pembrolizumab (MK-3475) in Pediatric Participants With an Advanced Solid Tumor or Lymphoma (MK-3475-051/KEYNOTE-051)',
    nct: 'NCT02332668',
    fase: 'Ib/II',
    status: 'Recrutando',
    neoplasia: 'melanoma',
    neoplasia_label: 'Melanoma',
    subtipo: '',
    linha_terapeutica: 'Recidivado / refratário',
    cenario_clinico: 'Recidivado / refratário',
    modalidade: ["imunoterapia"],
    biomarcadores: ["PD-L1"],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Pembrolizumab',
    comparador: 'Braço controle conforme protocolo',
    racional: 'Researchers are looking for new ways to treat children with different types of melanoma (skin cancer), solid tumors, and lymphomas (blood cancers) that are any of these:

* Advanced, which means cancer spread in the body or cannot be removed with sur...',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["MSD Brasil · São Paulo"],
    estados: [],
    cidades: ["São Paulo"],
    patrocinador: 'Merck Sharp & Dohme LLC',
    fonte_url: 'https://clinicaltrials.gov/study/NCT02332668',
    contato_url: 'https://clinicaltrials.gov/study/NCT02332668',
    data_atualizacao: '2026-05-19',
  },

  // ============== MIELOMA MÚLTIPLO ==============
  {
    id: 'nct06208150',
    nome: 'Tal-P',
    titulo: 'A Study Comparing Talquetamab Plus Pomalidomide, Talquetamab Plus Teclistamab, and Elotuzumab, Pomalidomide, and Dexamethasone or Pomalidomide, Bortezomib, and Dexamethasone in Participants With Re...',
    nct: 'NCT06208150',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'mieloma',
    neoplasia_label: 'Mieloma Múltiplo',
    subtipo: '',
    linha_terapeutica: 'Recidivado / refratário',
    cenario_clinico: 'Recidivado / refratário',
    modalidade: ["bispecífico", "combinação", "quimioterapia"],
    biomarcadores: [],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Talquetamab + Pomalidomide + Teclistamab + Elotuzumab + Dexamethasone + Bortezomib',
    comparador: 'Braço controle conforme protocolo',
    racional: 'The purpose of this study is to compare the effectiveness of either talquetamab plus pomalidomide (Tal-P) or talquetamab plus teclistamab (Tal-Tec) with elotuzumab, pomalidomide, and dexamethasone (EPd) or pomalidomide, bortezomib, and dexamethasone...',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Cetus Oncologia · Belo Horizonte", "DF Star · Brasília", "Fundacao Universidade de Caxias do Sul · Caxias do Sul", "Hospital Erasto Gaertner- Liga Paranaense de Combate ao Cancer · Curitiba", "Hospital De Clinicas De Porto Alegre · Porto Alegre"],
    estados: [],
    cidades: ["São José do Rio Preto", "Brasília", "Curitiba", "Recife", "Belo Horizonte", "Porto Alegre", "Rio de Janeiro", "Salvador", "Caxias do Sul", "São Paulo"],
    patrocinador: 'Janssen Research & Development, LLC',
    fonte_url: 'https://clinicaltrials.gov/study/NCT06208150',
    contato_url: 'https://clinicaltrials.gov/study/NCT06208150',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct05552222',
    nome: 'Tec-DR',
    titulo: 'A Study of Teclistamab in Combination With Daratumumab and Lenalidomide (Tec-DR) and Talquetamab in Combination With Daratumumab and Lenalidomide (Tal-DR) in Participants With Newly Diagnosed Multi...',
    nct: 'NCT05552222',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'mieloma',
    neoplasia_label: 'Mieloma Múltiplo',
    subtipo: '',
    linha_terapeutica: 'Avançado / metastático',
    cenario_clinico: 'Avançado / metastático',
    modalidade: ["bispecífico", "combinação", "quimioterapia"],
    biomarcadores: [],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Teclistamab + Daratumumab + Lenalidomide + Dexamethasone + Talquetamab',
    comparador: 'Braço controle conforme protocolo',
    racional: 'The purpose of this study is to compare the efficacy of teclistamab in combination with daratumumab and lenalidomide (Tec-DR) and talquetamab in combination with daratumumab and lenalidomide (Tal-DR) versus daratumumab, lenalidomide, dexamethasone (D...',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Fundacao Pio XII · Barretos", "Santa Casa de Misericordia de Belo Horizonte · Belo Horizonte", "Liga Paranaense de Combate ao Cancer · Curitiba", "Instituto Do Cancer Do Ceara · Fortaleza", "Liga Norte Riograndense Contra O Cancer · Natal"],
    estados: [],
    cidades: ["Curitiba", "Fortaleza", "Ribeirão Preto", "Belo Horizonte", "Natal", "Barretos", "Porto Alegre", "Niterói", "Salvador", "São Paulo"],
    patrocinador: 'Janssen Research & Development, LLC',
    fonte_url: 'https://clinicaltrials.gov/study/NCT05552222',
    contato_url: 'https://clinicaltrials.gov/study/NCT05552222',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct06152575',
    nome: 'EPd',
    titulo: 'MagnetisMM-32: A Study to Learn About the Study Medicine Called Elranatamab in People With Multiple Myeloma (MM) That Has Come Back After Taking Other Treatments (Including Prior Treatment With an ...',
    nct: 'NCT06152575',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'mieloma',
    neoplasia_label: 'Mieloma Múltiplo',
    subtipo: '',
    linha_terapeutica: 'Recidivado / refratário',
    cenario_clinico: 'Recidivado / refratário',
    modalidade: ["bispecífico", "combinação", "quimioterapia"],
    biomarcadores: [],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Elranatamab + Elotuzumab + Pomalidomide + Dexamethasone + Bortezomib + Carfilzomib',
    comparador: 'Braço controle conforme protocolo',
    racional: 'The purpose of this study is to learn about the study medicine called elranatamab.This study aims to compare elranatamab to other medicines for the treatment of MM (a type of cancer).

This study is seeking participants who:

* Are 18 years of age or...',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Instituto D'Or de Pesquisa e Ensino (IDOR) - Filial Salvador · Salvador/Estado de Bahia", "Instituto Oncomed de Educação e Pesquisa · Niterói/Rio de Janeiro", "Oncomed Clínica Oncológica · Niterói/Rio de Janeiro", "Hospital Moinhos de Vento · Porto Alegre/Rio Grande do Sul", "Centro Gaucho Integrado De Oncologia, Hematologia, Ensino E Pesquisa · Porto Alegre/Rio Grande do Sul"],
    estados: ["São Paulo", "Rio Grande do Sul", "Estado de Bahia", "Rio de Janeiro"],
    cidades: ["Ribeirão Preto", "Jaú", "Porto Alegre", "Rio de Janeiro", "Salvador", "Niterói", "SP", "São Paulo"],
    patrocinador: 'Pfizer',
    fonte_url: 'https://clinicaltrials.gov/study/NCT06152575',
    contato_url: 'https://clinicaltrials.gov/study/NCT06152575',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct06679101',
    nome: 'BRd',
    titulo: 'A Study of Belantamab Mafodotin Administered in Combination With Lenalidomide and Dexamethasone (BRd) Versus Daratumumab, Lenalidomide, and Dexamethasone (DRd) in Participants With Newly Diagnosed ...',
    nct: 'NCT06679101',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'mieloma',
    neoplasia_label: 'Mieloma Múltiplo',
    subtipo: '',
    linha_terapeutica: 'Conforme protocolo',
    cenario_clinico: 'Conforme protocolo',
    modalidade: ["ADC", "combinação", "quimioterapia"],
    biomarcadores: [],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Belantamab mafodotin + Lenalidomide + Dexamethasone + Daratumumab',
    comparador: 'Braço controle conforme protocolo',
    racional: 'The purpose of this Phase 3 study is to evaluate if BRd prolongs progression free survival (PFS) and/or improves minimal residual disease (MRD) negative status compared with DRd in participants with TI-NDMM.',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["GSK Investigational Site · Salvador/Estado de Bahia", "GSK Investigational Site · Porto Alegre/Rio Grande do Sul", "GSK Investigational Site · Barretos", "GSK Investigational Site · Joinville", "GSK Investigational Site · Porto Alegre"],
    estados: ["Rio Grande do Sul", "Estado de Bahia"],
    cidades: ["Teresina", "Joinville", "Barretos", "Vitória", "Porto Alegre", "Salvador", "São Paulo"],
    patrocinador: 'GlaxoSmithKline',
    fonte_url: 'https://clinicaltrials.gov/study/NCT06679101',
    contato_url: 'https://clinicaltrials.gov/study/NCT06679101',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct05020236',
    nome: 'PF-06863135',
    titulo: 'A Study to Learn About the Study Medicine Elranatamab Alone and With Daratumumab in People With Multiple Myeloma Who Have Received Other Treatments',
    nct: 'NCT05020236',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'mieloma',
    neoplasia_label: 'Mieloma Múltiplo',
    subtipo: '',
    linha_terapeutica: 'Recidivado / refratário',
    cenario_clinico: 'Recidivado / refratário',
    modalidade: ["bispecífico", "combinação", "quimioterapia"],
    biomarcadores: ["BCMA"],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Elranatamab + Daratumumab + Pomalidomide + Dexamethasone',
    comparador: 'Braço controle conforme protocolo',
    racional: 'The purpose of this clinical trial is to (1) learn whether the BCMA-CD3 bispecific antibody elranatamab can provide more benefit to people with multiple myeloma compared to a combination therapy including daratumumab, pomalidomide, and dexamethasone,...',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Instituto D'Or de Pesquisa e Ensino (IDOR) - Filial Salvador · Salvador/Estado de Bahia", "Centro Gaucho Integrado De Oncologia, Hematologia, Ensino E Pesquisa · Porto Alegre/Rio Grande do Sul", "Hospital Mae de Deus · Porto Alegre/Rio Grande do Sul", "Clínica Médica São Germano LTDA · SP/São Paulo", "Instituto de Educação, Pesquisa e Gestão em Saúde · Rio de Janeiro"],
    estados: ["São Paulo", "Rio Grande do Sul", "Estado de Bahia"],
    cidades: ["Porto Alegre", "Rio de Janeiro", "Salvador", "SP", "São Paulo"],
    patrocinador: 'Pfizer',
    fonte_url: 'https://clinicaltrials.gov/study/NCT05020236',
    contato_url: 'https://clinicaltrials.gov/study/NCT05020236',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct05243797',
    nome: 'NCT05243797',
    titulo: 'Phase 3 Study of Teclistamab in Combination With Lenalidomide and Teclistamab Alone Versus Lenalidomide Alone in Participants With Newly Diagnosed Multiple Myeloma as Maintenance Therapy Following ...',
    nct: 'NCT05243797',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'mieloma',
    neoplasia_label: 'Mieloma Múltiplo',
    subtipo: '',
    linha_terapeutica: 'Manutenção',
    cenario_clinico: 'Manutenção',
    modalidade: ["bispecífico", "combinação", "quimioterapia"],
    biomarcadores: [],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Teclistamab + Lenalidomide',
    comparador: 'Braço controle conforme protocolo',
    racional: 'This is a multicenter, randomized, open-label, Phase 3 study in participants with newly diagnosed multiple myeloma to evaluate the benefits of teclistamab in combination with lenalidomide and teclistamab alone versus lenalidomide alone as maintenance...',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Hospital Mãe de Deus - Centro Integrado de Oncologia · Porto Alegre", "Hospital Santa Rita · Porto Alegre", "Instituto Americas de Ensino,Pesquisa e Inovação · Rio de Janeiro", "IDOR- Instituto D'or de pesquisa. Av. São Rafael · Salvador", "A Real e Benemérita Associação Portuguesa de Beneficência · São Paulo"],
    estados: [],
    cidades: ["Porto Alegre", "São Paulo", "Rio de Janeiro", "Salvador"],
    patrocinador: 'European Myeloma Network B.V.',
    fonte_url: 'https://clinicaltrials.gov/study/NCT05243797',
    contato_url: 'https://clinicaltrials.gov/study/NCT05243797',
    data_atualizacao: '2026-05-19',
  },

  // ============== PÂNCREAS ==============
  {
    id: 'nct07076121',
    nome: 'NCT07076121',
    titulo: 'A Study Comparing BMS-986504 in Combination With Nab-paclitaxel and Gemcitabine Versus Placebo in Combination With Nab-paclitaxel and Gemcitabine in Participants With Untreated Metastatic Pancreati...',
    nct: 'NCT07076121',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'pancreas',
    neoplasia_label: 'Pâncreas',
    subtipo: '',
    linha_terapeutica: 'Avançado / metastático',
    cenario_clinico: 'Avançado / metastático',
    modalidade: ["quimioterapia"],
    biomarcadores: [],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'BMS-986504 + Gemcitabine + Nab-paclitaxel',
    comparador: 'Placebo',
    racional: 'The purpose of this study is to assess the safety and efficacy of BMS-986504, a selective, MTA-cooperative PRMT5 inhibitor, in combination with Nab-paclitaxel/Gemcitabine (nab-p/gem) versus placebo in combination with nab-p/gem, in participants with...',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["CEDOES · Vitória/Espírito Santo", "Instituto D'Or de Pesquisa e Ensino (IDOR) - Filial Salvador · Salvador/Estado de Bahia", "Hospital Mario Penna · Belo Horizonte/Minas Gerais", "Liga Norte Riograndense Contra o Câncer · Natal/Rio Grande do Norte", "Instituto de Oncologia Saint Gallen · Santa Cruz do Sul/Rio Grande do Sul"],
    estados: ["Estado de Bahia", "Rio Grande do Sul", "Rio Grande do Norte", "Espírito Santo", "Minas Gerais", "São Paulo"],
    cidades: ["Belo Horizonte", "Natal", "Barretos", "Vitória", "Rio de Janeiro", "Salvador", "São Paulo", "Santa Cruz do Sul"],
    patrocinador: 'Bristol-Myers Squibb',
    fonte_url: 'https://clinicaltrials.gov/study/NCT07076121',
    contato_url: 'https://clinicaltrials.gov/study/NCT07076121',
    data_atualizacao: '2026-05-19',
  },

  // ============== PRÓSTATA ==============
  {
    id: 'nct06136650',
    nome: 'NHA',
    titulo: 'A Study of Opevesostat (MK-5684) Versus Alternative Next-generation Hormonal Agent (NHA) in Metastatic Castration-resistant Prostate Cancer (mCRPC) Post One NHA (MK-5684-004)',
    nct: 'NCT06136650',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'prostata',
    neoplasia_label: 'Próstata',
    subtipo: '',
    linha_terapeutica: 'Avançado / metastático',
    cenario_clinico: 'Avançado / metastático',
    modalidade: ["terapia-alvo"],
    biomarcadores: [],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Opevesostat + Dexamethasone + Fludrocortisone acetate + Hydrocortisone + Abiraterone acetate + Prednisone acetate + Enzalutamide',
    comparador: 'Braço controle conforme protocolo',
    racional: 'The purpose of this study is to assess the efficacy and safety of opevesostat plus hormone replacement therapy (HRT) compared to alternative abiraterone acetate or enzalutamide in participants with Metastatic Castration-resistant Prostate Cancer (mCR...',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["CRIO - CENTRO REGIONAL INTEGRADO DE ONCOLOGIA ( Site 0256) · Fortaleza/Ceará", "Hospital Santa Rita de Cassia ( Site 0271) · Vitória/Espírito Santo", "Obras Sociais Irma Dulce ( Site 0255) · Salvador/Estado de Bahia", "Hospital São Domingos ( Site 0258) · São Luís/Maranhão", "Hospital Mario Penna ( Site 0264) · Belo Horizonte/Minas Gerais"],
    estados: ["Santa Catarina", "Estado de Bahia", "Maranhão", "Ceará", "Rio Grande do Sul", "Paraná", "Espírito Santo", "Minas Gerais", "São Paulo"],
    cidades: ["São José do Rio Preto", "São Luís", "Curitiba", "Bragança Paulista", "Fortaleza", "Belo Horizonte", "Vitória", "Taubaté", "Salvador", "Porto Alegre", "Uberaba", "Itajaí", "São Paulo"],
    patrocinador: 'Merck Sharp & Dohme LLC',
    fonte_url: 'https://clinicaltrials.gov/study/NCT06136650',
    contato_url: 'https://clinicaltrials.gov/study/NCT06136650',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct06629779',
    nome: 'MEVROMETOSTAT',
    titulo: 'A Study to Learn How PF-06821497 (Mevrometostat) Works in Men With Metastatic Castration-resistant Prostate Cancer.',
    nct: 'NCT06629779',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'prostata',
    neoplasia_label: 'Próstata',
    subtipo: '',
    linha_terapeutica: 'Avançado / metastático',
    cenario_clinico: 'Avançado / metastático',
    modalidade: ["terapia-alvo"],
    biomarcadores: [],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'PF-06821497 + Enzalutamide',
    comparador: 'Placebo',
    racional: 'This study will explore whether a combination of the investigational drug PF-06821497 and enzalutamide will work better than taking enzalutamide alone in participants with mCRPC who are ARSi or abiraterone naïve.',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Oncocentro Servico Medicos e Hospitalares Ltda · Fortaleza/Ceará", "Hospital São Carlos · Fortaleza/Ceará", "Oncocentro Oncologia · Fortaleza/Ceará", "Instituto D'Or de Pesquisa e Ensino · Fortaleza/Ceará", "Crio - Centro Regional Integrado de Oncologia · Fortaleza/Ceará"],
    estados: ["Estado de Bahia", "Ceará", "Rio Grande do Sul", "Rio Grande do Norte", "Federal District", "São Paulo"],
    cidades: ["São José do Rio Preto", "Brasília", "Fortaleza", "Santo André", "Barretos", "Natal", "Porto Alegre", "Salvador", "São Paulo"],
    patrocinador: 'Pfizer',
    fonte_url: 'https://clinicaltrials.gov/study/NCT06629779',
    contato_url: 'https://clinicaltrials.gov/study/NCT06629779',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct06952803',
    nome: 'AZD5305',
    titulo: 'A Study of Metastases Free Survival With Saruparib vs Placebo Added to a Standard RT/ADT in Men With High-risk Prostate Cancer With a BRCA Mutation',
    nct: 'NCT06952803',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'prostata',
    neoplasia_label: 'Próstata',
    subtipo: '',
    linha_terapeutica: 'Perioperatório',
    cenario_clinico: 'Perioperatório',
    modalidade: ["terapia-alvo"],
    biomarcadores: ["BRCA"],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Saruparib + Abiraterone + Prednisolone/Prednisone + Androgen Deprivation Therapy (ADT)',
    comparador: 'Placebo',
    racional: 'The purpose of the study is to demonstrate superiority of Saruparib (AZD5305) relative to placebo added to a standard radiation therapy (RT) + androgen deprivation therapy (ADT) regimen by assessment of metastases-free survival in participants with h...',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Research Site · Cachoeiro de Itapemirim", "Research Site · Curitiba", "Research Site · Jaú", "Research Site · Londrina", "Research Site · Pelotas"],
    estados: [],
    cidades: ["Londrina", "Curitiba", "Jaú", "Cachoeiro de Itapemirim", "Porto Alegre", "Rio de Janeiro", "Salvador", "São Paulo", "Pelotas"],
    patrocinador: 'AstraZeneca',
    fonte_url: 'https://clinicaltrials.gov/study/NCT06952803',
    contato_url: 'https://clinicaltrials.gov/study/NCT06952803',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct07028853',
    nome: 'PF-06821497',
    titulo: 'This Study Will Explore Whether a Combination of the Investigational Drug Mevrometostat (PF-06821497) and Enzalutamide Will Work Better Than Taking Enzalutamide Alone in Participants With mCSPC Who...',
    nct: 'NCT07028853',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'prostata',
    neoplasia_label: 'Próstata',
    subtipo: '',
    linha_terapeutica: 'Avançado / metastático',
    cenario_clinico: 'Avançado / metastático',
    modalidade: ["terapia-alvo"],
    biomarcadores: [],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Mevrometostat + Enzalutamide',
    comparador: 'Placebo',
    racional: 'This study will explore whether a combination of the investigational drug mevrometostat (PF-06821497) and enzalutamide will work better than taking enzalutamide alone in participants with mCSPC who are ARPI naïve and have not yet received chemotherap...',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Crio - Centro Regional Integrado de Oncologia · Fortaleza/Ceará", "Hospital Erasto Gaertner · Curitiba/Paraná", "ONCOSITE - Centro de Pesquisa Clinica em Oncologia · Ijuí/Rio Grande do Sul", "Centro Gaucho Integrado De Oncologia, Hematologia, Ensino E Pesquisa · Porto Alegre/Rio Grande do Sul", "CEPHO - Centro de Estudos e Pesquisas de Hematologia e Oncologia · Santo André/São Paulo"],
    estados: ["Rio Grande do Sul", "Paraná", "São Paulo", "Ceará"],
    cidades: ["São José do Rio Preto", "Sorocaba", "Curitiba", "Fortaleza", "Santo André", "Ijuí", "Porto Alegre", "São Paulo"],
    patrocinador: 'Pfizer',
    fonte_url: 'https://clinicaltrials.gov/study/NCT07028853',
    contato_url: 'https://clinicaltrials.gov/study/NCT07028853',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct06136624',
    nome: 'NHA',
    titulo: 'Study of Opevesostat (MK-5684) Versus Alternative NHA in mCRPC (MK-5684-003)',
    nct: 'NCT06136624',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'prostata',
    neoplasia_label: 'Próstata',
    subtipo: '',
    linha_terapeutica: 'Avançado / metastático',
    cenario_clinico: 'Avançado / metastático',
    modalidade: ["terapia-alvo"],
    biomarcadores: [],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Opevesostat + Abiraterone acetate + Enzalutamide + Hydrocortisone + Fludrocortisone acetate + Prednisone + Dexamethasone',
    comparador: 'Braço controle conforme protocolo',
    racional: 'This is a phase 3, randomized, open-label study of opevesostat compared to alternative abiraterone acetate or enzalutamide in participants with metastatic castration-resistant prostate cancer (mCRPC) with respect to overall survival (OS) in participa...',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Hospital Santa Rita de Cassia-Centro de Pesquisa Clínica ( Site 0320) · Vitória/Espírito Santo", "Obras Sociais Irma Dulce ( Site 0302) · Salvador/Estado de Bahia", "Hospital Felicio Rocho ( Site 0317) · Belo Horizonte/Minas Gerais", "Hospital Mario Penna ( Site 0309) · Belo Horizonte/Minas Gerais", "Hospital Universitário Evangélico Mackenzie-Centro de Oncologia Mackenzie ( Site 0314) · Curitiba/Paraná"],
    estados: ["Santa Catarina", "Estado de Bahia", "Paraná", "Espírito Santo", "Minas Gerais", "São Paulo"],
    cidades: ["Bragança Paulista", "Curitiba", "Belo Horizonte", "Vitória", "Itajaí", "Salvador", "São Paulo"],
    patrocinador: 'Merck Sharp & Dohme LLC',
    fonte_url: 'https://clinicaltrials.gov/study/NCT06136624',
    contato_url: 'https://clinicaltrials.gov/study/NCT06136624',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct06120491',
    nome: 'AZD5305',
    titulo: 'Saruparib (AZD5305) vs Placebo in Men With Metastatic Castration-Sensitive Prostate Cancer Receiving Physician\'s Choice New Hormonal Agents',
    nct: 'NCT06120491',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'prostata',
    neoplasia_label: 'Próstata',
    subtipo: '',
    linha_terapeutica: 'Avançado / metastático',
    cenario_clinico: 'Avançado / metastático',
    modalidade: ["terapia-alvo"],
    biomarcadores: [],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Saruparib + Abiraterone Acetate + Darolutamide + Enzalutamide',
    comparador: 'Placebo',
    racional: 'The intention of the study is to demonstrate superiority of Saruparib (AZD5305) + physician\'s choice NHA relative to placebo + physician\'s choice NHA by assessment of radiographic progression-free survival (rPFS) in participants with mCSPC.',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Research Site · Curitiba", "Research Site · Pelotas", "Research Site · Porto Alegre", "Research Site · Rio de Janeiro", "Research Site · Salvador"],
    estados: [],
    cidades: ["São Luís", "Curitiba", "Porto Alegre", "Rio de Janeiro", "Salvador", "São Paulo", "Pelotas"],
    patrocinador: 'AstraZeneca',
    fonte_url: 'https://clinicaltrials.gov/study/NCT06120491',
    contato_url: 'https://clinicaltrials.gov/study/NCT06120491',
    data_atualizacao: '2026-05-19',
  },

  // ============== RIM · CCRCC ==============
  {
    id: 'nct07227402',
    nome: 'LITESPARK-033',
    titulo: 'A Clinical Study of Belzutifan and Zanzalintinib in People With Recurrent Kidney Cancer Following Adjuvant Therapy (MK-6482-033)',
    nct: 'NCT07227402',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'rim',
    neoplasia_label: 'Rim · ccRCC',
    subtipo: '',
    linha_terapeutica: 'Perioperatório',
    cenario_clinico: 'Perioperatório',
    modalidade: ["terapia-alvo"],
    biomarcadores: [],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Belzutifan + Zanzalintinib + Cabozantinib',
    comparador: 'Braço controle conforme protocolo',
    racional: 'Researchers are looking for more ways to treat advanced renal cell carcinoma (RCC) that is recurrent. Researchers want to learn if recurrent advanced renal cell carcinoma (RCC) responds (gets smaller or goes away) after treatment with belzutifan (MK-...',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["IPC - MT Instituto de Pesquisas Clínicas do Mato Grosso ( Site 0305) · Cuiabá/Mato Grosso", "Liga Norte Riograndense Contra o Câncer ( Site 0307) · Natal/Rio Grande do Norte", "Hospital Moinhos de Vento ( Site 0309) · Porto Alegre/Rio Grande do Sul", "Fundação Faculdade Regional de Medicina de São José do Rio Preto ( Site 0302) · São José do Rio Preto/São Paulo", "Hospital Alemao Oswaldo Cruz ( Site 0311) · São Paulo/São Paulo"],
    estados: ["Rio Grande do Sul", "Rio Grande do Norte", "Mato Grosso", "São Paulo"],
    cidades: ["São José do Rio Preto", "Natal", "Cuiabá", "Porto Alegre", "São Paulo"],
    patrocinador: 'Merck Sharp & Dohme LLC',
    fonte_url: 'https://clinicaltrials.gov/study/NCT07227402',
    contato_url: 'https://clinicaltrials.gov/study/NCT07227402',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct06638931',
    nome: 'Anti-PD1',
    titulo: 'Agnostic Therapy in Rare Solid Tumors',
    nct: 'NCT06638931',
    fase: 'II',
    status: 'Recrutando',
    neoplasia: 'rim',
    neoplasia_label: 'Rim · ccRCC',
    subtipo: '',
    linha_terapeutica: 'Avançado / metastático',
    cenario_clinico: 'Avançado / metastático',
    modalidade: ["imunoterapia"],
    biomarcadores: ["PD-L1"],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Nivolumab',
    comparador: 'Braço controle conforme protocolo',
    racional: 'The ANTARES study is a phase II basket trial designed to evaluate the tissue-agnostic efficacy of the monoclonal anti-PD1 antibody, nivolumab, in patients with advanced or metastatic rare tumors.

The study aims to treat rare malignancies with PD-L1...',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Hospital São Carlos · Fortaleza/Ceará", "Hospital São Rafael · Salvador/Estado de Bahia", "Hospital Santa Cruz · Curitiba/Paraná", "IDOR Recife · Recife/Pernambuco", "Instituto D'or de Pesquisa e Ensino · São Paulo/São Paulo"],
    estados: ["Estado de Bahia", "Pernambuco", "Ceará", "Paraná", "São Paulo"],
    cidades: ["Brasília", "Curitiba", "Fortaleza", "Recife", "Rio de Janeiro", "Salvador", "São Paulo"],
    patrocinador: 'Instituto do Cancer do Estado de São Paulo',
    fonte_url: 'https://clinicaltrials.gov/study/NCT06638931',
    contato_url: 'https://clinicaltrials.gov/study/NCT06638931',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct07293351',
    nome: 'RCC',
    titulo: 'A Study to Evaluate the Safety, Tolerability, and Efficacy of Pumitamig Alone or in Combination With Ipilimumab or Cabozantinib in Participants With Advanced Renal Cell Carcinoma (RCC) (ROSETTA RCC...',
    nct: 'NCT07293351',
    fase: 'Ib/II',
    status: 'Recrutando',
    neoplasia: 'rim',
    neoplasia_label: 'Rim · ccRCC',
    subtipo: '',
    linha_terapeutica: 'Avançado / metastático',
    cenario_clinico: 'Avançado / metastático',
    modalidade: ["bispecífico", "combinação", "imunoterapia", "terapia-alvo"],
    biomarcadores: [],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Pumitamig + Ipilimumab + Cabozantinib + Nivolumab',
    comparador: 'Braço controle conforme protocolo',
    racional: 'The purpose of this study is to evaluate the safety, tolerability, and efficacy of Pumitamig alone or in combination with Ipilimumab or Cabozantinib in participants with advanced Renal Cell Carcinoma (RCC)',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Local Institution - 0093 · Brasília/Federal District"],
    estados: ["Federal District"],
    cidades: ["Brasília"],
    patrocinador: 'Bristol-Myers Squibb',
    fonte_url: 'https://clinicaltrials.gov/study/NCT07293351',
    contato_url: 'https://clinicaltrials.gov/study/NCT07293351',
    data_atualizacao: '2026-05-19',
  },

  // ============== BEXIGA / UROTELIAL ==============
  {
    id: 'nct07218380',
    nome: 'NCT07218380',
    titulo: 'A Study of Vepugratinib (LY3866288) in Participants With Cancer in the Urinary Tract',
    nct: 'NCT07218380',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'urotelial',
    neoplasia_label: 'Bexiga / Urotelial',
    subtipo: '',
    linha_terapeutica: 'Avançado / metastático',
    cenario_clinico: 'Avançado / metastático',
    modalidade: ["combinação", "imunoterapia", "terapia-alvo"],
    biomarcadores: ["FGFR"],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Vepugratinib + EV + Pembrolizumab',
    comparador: 'Placebo',
    racional: 'The purpose of this study is to test a new medicine, vepugratinib, in comparison with placebo, to see if it is safe and can help people with a bladder cancer that is advanced or has spread.

Vepugratinib or placebo will be administered in combination...',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Fundação Pio XII - Hospital de Câncer de Barretos · Barretos", "CPAM - Centro de Pesquisas da Amazônia · Belém", "Oncocentro de Minas Gerais · Belo Horizonte", "Hospital Mario Penna · Belo Horizonte", "Hospital Tacchini · Bento Gonçalves"],
    estados: [],
    cidades: ["Londrina", "Curitiba", "Belo Horizonte", "Bento Gonçalves", "Barretos", "Natal", "João Pessoa", "São Caetano do Sul", "Porto Alegre", "Rio de Janeiro", "Salvador", "Belém", "São Paulo", "Santa Cruz do Sul"],
    patrocinador: 'Eli Lilly and Company',
    fonte_url: 'https://clinicaltrials.gov/study/NCT07218380',
    contato_url: 'https://clinicaltrials.gov/study/NCT07218380',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct06319820',
    nome: 'IR-NMIBC',
    titulo: 'A Study to Evaluate TAR-210 Versus Single Agent Intravesical Cancer Treatment in Participants With Bladder Cancer',
    nct: 'NCT06319820',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'urotelial',
    neoplasia_label: 'Bexiga / Urotelial',
    subtipo: '',
    linha_terapeutica: 'Conforme protocolo',
    cenario_clinico: 'Conforme protocolo',
    modalidade: ["quimioterapia"],
    biomarcadores: ["FGFR"],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'TAR-210 + Gemcitabine + MMC',
    comparador: 'Braço controle conforme protocolo',
    racional: 'The main purpose of this study is to compare the disease-free survival between participants receiving treatment with TAR-210 versus investigator\'s choice of intravesical chemotherapy for treatment of intermediate-risk NMIBC.',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Fundacao Pio XII · Barretos", "Universidade Estadual De Campinas · Campinas", "Liga Norte Riograndense Contra O Cancer · Natal", "Associacao Hospitalar Moinhos de Vento · Porto Alegre", "Irmandade da Santa Casa de Misericordia de Porto Alegre · Porto Alegre"],
    estados: [],
    cidades: ["Santo André", "Barretos", "Natal", "Porto Alegre", "Campinas", "Salvador", "São Paulo"],
    patrocinador: 'Janssen Research & Development, LLC',
    fonte_url: 'https://clinicaltrials.gov/study/NCT06319820',
    contato_url: 'https://clinicaltrials.gov/study/NCT06319820',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct06919965',
    nome: 'BCG',
    titulo: 'A Study to Evaluate TAR-210 Versus Intravesical Chemotherapy Treatment in Participants With High Risk Non-Muscle-Invasive Bladder Cancer',
    nct: 'NCT06919965',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'urotelial',
    neoplasia_label: 'Bexiga / Urotelial',
    subtipo: '',
    linha_terapeutica: 'Conforme protocolo',
    cenario_clinico: 'Conforme protocolo',
    modalidade: ["quimioterapia"],
    biomarcadores: ["FGFR"],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'TAR-210 + Mitomycin C + Gemcitabine',
    comparador: 'Braço controle conforme protocolo',
    racional: 'The main purpose of this study is to compare the disease-free survival (the length of time after randomization that a participant survives without any signs or symptoms of the cancer returning, or progressing) between Bacillus Calmette-Guérin (BCG) t...',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Liga Norte Riograndense Contra O Cancer · Natal", "Hospital Regional do Cancer - Hospital de Esperança · Presidente Prudente", "Fundacao Faculdade Regional De Medicina De Sao Jose Do Rio Preto · São José do Rio Preto", "Fundacao Faculdade de Medicina - Instituto do Cancer do Estado de Sao Paulo · São Paulo", "Real e Benemerita Associacao Portuguesa de Beneficencia · São Paulo"],
    estados: [],
    cidades: ["São José do Rio Preto", "Natal", "São Paulo", "Presidente Prudente"],
    patrocinador: 'Janssen Research & Development, LLC',
    fonte_url: 'https://clinicaltrials.gov/study/NCT06919965',
    contato_url: 'https://clinicaltrials.gov/study/NCT06919965',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct07419295',
    nome: 'MK-2870',
    titulo: 'A Clinical Trial of Sacituzumab Tirumotecan (Sac-TMT, MK-2870) to Treat Urothelial Cancer (MK-2870-031)',
    nct: 'NCT07419295',
    fase: 'III',
    status: 'Recrutando',
    neoplasia: 'urotelial',
    neoplasia_label: 'Bexiga / Urotelial',
    subtipo: '',
    linha_terapeutica: 'Avançado / metastático',
    cenario_clinico: 'Avançado / metastático',
    modalidade: ["ADC", "combinação", "imunoterapia", "quimioterapia"],
    biomarcadores: [],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Sacituzumab tirumotecan + Vinflunine + Docetaxel + Paclitaxel + Rescue medications for sacituzumab tirumotecan + Rescue medications for chemotherapy',
    comparador: 'Braço controle conforme protocolo',
    racional: 'Researchers are looking for new ways to treat locally advanced or metastatic urothelial cancer (UC). Current treatments for locally advanced or metastatic UC include chemotherapy, immunotherapy, and targeted therapy.

Researchers want to know if givi...',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Fundação Faculdade Regional de Medicina de São José do Rio Preto ( Site 0110) · São José do Rio Preto/São Paulo"],
    estados: ["São Paulo"],
    cidades: ["São José do Rio Preto"],
    patrocinador: 'Merck Sharp & Dohme LLC',
    fonte_url: 'https://clinicaltrials.gov/study/NCT07419295',
    contato_url: 'https://clinicaltrials.gov/study/NCT07419295',
    data_atualizacao: '2026-05-19',
  },
  {
    id: 'nct06534983',
    nome: 'NCT06534983',
    titulo: 'A Study to Evaluate the Efficacy and Safety of Autogene Cevumeran With Nivolumab Versus Nivolumab Alone in Participants With High-risk Muscle-invasive Urothelial Carcinoma (MIUC)',
    nct: 'NCT06534983',
    fase: 'II',
    status: 'Recrutando',
    neoplasia: 'urotelial',
    neoplasia_label: 'Bexiga / Urotelial',
    subtipo: '',
    linha_terapeutica: 'Perioperatório',
    cenario_clinico: 'Perioperatório',
    modalidade: ["imunoterapia"],
    biomarcadores: [],
    testes_fornecidos: 'Conforme protocolo do estudo',
    intervencao: 'Autogene Cevumeran + Nivolumab + Saline',
    comparador: 'Braço controle conforme protocolo',
    racional: 'The main purpose of the study is to evaluate the efficacy of adjuvant treatment with autogene cevumeran plus nivolumab compared with nivolumab in participants with high risk MIUC.

In this study participants will be enrolled in a safety run-in phase...',
    criterios_principais: [],
    criterios_exclusao: [],
    centros: ["Hospital Moinhos de Vento · Porto Alegre/Rio Grande do Sul"],
    estados: ["Rio Grande do Sul"],
    cidades: ["Porto Alegre"],
    patrocinador: 'Hoffmann-La Roche',
    fonte_url: 'https://clinicaltrials.gov/study/NCT06534983',
    contato_url: 'https://clinicaltrials.gov/study/NCT06534983',
    data_atualizacao: '2026-05-19',
  },