#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Batch B: Append 6 deeply-expanded guideline objects to guidelines-data.js
  - 3 TARE / Radioembolizacao hepatica
  - 3 Radioiodoterapia
"""
import os

target = r"C:\Users\marco\Desktop\TheraTrials Oncology\site\assets\js\guidelines-data.js"

content = '''
  // ═══════════════════════════════════════════════
  //  3. TARE / Radioembolização hepática
  // ═══════════════════════════════════════════════
  {
    id: "tare-eanm-procedure-2022",
    title: "EANM procedure guideline for the treatment of liver cancer and liver metastases with intra-arterial radioactive compounds",
    year: "2022",
    society: "EANM",
    type: "Procedure guideline",
    badges: ["essential"],
    category: "tare",
    categoryName: "TARE / Radioembolização hepática",
    categoryColor: "#F59E0B",
    scope: "Guideline procedimental abrangente da EANM para radioembolização trans-arterial (TARE) com microesferas de 90Y em tumores hepáticos primários e metastáticos. O documento consolida a experiência clínica europeia acumulada ao longo de duas décadas, integrando dados dos estudos randomizados SARAH e SIRveNIB (TARE vs sorafenibe em CHC avançado) e do estudo DOSISPHERE-01 (dosimetria personalizada vs padrão em CHC). Abrange todo o fluxo terapêutico desde a avaliação multidisciplinar inicial até o seguimento pós-procedimento, incluindo critérios de seleção, mapeamento angiográfico, dosimetria pré-terapêutica com 99mTc-MAA, técnica de administração e avaliação de resposta. Posiciona a TARE no algoritmo de tratamento do CHC segundo classificação BCLC e discute seu papel em metástases hepáticas de carcinoma colorretal (CCR), tumores neuroendócrinos (TNE) e colangiocarcinoma intra-hepático. Enfatiza a transição de modelos de cálculo de atividade empíricos (BSA) para dosimetria personalizada baseada em partição ou voxel.",
    indications: [
      "CHC BCLC B (intermediário) não candidato ou refratário a quimioembolização convencional (cTACE)",
      "CHC BCLC C com invasão portal segmentar ou lobar (sem trombose de veia porta principal completa bilateral)",
      "CHC BCLC 0/A como ponte para transplante hepático (downstaging dentro dos critérios de Milano)",
      "Downstaging de CHC para transplante: reduzir tumor(es) para dentro dos critérios de Milano ou UCSF",
      "Segmentectomia por radiação (radiation segmentectomy) para CHC unifocal <=5 cm em segmento único",
      "Lobectomia por radiação (radiation lobectomy) para hipertrofia contralateral pré-hepatectomia",
      "Metástases hepáticas de CCR quimiorrefratárias (pós-oxaliplatina e irinotecano) com doença predominantemente hepática",
      "Metástases hepáticas de TNE refratárias a PRRT, quimioterapia ou tratamento com análogos de somatostatina",
      "Colangiocarcinoma intra-hepático irressecável como opção terapêutica após falha de quimioterapia sistêmica",
      "Metástases hepáticas de câncer de mama, melanoma uveal e outros tumores com predomínio hepático (uso off-label selecionado)"
    ],
    keyPoints: [
      "Avaliação pré-procedimento obrigatória: TC trifásica ou RM com contraste hepatoespecífico (Gd-EOB-DTPA) para volumetria tumoral e hepática, avaliação de função hepática por Child-Pugh (A ou B7 sem ascite), escore ALBI e MELD",
      "Mapeamento angiográfico: arteriografia celíaca e mesentérica superior com identificação de anatomia vascular hepática variante, embolização profilática de colaterais gastrointestinais (artéria gastroduodenal, gástrica direita, cística) para prevenir deposição extrahepática",
      "Cintilografia com 99mTc-MAA SPECT/CT: administração de 150-200 MBq de MAA intra-arterial na mesma posição do cateter terapêutico planejado, cálculo de shunt hepatopulmonar (limite <20% para dose padrão, <10% ideal), avaliação de deposição extrahepática gastrointestinal",
      "Modelos de cálculo de atividade: BSA (empírico, cada vez menos recomendado), modelo de partição (tumoral vs não-tumoral, recomendado como mínimo) e dosimetria voxelizada (MIRD, padrão ideal para personalização)",
      "Doses-alvo por indicação: CHC >120 Gy ao tumor (preferencial >205 Gy conforme DOSISPHERE-01), <40 Gy ao pulmão cumulativo, <70 Gy ao fígado não-tumoral em parênquima com função preservada, <40 Gy se cirrose Child-Pugh B",
      "Resultados dos estudos SARAH e SIRveNIB: TARE não demonstrou superioridade de sobrevida global sobre sorafenibe em CHC avançado na análise por intenção de tratar, porém com melhor perfil de toxicidade e qualidade de vida; análises post-hoc sugerem benefício em subgrupos com doença unilobar e função hepática preservada",
      "Dados do DOSISPHERE-01: dosimetria personalizada com dose ao tumor >205 Gy resultou em taxa de resposta objetiva significativamente superior (71% vs 36%) comparada a dosimetria padrão BSA em CHC, estabelecendo o paradigma de personalização",
      "Segmentectomia por radiação: doses ablativas >400 Gy ao segmento alvo em CHC unifocal <=5 cm, com taxas de resposta completa patológica de 60-80% em séries cirúrgicas, alternativa curativa em pacientes não cirúrgicos",
      "Radiation lobectomy: tratamento seletivo de um lobo hepático com doses terapêuticas para induzir hipertrofia contralateral (>10% em 6-8 semanas), permitindo hepatectomia subsequente segura em pacientes com volume hepático futuro insuficiente",
      "Avaliação de resposta: mRECIST ou critérios EASL para CHC (baseados em realce arterial, não tamanho), RECIST 1.1 para metástases; primeira avaliação em 3 meses pós-TARE (resposta pode ser tardia)",
      "Manejo de síndrome pós-embolização: fadiga (60-80%), dor abdominal (30-50%), febre baixa e náusea, autolimitados em 1-2 semanas; tratamento sintomático com analgésicos, antieméticos e hidratação",
      "Toxicidade hepática: REILD (radioembolization-induced liver disease) ocorre em 0-4% quando respeitados limites dosimétricos; risco aumentado em cirrose avançada, quimioterapia hepatotóxica prévia (bevacizumabe) e tratamento bilobar simultâneo",
      "Contraindicações absolutas: shunt hepatopulmonar >20% sem possibilidade de redução, refluxo extrahepático gastrointestinal não corrigível por embolização, insuficiência hepática descompensada (Child-Pugh C, bilirrubina >2 mg/dL)",
      "Papel da equipe multidisciplinar: tumor board hepatobiliar com hepatologista, onco-cirurgião, radiointervencionista e médico nuclear é essencial para definir elegibilidade, timing e integração com terapias sistêmicas",
      "Imagem pós-procedimento: 90Y-PET/CT (método preferido, resolução espacial superior ~5 mm) ou 90Y-Bremsstrahlung SPECT/CT (alternativa) para verificação da distribuição de microesferas e dosimetria pós-tratamento"
    ],
    radiopharmaceuticals: "Microesferas de resina marcadas com 90Y (SIR-Spheres®, fabricante Sirtex) e microesferas de vidro marcadas com 90Y (TheraSphere®, fabricante Boston Scientific). O 90Y é um beta-emissor puro com energia máxima de 2,28 MeV, meia-vida de 64,1 horas e penetração média tecidual de 2,5 mm (máxima 11 mm). As microesferas de resina têm diâmetro de 20-60 micrômetros e atividade específica de 50 Bq/esfera, sendo administradas em maior número por dose (40-80 milhões de esferas). As microesferas de vidro têm diâmetro de 20-30 micrômetros e atividade específica muito mais alta (~2.500 Bq/esfera no dia da calibração), sendo administradas em menor número (1-8 milhões), com menor efeito embólico. Para planejamento dosimétrico pré-TARE utiliza-se 99mTc-MAA (macroagregados de albumina, partículas de 10-100 micrômetros) administrados por via intra-arterial durante o mapeamento angiográfico.",
    practicalAspects: "O fluxo de TARE envolve múltiplas etapas ao longo de 2-4 semanas. Na primeira sessão (work-up angiográfico), o radiointervencionista realiza arteriografia diagnóstica com mapeamento completo da anatomia arterial hepática, identifica e emboliza colaterais gastrointestinais, e administra 99mTc-MAA pela mesma posição de cateter planejada para terapia. Após 1-4 horas, o paciente realiza SPECT/CT de abdome para cálculo de shunt hepatopulmonar e avaliação de deposição extrahepática. O médico nuclear ou físico médico realiza a dosimetria pré-terapêutica com segmentação de volumes (tumor, fígado não-tumoral, pulmão) e cálculo de atividade pelo modelo escolhido. Na segunda sessão (dia do tratamento, tipicamente 1-2 semanas após), o radiointervencionista cateteriza seletivamente a artéria hepática na mesma posição do MAA e administra as microesferas de 90Y sob fluoroscopia, com infusão lenta e intercalada com soro para prevenir estase. O procedimento dura 60-90 minutos. Imediatamente após, ou dentro de 6 horas, realiza-se 90Y-PET/CT para verificação de biodistribuição e dosimetria pós-tratamento. O paciente permanece em observação por 4-6 horas e recebe alta no mesmo dia ou no dia seguinte, com prescrição de analgésicos, antieméticos e inibidor de bomba de prótons. Seguimento: TC ou RM contrastada em 3 meses para avaliação de resposta (mRECIST para CHC), função hepática seriada (ALT, AST, bilirrubina, albumina), e marcadores tumorais (AFP para CHC, CEA para CCR). Tratamentos subsequentes (outro lobo ou retreatamento) podem ser considerados após 6-8 semanas conforme função hepática e resposta.",
    limitations: "Contraindicado em pacientes com shunt hepatopulmonar >20% sem redução possível, pois a irradiação pulmonar cumulativa >30 Gy pode causar pneumonite por radiação potencialmente fatal. Trombose de veia porta principal bilateral é contraindicação relativa; trombose lobar ou segmentar pode ser tratada com abordagem contralateral. Função hepática comprometida (Child-Pugh C, bilirrubina >2 mg/dL, ascite refratária) associa-se a risco inaceitável de REILD. Os estudos SARAH e SIRveNIB não demonstraram superioridade de sobrevida global sobre sorafenibe em análise ITT para CHC avançado, o que limitou inicialmente o posicionamento da TARE nas diretrizes oncológicas; porém, análises de subgrupo e o paradigma de dosimetria personalizada (DOSISPHERE-01) estão redefinindo o cenário. A TARE requer infraestrutura complexa (sala de hemodinâmica, medicina nuclear, equipe multidisciplinar treinada), limitando sua disponibilidade. Quimioterapia hepatotóxica recente (especialmente bevacizumabe nas 8 semanas anteriores) aumenta o risco de REILD. Doença extrahepática predominante ou em progressão é contraindicação relativa, pois a TARE trata exclusivamente doença hepática. A variabilidade entre modelos dosimétricos (BSA vs partição vs voxel) pode resultar em atividades administradas significativamente diferentes, reforçando a necessidade de padronização.",
    reference: "Defined by EANM Dosimetry and Therapy Committees. Eur J Nucl Med Mol Imaging. 2022."
  },
  {
    id: "tare-dosimetry-sop-2021",
    title: "EANM Dosimetry Committee SOP: unified methodology for 99mTc-MAA pre- and 90Y peri-therapy dosimetry in liver radioembolization with 90Y microspheres",
    year: "2021",
    society: "EANM — Dosimetry Committee",
    type: "Standard operating procedure",
    badges: ["dosimetry"],
    category: "tare",
    categoryName: "TARE / Radioembolização hepática",
    categoryColor: "#F59E0B",
    scope: "SOP dosimétrico unificado publicado pelo Comitê de Dosimetria da EANM para padronizar a dosimetria em radioembolização hepática com microesferas de 90Y. O documento aborda de forma integrada a dosimetria pré-terapêutica baseada em SPECT/CT com 99mTc-MAA e a dosimetria peri-terapêutica com 90Y-PET/CT ou 90Y-Bremsstrahlung SPECT/CT. Fundamenta-se na evidência crescente de que a dosimetria personalizada melhora desfechos clínicos, como demonstrado no estudo DOSISPHERE-01 para CHC. Estabelece metodologia reprodutível e validada para quantificação de doses absorvidas em tumor, fígado não-tumoral e pulmão, permitindo comparação multicêntrica e otimização terapêutica. O SOP posiciona a dosimetria como componente essencial do fluxo de TARE, não mais opcional, alinhado com a Diretiva Europeia 2013/59/Euratom que exige otimização individualizada em terapias com radionuclídeos.",
    indications: [
      "Planejamento dosimétrico pré-TARE para cálculo personalizado de atividade de 90Y-microesferas baseado em doses-alvo tumorais e limites de segurança para fígado e pulmão",
      "Verificação dosimétrica pós-procedimento com 90Y-PET/CT para confirmar concordância entre dose planejada (MAA) e dose realmente depositada (90Y)",
      "Correlação dose-resposta em CHC: identificação de doses tumorais associadas a resposta objetiva e controle local prolongado",
      "Correlação dose-toxicidade: identificação de doses ao fígado não-tumoral associadas a risco de REILD e insuficiência hepática",
      "Avaliação de shunt hepatopulmonar quantitativo para decisão de elegibilidade e ajuste de atividade",
      "Monitoramento cumulativo de dose pulmonar em tratamentos bilobares sequenciais ou retratamentos",
      "Documentação dosimétrica padronizada para auditoria clínica, pesquisa multicêntrica e compliance regulatório",
      "Comparação de técnicas dosimétricas (planar vs SPECT vs PET) para validação interna de qualidade"
    ],
    keyPoints: [
      "Protocolo de aquisição SPECT/CT com 99mTc-MAA: energia de 140 keV, colimador LEHR, reconstrução iterativa OSEM (4-8 iterações, 8-16 subsets), correção de atenuação por mapa CT, correção de scatter (DEW ou TEW), matriz 128x128, 60-120 projeções, 15-30 s/projeção",
      "Segmentação hepática em TC: delineação de fígado total, volume tumoral (todas as lesões TARE-alvo), fígado não-tumoral e pulmão; segmentação manual assistida ou semi-automática com softwares dedicados (Simplicit90Y, Dosimetry Toolkit, MIM SurePlan MRT)",
      "Cálculo de dose absorvida pelo modelo de partição: D(tumor) = A_total x LSF_tumor x 50 / m_tumor (em Gy), onde LSF = liver-to-shunt fraction tumoral derivada da razão de contagens MAA tumor/fígado total",
      "Modelo MIRD voxelizado: dose calculada voxel a voxel a partir do mapa de atividade 3D derivado do SPECT/CT, convoluído com dose-point-kernel do 90Y, produzindo mapa de dose 3D e histogramas dose-volume (DVH)",
      "Limites de dose recomendados: tumor >120 Gy (mínimo para CHC), preferencial >205 Gy (conforme DOSISPHERE-01); fígado não-tumoral <70 Gy em parênquima saudável, <40 Gy em cirrose Child-Pugh B; pulmão <30 Gy por sessão e <50 Gy cumulativo",
      "Cálculo de shunt hepatopulmonar: método planar (contagens pulmonares/contagens hepáticas+pulmonares em imagem anterior-posterior com média geométrica) ou método SPECT/CT quantitativo (mais preciso para shunts <10%); limite clínico de 20% para elegibilidade",
      "Verificação pós-TARE com 90Y-PET/CT: aquisição em <6h pós-procedimento para melhor estatística de contagem (meia-vida 90Y = 64h), reconstrução TOF quando disponível melhora significativamente resolução; confirmação de que dose depositada corresponde ao planejamento MAA",
      "Comparação MAA vs 90Y: concordância dosimétrica média de 80-90% quando cateter posicionado identicamente; discordâncias >20% podem ocorrer por diferença de fluxo, posição de cateter ou redistribuição hemodinâmica",
      "Dose-volume histograms (DVH): análise de cobertura tumoral (D70, D90 = dose mínima recebida por 70%/90% do volume tumoral) e heterogeneidade de dose como preditores de resposta e toxicidade",
      "Correlação dose-resposta demonstrada: em CHC, dose média tumoral >200 Gy associa-se a taxa de resposta completa de 50-60%; em metástases de CCR, doses >60-80 Gy ao tumor associam-se a maior taxa de controle local",
      "Padronização de calibração: recomenda-se calibração cruzada entre gama-câmara (SPECT com 99mTc) e PET/CT (90Y) usando phantom hepático com esferas de diferentes volumes preenchidas com atividade conhecida",
      "Metodologia unificada permite que centros diferentes apliquem o mesmo protocolo, viabilizando estudos multicêntricos prospectivos de dosimetria em TARE",
      "Integração com inteligência artificial: algoritmos de segmentação automática de fígado e lesões em TC estão em validação e podem acelerar significativamente o fluxo dosimétrico",
      "Relatório dosimétrico padronizado deve incluir: volumes segmentados (mL), atividade administrada (GBq), modelo dosimétrico utilizado, dose absorvida média por compartimento (Gy), DVH quando disponível, shunt hepatopulmonar e concordância MAA vs 90Y",
      "O SOP constitui a base técnica para implementação da dosimetria como standard of care em TARE na Europa, alinhado com regulação EURATOM"
    ],
    radiopharmaceuticals: "O planejamento dosimétrico pré-TARE utiliza 99mTc-MAA (macroagregados de albumina marcados com 99mTc), administrados por via intra-arterial durante mapeamento angiográfico na atividade de 150-200 MBq (4-5 mCi). O 99mTc-MAA funciona como substituto das microesferas de 90Y, com partículas de 10-100 micrômetros que simulam a distribuição intravascular hepática. Para a terapia, utilizam-se microesferas de 90Y (resina SIR-Spheres ou vidro TheraSphere) em atividades calculadas pelo modelo dosimétrico (tipicamente 1-3 GBq). A verificação pós-tratamento é realizada com o próprio 90Y: o 90Y-PET/CT explora a emissão de pósitrons de produção interna (branching ratio ~32 por milhão de decaimentos) para gerar imagens tridimensionais de distribuição das microesferas depositadas.",
    practicalAspects: "O fluxo dosimétrico completo inicia na sessão de work-up angiográfico, quando 150-200 MBq de 99mTc-MAA são administrados pelo cateter posicionado na artéria alimentadora do tumor. Em 1-4 horas, o paciente realiza SPECT/CT de abdome e tórax em gama-câmara calibrada quantitativamente. O físico médico ou médico nuclear segmenta os volumes de interesse (tumor, fígado não-tumoral, pulmão) na TC co-registrada, mapeando a distribuição de MAA como proxy de 90Y. A dosimetria pré-terapêutica calcula a atividade necessária para atingir a dose-alvo tumoral respeitando os limites de órgãos de risco, utilizando o modelo de partição ou voxelizado conforme recursos do centro. No dia do tratamento, a atividade calculada é confirmada com calibrador de dose e administrada pelo radiointervencionista. Em até 6 horas pós-procedimento, o paciente realiza 90Y-PET/CT (preferencialmente com reconstrução TOF e tempo de aquisição prolongado de 15-20 min/bed position para compensar a baixa estatística do 90Y). Alternativamente, 90Y-Bremsstrahlung SPECT/CT pode ser realizado com colimadores de média-energia e correção de scatter dedicada, com resolução inferior ao PET. A dosimetria pós-tratamento é então calculada com o mesmo software e comparada ao planejamento MAA. O relatório dosimétrico é anexado ao prontuário do paciente e revisado na reunião multidisciplinar hepatobiliar para decisão de tratamentos subsequentes. Softwares de dosimetria voxelizada disponíveis incluem Simplicit90Y, MIM SurePlan MRT, Dosimetry Toolkit, PLANET Dose e QDOSE. Para centros iniciando dosimetria em TARE, o SOP recomenda começar com o modelo de partição e progredir para voxel conforme expertise e software disponível.",
    limitations: "O 99mTc-MAA é um substituto imperfeito das microesferas de 90Y: as partículas de MAA diferem em tamanho (10-100 vs 20-60 micrômetros), densidade e comportamento hemodinâmico, resultando em discordâncias de distribuição de 10-30% em até 20% dos casos. A posição do cateter entre a sessão de MAA e a terapia pode variar, gerando discrepâncias dosimétricas significativas. Dosimetria pré-terapêutica baseada em MAA pode superestimar ou subestimar a dose final, especialmente em tumores hipervascularizados com artérias alimentadoras múltiplas. A dosimetria voxelizada requer software especializado (custo de licença significativo) e expertise técnica, não sendo acessível em todos os centros. O 90Y-PET/CT, embora preferido para verificação pós-tratamento, tem limitações de estatística de contagem muito baixa (branching ratio mínimo do 90Y), exigindo tempo de aquisição prolongado e algoritmos de reconstrução otimizados. 90Y-Bremsstrahlung SPECT/CT tem resolução espacial inferior (~15 mm) comparada ao PET (~5-8 mm), limitando a análise voxelizada. A segmentação manual de tumores hepáticos é demorada e sujeita a variabilidade inter-observador, embora segmentação semi-automática e IA estejam reduzindo esse problema. Não existe ainda consenso universal sobre os limiares dosimétricos ideais para metástases (CCR, TNE, colangiocarcinoma), que são menos bem estabelecidos que para CHC.",
    reference: "Bastiaannet R, et al. EANM Dosimetry Committee SOP for unified MAA and 90Y dosimetry in liver radioembolization. Eur J Nucl Med Mol Imaging. 2021;48:S295."
  },
  {
    id: "tare-glass-microspheres-2025",
    title: "Clinical and dosimetric considerations for 90Y glass microsphere radioembolization",
    year: "2025",
    society: "Multissociedade",
    type: "Guidance document",
    badges: ["recent","dosimetry"],
    category: "tare",
    categoryName: "TARE / Radioembolização hepática",
    categoryColor: "#F59E0B",
    scope: "Documento de orientação multissociedade focado especificamente nas microesferas de vidro marcadas com 90Y (TheraSphere®), abordando suas particularidades clínicas e dosimétricas em relação às microesferas de resina. As microesferas de vidro possuem atividade específica muito superior, resultando em menor número de esferas por dose e consequentemente menor efeito embólico, o que as torna particularmente adequadas para pacientes com trombose portal. O documento consolida a experiência com segmentectomia por radiação (radiation segmentectomy) e lobectomia por radiação como estratégias curativas ou neo-adjuvantes em CHC, sustentadas por dados do estudo DOSISPHERE-01 e de múltiplas séries institucionais com follow-up a longo prazo. Discute o conceito de dosimetria ablativa, em que doses supraterapêuticas ao segmento alvo (>400 Gy) induzem necrose completa do tumor e do parênquima adjacente. Aborda ainda a integração da TARE com vidro com terapias sistêmicas emergentes (imunoterapia, inibidores de tirosina-quinase) e seu posicionamento no cenário competitivo atual do tratamento de CHC.",
    indications: [
      "CHC unifocal <=5 cm em segmento único: segmentectomia por radiação como alternativa curativa a ressecção ou ablação térmica em pacientes não-cirúrgicos ou com localização desfavorável",
      "CHC BCLC 0/A: tratamento com intenção curativa em pacientes que não são candidatos a cirurgia, com taxas de resposta completa patológica de 60-80% em séries cirúrgicas",
      "CHC BCLC B/C com trombose portal lobar ou segmentar: microesferas de vidro preferidas pelo menor efeito embólico, reduzindo risco de descompensação hepática",
      "Downstaging de CHC para transplante hepático: redução de tamanho e/ou número de tumores para enquadramento nos critérios de Milano ou critérios expandidos (UCSF, up-to-seven)",
      "Lobectomia por radiação (radiation lobectomy) para hipertrofia do futuro remanescente hepático: alternativa a embolização portal pré-operatória com vantagem de tratar simultaneamente o tumor",
      "Metástases hepáticas de CCR com doença predominantemente hepática após falha de quimioterapia de segunda linha",
      "Metástases hepáticas de TNE com alta carga tumoral hepática como consolidação ou alternativa a PRRT",
      "Colangiocarcinoma intra-hepático irressecável como opção de segunda ou terceira linha",
      "CHC em fígado não-cirrótico (fibrolamelar, CHC em esteatose): microesferas de vidro com dosimetria ablativa podem oferecer controle local excelente"
    ],
    keyPoints: [
      "Diferenças fundamentais entre microesferas de vidro e resina: TheraSphere tem atividade específica ~50x maior (~2.500 Bq/esfera vs ~50 Bq/esfera), resultando em 1-8 milhões de esferas por dose vs 40-80 milhões; menor efeito embólico com vidro, vantajoso em trombose portal mas potencialmente menor isquemia tumoral",
      "Dosimetria ablativa para radiation segmentectomy: dose-alvo >400 Gy ao segmento alvo contendo o tumor, com necrose completa do segmento e preservação do restante do fígado; volume do segmento alvo calculado por TC 3D volumétrica",
      "Modelo MIRD simplificado para TheraSphere: A(GBq) = D(Gy) x M(kg) / 50, onde D = dose-alvo e M = massa do compartimento alvo (segmento, lobo ou fígado perfundido); modelo direto e prático para cálculo de atividade",
      "Dados do DOSISPHERE-01: estudo randomizado em CHC demonstrando que dosimetria personalizada com dose tumoral >205 Gy (braço dosimetria) produziu taxa de resposta objetiva de 71% vs 36% (braço padrão BSA), com sobrevida global mediana de 26,6 vs 10,7 meses",
      "Radiation lobectomy: dose de 100-150 Gy ao lobo alvo induz atrofia ipsilateral e hipertrofia contralateral de >10% em 6-8 semanas, comparável a embolização portal, com vantagem adicional de efeito antitumoral simultâneo",
      "Shelf-life de TheraSphere: 12 dias a partir da data de calibração; a atividade específica decai exponencialmente, exigindo planejamento logístico preciso entre encomenda, calibração e data do procedimento",
      "Integração com TC 3D para planejamento volumétrico: softwares dedicados calculam volumes segmentares perfundidos pela artéria cateterizada, permitindo dosimetria personalizada precisa com mapa de dose 3D",
      "Trombose de veia porta: microesferas de vidro são preferidas sobre resina neste cenário devido ao menor efeito embólico, reduzindo o risco de comprometimento adicional do fluxo portal e descompensação hepática",
      "Séries de longo prazo de radiation segmentectomy: sobrevida global mediana de 30-50 meses em CHC BCLC 0/A tratados com doses ablativas, competitivo com ablação térmica e ressecção em pacientes selecionados",
      "Combinação com imunoterapia (atezolizumabe+bevacizumabe) e TKI (lenvatinibe, sorafenibe): dados preliminares sugerem segurança e potencial sinergismo; trials prospectivos em andamento para CHC intermediário e avançado",
      "Papel em bridge to transplant: TARE com vidro pode manter pacientes dentro dos critérios de listagem enquanto aguardam transplante, com taxas de exclusão por progressão inferiores a observação ou cTACE em algumas séries",
      "Avaliação de resposta após radiation segmentectomy: zona de necrose avascular completa na TC/RM em 3-6 meses, sem realce arterial residual; biópsia pós-tratamento raramente necessária quando imagem demonstra necrose completa",
      "Toxicidade: síndrome pós-radioembolização similar a resina, porém com menor incidência de dor abdominal em alguns estudos (menor efeito embólico); REILD incomum quando respeitados limites dosimétricos para fígado não-tumoral",
      "Calibração no dia e hora: a atividade da ampola de TheraSphere deve ser verificada no dia do procedimento com calibrador de dose, aplicando fator de decaimento desde a data de calibração do fabricante",
      "Custo e disponibilidade: TheraSphere tem custo por procedimento geralmente superior ao de SIR-Spheres; disponibilidade limitada em alguns países, especialmente na América Latina, com implicações para acesso dos pacientes"
    ],
    radiopharmaceuticals: "Microesferas de vidro marcadas com 90Y (TheraSphere®, fabricante Boston Scientific). Cada esfera tem diâmetro de 20-30 micrômetros e atividade específica de aproximadamente 2.500 Bq na data de calibração, decaindo conforme meia-vida do 90Y (64,1 horas) ao longo de um shelf-life de 12 dias. Uma dose típica para segmentectomia por radiação contém 1-4 milhões de esferas, enquanto para lobectomia a dose pode conter 4-8 milhões. O 90Y incorporado na matriz de vidro permanece estável, sem lixiviação significativa in vivo. A atividade por ampola varia de 3 a 20 GBq na data de calibração, disponível em faixas de atividade pré-definidas. O vidro biocompatível é não biodegradável, permanecendo no leito vascular tumoral indefinidamente após implantação.",
    practicalAspects: "O planejamento para microesferas de vidro segue o fluxo padrão de TARE com particularidades específicas. A volumetria hepática é realizada em TC trifásica com software 3D, calculando o volume do compartimento alvo (segmento, setor ou lobo perfundido pela artéria cateterizada). O modelo MIRD simplificado é aplicado: A(GBq) = D(Gy) x M(kg) / 50. Para radiation segmentectomy, a dose-alvo típica é >400 Gy ao segmento (incluindo tumor e parênquima adjacente). Para lobectomia, 100-150 Gy ao lobo. Para tratamento lobar padrão, a dose-alvo tumoral deve ser >205 Gy conforme DOSISPHERE-01. O MAA SPECT/CT é fundamental para confirmar a distribuição intravascular e calcular o shunt hepatopulmonar. No dia do procedimento, a atividade residual na ampola é calibrada e o volume total de microesferas é administrado por cateterização seletiva. Como TheraSphere tem menor efeito embólico, o endpoint angiográfico durante a administração não é estase (diferente de resina), e sim a infusão completa da dose calculada. Imagem pós-procedimento com 90Y-PET/CT em <6 horas permite verificação dosimétrica e comparação com planejamento. Seguimento clínico inclui função hepática seriada nas primeiras 4-6 semanas (bilirrubina, albumina, INR), marcadores tumorais e TC/RM contrastada em 3 meses. Para radiation segmentectomy, a resposta esperada é necrose avascular completa do segmento tratado. Avaliação pelo tumor board hepatobiliar define necessidade de terapia adicional. Pacientes candidatos a transplante são reavaliados com critérios de imagem a cada 3 meses.",
    limitations: "Os dados do estudo DOSISPHERE-01 foram obtidos exclusivamente em pacientes com CHC, e a extrapolação de limiares dosimétricos para metástases hepáticas (CCR, TNE, colangiocarcinoma) requer cautela, pois a radiossensibilidade tumoral e a relação dose-resposta podem diferir significativamente. O menor efeito embólico das microesferas de vidro, embora vantajoso em trombose portal, pode resultar em menor isquemia tumoral comparada às microesferas de resina, com potencial impacto na resposta de tumores hipervasculares. O shelf-life de 12 dias exige coordenação logística precisa entre encomenda, calibração e data do procedimento, limitando a flexibilidade de agendamento. O custo por procedimento é geralmente superior ao de microesferas de resina e pode ser proibitivo em sistemas de saúde com recursos limitados. A disponibilidade de TheraSphere é restrita em muitos países latino-americanos, limitando o acesso de pacientes. A dosimetria ablativa requer segmentação volumétrica precisa e software de planejamento 3D, com curva de aprendizado significativa. Os dados de combinação com imunoterapia e TKI são preliminares e baseados em séries pequenas ou trials em fase inicial; segurança e eficácia dessa abordagem combinada ainda estão sendo estabelecidas. Em tumores hepáticos com alta heterogeneidade vascular (shunts arteriovenosos intratumorais), a dosimetria baseada em MAA pode ser especialmente imprecisa.",
    reference: "Clinical and dosimetric considerations for 90Y glass microsphere radioembolization. 2025."
  },

  // ═══════════════════════════════════════════════
  //  4. Radioiodoterapia
  // ═══════════════════════════════════════════════
  {
    id: "rait-snmmi-eanm-dtc-2022",
    title: "SNMMI Procedure Standard/EANM Practice Guideline for Nuclear Medicine Evaluation and Therapy of Differentiated Thyroid Cancer",
    year: "2022",
    society: "SNMMI · EANM",
    type: "Procedure standard / Practice guideline",
    badges: ["essential"],
    category: "tireoide",
    categoryName: "Radioiodoterapia",
    categoryColor: "#F472B6",
    scope: "Guideline procedimental conjunto SNMMI/EANM que padroniza a avaliação por medicina nuclear e a terapia com 131I (radioiodoterapia, RAI) em carcinoma diferenciado de tireoide (CDT), incluindo os tipos papilífero, folicular, variante de células de Hurthle e formas pouco diferenciadas com captação de iodo preservada. O documento integra a estratificação de risco da ATA 2015, o sistema de resposta ao tratamento e a dosimetria em cenários selecionados, fornecendo um framework procedimental completo desde o preparo até o seguimento a longo prazo. Posiciona a RAI no contexto do manejo multimodal do CDT, reconhecendo a tendência contemporânea de desintensificação em doença de baixo risco e intensificação em doença de alto risco ou metastática. Incorpora evidência de estudos como ESTIMABL1 e HiLo que demonstraram equivalência de ablação com atividades baixas (30 mCi) e preparo com rhTSH vs suspensão hormonal em pacientes de baixo risco.",
    indications: [
      "Ablação de remanescente tireoidiano pós-tireoidectomia total em CDT de risco intermediário ATA (invasão microscópica extratireoidiana, linfonodo metastático N1, histologia agressiva como variante de células altas ou colunar)",
      "Ablação em CDT de alto risco ATA (extensão extratireoidiana macroscópica, ressecção incompleta R1/R2, metástases a distância, linfonodo >3 cm)",
      "Terapia adjuvante em CDT com doença residual microscópica (margens positivas) ou doença linfonodal volumosa (N1b extenso) após cirurgia",
      "Terapia de doença metastática iodo-ávida: metástases pulmonares micronodulares difusas, metástases ósseas, metástases linfonodais mediastínais ou cervicais irressecáveis",
      "Retratamento em doença persistente ou recorrente com captação de RAI confirmada em PCI ou SPECT/CT",
      "PCI diagnóstica (pesquisa de corpo inteiro) com 123I ou 131I em baixa dose para estadiamento pós-operatório ou seguimento de doença indeterminada",
      "Ablação seletiva em CDT de baixo risco com fatores desfavoráveis isolados: tumor 1-4 cm, variante agressiva, invasão linfovascular extensa",
      "Cenários em que tireoglobulina pós-operatória estimulada é elevada (>1-2 ng/mL) sem doença estrutural identificável"
    ],
    keyPoints: [
      "Estratificação de risco ATA como base para decisão terapêutica: baixo risco (T1-T2 N0M0, sem invasão linfovascular, histologia clássica) — ablação não rotineira; intermediário — ablação recomendada; alto risco — terapia com RAI recomendada",
      "Atividades recomendadas para ablação de remanescente: 30 mCi (1,1 GBq) em baixo risco selecionado (conforme ESTIMABL1/HiLo), 50-100 mCi (1,85-3,7 GBq) em risco intermediário, 100-150 mCi (3,7-5,55 GBq) em alto risco sem doença estrutural residual",
      "Atividades para terapia de doença metastática: 100-200 mCi (3,7-7,4 GBq) para doença linfonodal, 150-200 mCi (5,55-7,4 GBq) para metástases pulmonares macronodulares e ósseas, 100-150 mCi para metástases pulmonares micronodulares difusas (com dosimetria mandatória por risco de fibrose pulmonar)",
      "Preparo com TSH elevado (>30 mUI/L): opção 1 — suspensão de levotiroxina por 3-4 semanas (com ou sem triiodotironina de ponte nas primeiras 2 semanas); opção 2 — rhTSH (Thyrogen®) 0,9 mg IM em D-2 e D-1, RAI em D0; rhTSH preferido em pacientes de baixo/intermediário risco sem doença estrutural, e obrigatório em pacientes com hipopituitarismo",
      "Dieta hipoiódica por 1-2 semanas antes do tratamento: evitar alimentos ricos em iodo (frutos do mar, laticínios processados, sal iodado, contrastes iodados recentes), com ingesta de iodo <50 microgramas/dia ideal",
      "PCI diagnóstica pós-dose (5-8 dias): imagem planar de corpo inteiro anterior e posterior + SPECT/CT de pescoço e tórax (obrigatório); SPECT/CT de abdome quando suspeitada doença abdominal; detecta captação ectópica não prevista em 10-15% dos casos",
      "Dosimetria indicada em: atividades cumulativas elevadas (>600 mCi), metástases pulmonares difusas (limite de 80 mCi de retenção pulmonar em 48h), insuficiência renal (clearance de 131I reduzido), pacientes idosos com comorbidades, e retratamentos múltiplos",
      "Sistema de resposta ao tratamento ATA para reclassificação dinâmica: resposta excelente (Tg estimulada <1 ng/mL, imagem negativa), resposta indeterminada (Tg 1-10 ng/mL, achados inespecíficos), resposta bioquímica incompleta (Tg >10 ng/mL, imagem negativa), resposta estrutural incompleta (doença mensurável persistente)",
      "Stunning effect: PCI diagnóstica pré-terapêutica com 131I em doses de 2-5 mCi pode reduzir a captação terapêutica subsequente em até 50%; para evitar, utilizar 123I para PCI diagnóstica (sem stunning) ou administrar RAI terapêutico sem PCI prévia (preferência em alto risco)",
      "Monitoramento pós-RAI: hemograma completo em 6-8 semanas (nadir leucocitário), função renal, tireoglobulina (Tg) basal e estimulada, anticorpos anti-Tg (interferência no ensaio), US cervical em 6-12 meses",
      "Contracepção obrigatória: mulheres devem evitar gestação por 6-12 meses pós-RAI; homens por 4-6 meses; discutir criopreservação de esperma antes de altas atividades cumulativas",
      "Xerostomia pós-RAI: hidratação abundante, sialagogos (limão, chicletes ácidos), massagem salivar; glândulas salivares são o principal órgão de toxicidade crônica em RAI repetitivo",
      "Risco de segundo tumor primário: atividade cumulativa >600 mCi (22 GBq) associada a risco aumentado de leucemia aguda (risco absoluto ~1%), câncer de bexiga e câncer de mama; ponderar benefício-risco em retratamentos",
      "Critérios para definição de doença iodo-refratária: perda de captação em lesão(es) conhecida(s) no PCI pós-dose, progressão estrutural dentro de 12 meses pós-RAI apesar de captação, atividade cumulativa >600 mCi sem benefício demonstrável",
      "Integração com PET-FDG: 18F-FDG PET/CT indicado em CDT com Tg elevada e PCI negativa (flip-flop phenotype), em doença de alto grau/pouco diferenciada e para avaliação de doença potencialmente iodo-refratária; captação de FDG em lesão sem captação de iodo indica refratariedade e pior prognóstico"
    ],
    radiopharmaceuticals: "131I-Iodeto de sódio (NaI) em cápsulas gelatinosas ou solução oral, sendo o agente terapêutico padrão. Atividades administradas variam de 30 mCi (1,1 GBq) para ablação em baixo risco até 200-300 mCi (7,4-11,1 GBq) para doença metastática extensa. O 131I é beta-emissor (energia máxima 0,61 MeV, penetração média 0,4 mm) com componente gama (364 keV) que permite imageamento pós-dose. Meia-vida física de 8,02 dias. Para PCI diagnóstica, utiliza-se preferencialmente 123I (159 keV, gama puro, meia-vida 13,2 horas) na atividade de 1-2 mCi (37-74 MBq), que não causa stunning; alternativamente, 131I em dose baixa (1-3 mCi). O 124I (beta+ emissor, meia-vida 4,18 dias) pode ser utilizado para PET/CT dosimétrica pré-terapêutica em centros especializados.",
    practicalAspects: "O fluxo completo de RAI para CDT inicia com a tireoidectomia total (requisito para ablação efetiva). O preparo para RAI começa 3-4 semanas antes com suspensão de levotiroxina (ou 2 dias antes com rhTSH). A dieta hipoiódica é iniciada 1-2 semanas antes. No dia do tratamento (D0), confirma-se TSH >30 mUI/L (ou administração de rhTSH em D-2 e D-1), coleta-se Tg basal, e o paciente recebe a cápsula de 131I oral em jejum de pelo menos 2 horas. Após a administração, o paciente permanece em isolamento em quarto plumbífero (obrigatório no Brasil para atividades >1,11 GBq / 30 mCi por norma da CNEN) por 24-72 horas, até que a taxa de dose a 1 metro seja inferior ao limite regulatório de liberação (tipicamente <25 microSv/h ou <50 microSv/h conforme país). Durante o isolamento, hidratação abundante (2-3 L/dia) e estimulação de glândulas salivares. O PCI pós-dose é realizado em D5-D8: varredura planar de corpo inteiro (velocidade 5-10 cm/min, colimador de alta energia) seguida de SPECT/CT de pescoço e tórax. O SPECT/CT aumenta a sensibilidade em 15-30% comparado ao planar isolado e fornece localização anatômica precisa. Após alta, o paciente recebe orientações escritas de radioproteção domiciliar: manter distância >1 metro de crianças e gestantes por 5-7 dias, não compartilhar utensílios, descarga dupla no vaso sanitário. A levotiroxina é reiniciada em dose supressiva (TSH-alvo <0,1 mUI/L em alto risco, 0,1-0,5 em intermediário) ou substitutiva (TSH 0,5-2,0 em baixo risco com resposta excelente). Seguimento: Tg + anti-Tg em 6-12 semanas, US cervical em 6-12 meses, e reclassificação de risco pelo sistema de resposta ao tratamento ATA.",
    limitations: "CDT iodo-refratário (perda de captação de RAI ou progressão apesar de RAI) não se beneficia de doses adicionais e deve ser encaminhado para TKI (lenvatinibe, sorafenibe) ou terapias-alvo (selpercatinibe para RET+, larotrectinibe para NTRK+). O stunning effect com 131I diagnóstico pode comprometer a eficácia terapêutica, e sua relevância clínica permanece debatida; preferir 123I para PCI diagnóstica ou omitir PCI pré-terapêutica em pacientes de alto risco. Atividade cumulativa >600 mCi (22 GBq) associa-se a risco aumentado de leucemia aguda mieloide e síndrome mielodisplásica (risco absoluto ~1-2%), exigindo discussão de benefício-risco em cada retratamento. Xerostomia crônica afeta qualidade de vida significativamente em 10-30% dos pacientes com doses cumulativas elevadas. Metástases pulmonares difusas micronodulares exigem dosimetria (limite de retenção pulmonar de 80 mCi em 48h) para evitar fibrose pulmonar. A variabilidade na preparação da dieta hipoiódica entre pacientes pode afetar a eficácia da ablação. Em centros sem SPECT/CT, a PCI planar isolada pode subestimar a extensão da doença. Pacientes com anticorpos anti-Tg positivos não podem utilizar tireoglobulina como marcador confiável de seguimento, necessitando de tendência de título de anticorpos e imagem funcional. Regulamentações de radioproteção para isolamento e liberação variam significativamente entre países, criando heterogeneidade na prática.",
    reference: "Avram AM, et al. SNMMI Procedure Standard/EANM Practice Guideline for Nuclear Medicine Evaluation and Therapy of Differentiated Thyroid Cancer. J Nucl Med. 2022;63(6):e1-e35."
  },
  {
    id: "rait-eanm-benign-2023",
    title: "The EANM guideline on radioiodine therapy of benign thyroid disease",
    year: "2023",
    society: "EANM",
    type: "Guideline",
    badges: [],
    category: "tireoide",
    categoryName: "Radioiodoterapia",
    categoryColor: "#F472B6",
    scope: "Guideline europeu dedicado exclusivamente ao uso terapêutico de 131I em doenças tireoidianas benignas, publicado pela EANM em 2023. Abrange as três principais indicações de RAI benigno: doença de Graves, bócio multinodular tóxico (BMNT) e adenoma tóxico (Plummer), além de discutir o uso em bócio não-tóxico volumoso com risco cirúrgico elevado. O documento fornece orientação detalhada sobre seleção de pacientes, cálculo de atividade (métodos fixo e calculado por Marinelli), preparo, administração, manejo de complicações e seguimento. Incorpora a evidência contemporânea sobre eficácia comparativa com antitireoidianos e cirurgia, posicionando a RAI como opção terapêutica de primeira ou segunda linha conforme o contexto clínico. Aborda extensamente a controvérsia sobre oftalmopatia de Graves pós-RAI e as estratégias de prevenção com corticoterapia profilática. Reflete a experiência predominantemente europeia, onde a RAI para doença benigna é amplamente praticada e disponível na maioria dos centros de medicina nuclear.",
    indications: [
      "Doença de Graves (bócio difuso tóxico) refratária a antitireoidianos (metimazol/carbimazol) após 12-18 meses de tratamento, ou com recidiva após suspensão",
      "Doença de Graves como primeira opção terapêutica em pacientes >40 anos sem oftalmopatia ativa moderada-grave, ou com contraindicação a antitireoidianos (agranulocitose, hepatotoxicidade)",
      "Bócio multinodular tóxico (BMNT) sintomático com tireotoxicose laboratorial e nódulos funcionantes confirmados por cintilografia com 99mTc-pertecnetato ou 123I",
      "Adenoma tóxico (Plummer) com área quente supressora ao mapeamento cintilográfico, como alternativa à cirurgia em pacientes com risco operatório",
      "Bócio multinodular não-tóxico volumoso (>60-80 mL) em pacientes com risco cirúrgico elevado (idosos, comorbidades cardiopulmonares) para redução de volume tireoidiano",
      "Bócio recidivado pós-tireoidectomia parcial com tireotoxicose recorrente",
      "Hipertireoidismo subclínico persistente (TSH suprimido, T3/T4 normais) em pacientes com fibrilação atrial ou osteoporose, não controlados com observação",
      "Hipertireoidismo induzido por amiodarona tipo 1 (com substrato nodular autônomo) após controle inicial com tionamidas, para terapia definitiva"
    ],
    keyPoints: [
      "Cálculo de atividade — método fixo: atividades empíricas pré-definidas por diagnóstico (200-400 MBq para Graves, 400-800 MBq para BMNT, 400-600 MBq para AT); simples e amplamente utilizado, porém sem personalização",
      "Cálculo de atividade — método calculado (Marinelli): A(MBq) = [D(Gy) x M(g) x 24.67] / [captação(%) x Teff(dias)], onde D = dose-alvo, M = massa tireoidiana por US, captação = RAIU de 24h e Teff = meia-vida efetiva do 131I; permite personalização baseada em anatomia e função do paciente individual",
      "Doses-alvo por patologia: 150-200 Gy para Graves (intenção ablativa, hipotireoidismo como desfecho desejado), 300-400 Gy para BMNT (necessário maior dose pela captação heterogênea e resistência relativa de nódulos), 300 Gy para adenoma tóxico (foco no nódulo autônomo)",
      "Suspensão de antitireoidianos antes da RAI: metimazol 3-7 dias antes (controvérsia sobre impacto na eficácia; evidência sugere que suspensão >=7 dias melhora taxa de cura), carbimazol 2-3 semanas antes por meia-vida mais longa; reiniciar apenas se necessário 3-7 dias após RAI",
      "Pré-tratamento com antitireoidianos em populações de risco: obrigatório em idosos >70 anos, cardiopatas (insuficiência cardíaca, fibrilação atrial), e pacientes com T4L muito elevado (>2-3x LSN), para evitar crise tireotóxica por lise de tireócitos após RAI",
      "Avaliação pré-terapia completa: TSH, T4L, T3L, TRAb (confirmar etiologia de Graves vs outras), anti-TPO, US cervical com Doppler (volume tireoidiano, ecogenicidade, nódulos suspeitos para PAAF), cintilografia de tireoide com captação de 131I ou 99mTc-pertecnetato, captação de 24h (RAIU) para cálculo de atividade",
      "Hipotireoidismo como desfecho esperado e desejado em Graves: 60-80% em 12 meses após dose única; iniciar levotiroxina assim que TSH >10 mUI/L ou sintomático; o paciente deve ser informado pré-tratamento de que hipotireoidismo é o objetivo terapêutico, não uma complicação",
      "Oftalmopatia de Graves (OG): risco de piora pós-RAI de ~15-25% em pacientes com OG leve pré-existente, especialmente tabagistas; corticoterapia profilática com prednisona 0,3-0,5 mg/kg/dia iniciando no dia da RAI por 4-6 semanas com desmame gradual reduz significativamente esse risco; OG ativa moderada-grave é contraindicação relativa para RAI — considerar antitireoidianos ou cirurgia",
      "Bócio volumoso (>60-80 mL): resposta a dose única de RAI pode ser parcial (redução de 30-40% do volume em 12 meses); opções: dose única alta, tratamento seriado, ou pré-tratamento com rhTSH 0,1-0,3 mg IM 24h antes da RAI para aumentar captação homogênea (uso off-label, melhora resposta em BMNT de baixa captação)",
      "RAIU de 24h como preditor de resposta: captação >40% em Graves indica boa resposta; captação <15% em BMNT sugere necessidade de dose maior ou adjuvância com rhTSH; captação pode ser reduzida por ingesta excessiva de iodo, contrastes iodados recentes ou amiodarona",
      "RAI vs cirurgia em BMNT: RAI preferida quando risco cirúrgico elevado, bócio <80 mL e sem nódulos suspeitos para malignidade; cirurgia preferida em bócio muito volumoso (>80-100 mL), nódulos suspeitos a PAAF (Bethesda IV-VI), compressão traqueal grave com desvio, ou bócio mergulhante subesternal extenso",
      "Efeitos colaterais agudos: cervicalgia e edema por tireoidite actínica (5-10%, em 1-2 semanas, autolimitada), náusea transitória, sialadenite rara em doses usadas para doença benigna, tireotoxicose transitória por liberação hormonal (1-2 semanas pós-RAI)",
      "Contracepção pós-RAI: mulheres devem evitar gestação por 6-12 meses; homens por 4 meses; pacientes devem ser informados e orientados antes do tratamento",
      "Seguimento pós-RAI: T4L e TSH em 4-6 semanas, depois mensalmente por 6 meses; maioria dos pacientes torna-se hipotireoideo em 3-6 meses (Graves) ou mantém eutireoidismo com redução de bócio em 6-12 meses (BMNT/AT)"
    ],
    radiopharmaceuticals: "131I-Iodeto de sódio (NaI) em cápsulas gelatinosas ou solução oral, sendo o único agente terapêutico utilizado em doença tireoidiana benigna. Atividades típicas para doença benigna são significativamente menores que para CDT: 185-555 MBq (5-15 mCi) para doença de Graves, 370-800 MBq (10-22 mCi) para BMNT, e 370-740 MBq (10-20 mCi) para adenoma tóxico. O 131I administrado oralmente é rapidamente absorvido pelo trato gastrointestinal e captado pelos tireócitos via simporter sódio-iodo (NIS), concentrando-se no tecido tireoidiano funcionante. A emissão beta do 131I (penetração média 0,4 mm) causa destruição celular localizada por dano ao DNA e apoptose. A meia-vida efetiva na tireoide varia de 4-7 dias, influenciada pelo turnover hormonal e função renal.",
    practicalAspects: "O preparo para RAI em doença benigna inclui avaliação clínica com quantificação de sintomas de tireotoxicose, confirmação laboratorial (TSH suprimido, T4L/T3L elevados), identificação etiológica (TRAb para Graves, cintilografia para BMNT/AT), avaliação de oftalmopatia quando aplicável (Clinical Activity Score, classificação EUGOGO), exclusão de gestação (beta-hCG) e amamentação, US cervical para volumetria e exclusão de nódulos suspeitos, e captação de 131I de 24h (RAIU) para cálculo de atividade. Antitireoidianos são suspensos 3-7 dias antes (metimazol) ou 2-3 semanas (carbimazol). A administração é oral, preferencialmente em jejum de 2-4 horas, em ambiente ambulatorial para atividades <400 MBq (na maioria dos países) ou em internação para atividades maiores. Atividades típicas: 200-400 MBq para Graves (dose ablativa), 400-800 MBq para BMNT. Em países como o Brasil, atividades >1,11 GBq (30 mCi) requerem internação conforme norma CNEN. Pós-administração: orientações de radioproteção escritas (distância de gestantes e crianças por 3-5 dias, descarga dupla, não compartilhar utensílios), hidratação abundante. Corticoterapia profilática quando indicada (OG) é iniciada no D0. Seguimento: consulta em 4-6 semanas com T4L/TSH, depois mensalmente até 6 meses. Hipotireoidismo em Graves: esperar e iniciar levotiroxina quando TSH >10 mUI/L. BMNT/AT: reavaliação de função e volume tireoidiano em 6-12 meses; considerar segunda dose de RAI se resposta insuficiente após 6 meses.",
    limitations: "Contraindicação absoluta na gestação (efeito teratogênico e ablação da tireoide fetal) e amamentação (excreção de 131I no leite materno). Piora de oftalmopatia de Graves em ~15-25% dos pacientes com OG pré-existente, particularmente em tabagistas e pacientes com TRAb muito elevado; corticoterapia profilática mitiga mas não elimina esse risco. BMNT muito volumoso (>80-100 mL) frequentemente requer múltiplas doses de RAI ou tratamento combinado (rhTSH + RAI ou RAI + cirurgia subsequente) com resposta parcial a dose única. Bócio subesternal extenso com compressão traqueal grave pode piorar transitoriamente após RAI por edema actínico, requerendo avaliação individual e manejo em centro com suporte cirúrgico. A captação de 131I pode estar reduzida por ingesta excessiva de iodo, uso recente de contraste iodado (<2-3 meses), suplementos contendo iodo ou amiodarona, necessitando de medição de iodúria para confirmar depleção. O método fixo de cálculo de atividade resulta em taxa de cura variável (50-90% em dose única) comparado ao método calculado (70-95%); porém, o método calculado requer US volumétrica e captação de 24h, não disponíveis em todos os centros. Hipotireoidismo é consequência inevitável do tratamento ablativo em Graves, exigindo reposição hormonal vitalícia e acompanhamento endocrinológico permanente. Pacientes devem ser adequadamente informados de que o tratamento substitui a tireotoxicose pela necessidade de reposição hormonal crônica.",
    reference: "Giovanella L, et al. The EANM guideline on radioiodine therapy of benign thyroid disease. Eur J Nucl Med Mol Imaging. 2023."
  },
  {
    id: "rait-ata-dtc-2025",
    title: "2025 American Thyroid Association Management Guidelines for Adult Patients with Differentiated Thyroid Cancer",
    year: "2025",
    society: "ATA",
    type: "Management guideline",
    badges: ["recent","essential"],
    category: "tireoide",
    categoryName: "Radioiodoterapia",
    categoryColor: "#F472B6",
    scope: "Atualização das recomendações ATA 2015 para manejo de carcinoma diferenciado de tireoide (CDT) em adultos, publicada em 2025. Representa a revisão mais abrangente do tema na última década, incorporando avanços significativos em biologia molecular, estratificação de risco genômica, desintensificação terapêutica em baixo risco e terapias-alvo em doença avançada. O guideline redefine o papel da RAI com base em dados acumulados dos estudos ESTIMABL1, ESTIMABL2, HiLo e IoN, que demonstraram que observação sem RAI é segura em CDT de baixo risco selecionado, e que ablação com atividade baixa (30 mCi) com rhTSH é equivalente a altas atividades com suspensão hormonal. Integra dados de genômica tumoral (mutações BRAF V600E, promotor TERT, fusões RET e NTRK) na estratificação de risco e decisão terapêutica, e consolida o sistema de resposta ao tratamento (excelente, indeterminada, bioquímica incompleta, estrutural incompleta) como ferramenta de reclassificação dinâmica ao longo do seguimento. Posiciona terapias-alvo (inibidores multi-quinase, inibidores seletivos RET e NTRK) no algoritmo de doença iodo-refratária, refletindo a evolução rápida desse campo.",
    indications: [
      "Estratificação de risco pós-operatória atualizada para decisão individualizada sobre RAI: categorias baixo, intermediário e alto risco com integração de dados moleculares e extensão anatômica",
      "Observação ativa (vigilância sem RAI) como opção validada em CDT de baixo risco: microcarcinoma papilífero <1 cm intratireoidiano sem invasão linfovascular, sem linfonodo clínico, sem histologia agressiva, sem mutação BRAF/TERT",
      "Lobectomia como alternativa a tireoidectomia total em tumores 1-4 cm de baixo risco: N0, sem extensão extratireoidiana, sem histologia agressiva; implica em não realizar RAI",
      "Ablação com RAI em risco intermediário: recomendada quando invasão microscópica extratireoidiana, metástase linfonodal N1a limitada (1-5 linfonodos <3 cm), variantes histológicas de risco intermediário",
      "Terapia com RAI em alto risco: extensão extratireoidiana macroscópica (T4), ressecção incompleta R1/R2, N1b extenso, metástases a distância M1 iodo-ávidas",
      "Seguimento por sistema de resposta ao tratamento: reclassificação a cada avaliação, com desintensificação em resposta excelente e intensificação em resposta estrutural incompleta",
      "Manejo de doença iodo-refratária: terapias-alvo moleculares como primeira opção em progressão confirmada (lenvatinibe, sorafenibe) ou terapias seletivas em tumores com alterações druggable (selpercatinibe para RET+, larotrectinibe/entrectinibe para NTRK+)",
      "Dosimetria recomendada para atividades >150 mCi, metástases pulmonares difusas e comprometimento renal"
    ],
    keyPoints: [
      "Revisão da classificação de risco com integração molecular: BRAF V600E isolado reclassificado como risco intermediário (não alto), porém BRAF V600E + mutação no promotor TERT eleva para alto risco pela sinergia prognóstica demonstrada; fusões RET e NTRK identificam tumores potencialmente targetáveis; perfil molecular (ThyroSeq, Afirma) pode reclassificar risco quando histologia é ambígua",
      "Desintensificação em baixo risco: estudos ESTIMABL2 e IoN demonstraram que seguimento sem RAI é seguro em pacientes com CDT papilífero pT1a-pT1b N0 com tireoidectomia total e Tg pós-operatória indetectável; taxa de recorrência <2% em 5 anos sem RAI nesse subgrupo",
      "rhTSH como preparo preferido para ablação e tratamento adjuvante em pacientes sem doença estrutural residual conhecida: equivalência de eficácia demonstrada nos estudos HiLo e ESTIMABL1, com melhor qualidade de vida (evita hipotireoidismo sintomático da suspensão hormonal) e menor tempo de afastamento laboral",
      "Reclassificação dinâmica pelo sistema de resposta ao tratamento: pacientes inicialmente de alto risco que atingem resposta excelente após RAI (Tg estimulada <1 ng/mL, US e imagem negativas) podem ter intensidade de seguimento reduzida; inversamente, pacientes de baixo risco com resposta bioquímica incompleta persistente requerem investigação adicional",
      "Terapias-alvo em CDT iodo-refratário: lenvatinibe (SELECT trial, sobrevida livre de progressão 18,3 vs 3,6 meses) e sorafenibe (DECISION trial, SLP 10,8 vs 5,8 meses) como inibidores multi-quinase de primeira linha; selpercatinibe para tumores com fusão ou mutação RET (LIBRETTO-001, taxa de resposta objetiva >60%); larotrectinibe e entrectinibe para fusões NTRK (taxa de resposta ~75%)",
      "Papel da lobectomia expandido: tumores 1-4 cm de baixo risco podem ser manejados com lobectomia seguida de vigilância, sem RAI e sem supressão de TSH; Tg funciona como marcador de seguimento mas com interpretação diferente (tecido tireoidiano remanescente produz Tg basal); tendência de Tg no tempo é mais informativa que valor absoluto",
      "Dosimetria em cenários específicos: mandatória para atividades >150 mCi, metástases pulmonares micronodulares difusas (limite de retenção pulmonar de 80 mCi em 48h), insuficiência renal (CrCl <60 mL/min, clearance de 131I reduzido) e retratamentos após atividade cumulativa >500 mCi",
      "Vigilância ativa de microcarcinoma papilífero sem cirurgia: opção validada para tumores <1 cm intratireoidiano sem linfonodo suspeito, sem invasão extratireoidiana e sem localização de risco (adjacente a traqueia ou nervo laríngeo recorrente); taxa de crescimento >3 mm em qualquer dimensão desencadeia intervenção",
      "TSH-alvo no seguimento: alto risco com doença persistente: TSH <0,1 mUI/L; alto risco em remissão: 0,1-0,5 mUI/L por 5 anos, depois 0,5-2,0; intermediário em remissão: 0,5-2,0 mUI/L; baixo risco em remissão ou pós-lobectomia: 0,5-2,0 mUI/L (não suprimir)",
      "Papel do PET-FDG atualizado: indicado em Tg >10 ng/mL com US e PCI negativos; em doença pouco diferenciada ou histologias agressivas; para avaliação de potencial refratariedade a iodo; SUVmax >10 em lesão associa-se a pior prognóstico e menor probabilidade de resposta a RAI",
      "Rastreamento familiar: CDT familiar não-medular (2-3 parentes afetados na família) merece aconselhamento genético, embora gene causal não esteja identificado; excluir MEN2 (RET germinativo) em carcinoma medular",
      "Seguimento a longo prazo: US cervical + Tg + anti-Tg a cada 6-12 meses nos primeiros 5 anos; anual após 5 anos; desintensificação para a cada 2-3 anos após 10 anos em resposta excelente mantida; TC de tórax sem contraste anual nos primeiros 3-5 anos em alto risco",
      "Abordagem de metástases a distância: metástases pulmonares micronodulares iodo-ávidas têm excelente prognóstico (sobrevida em 10 anos >90% com RAI repetitivo); metástases ósseas são de pior prognóstico e beneficiam-se de abordagem multimodal (RAI + radioterapia externa + cirurgia ortopédica preventiva); metástases cerebrais raras mas requerem neurocirurgia/radiocirurgia antes de RAI",
      "Conceito de redifferentiation therapy: uso de inibidores de MEK (trametinibe) ou BRAF (dabrafenibe) para restaurar captação de iodo em CDT iodo-refratário BRAF-mutado; dados de fase 2 promissores mas ainda experimentais; pode permitir re-tratamento eficaz com RAI em tumores previamente refratários",
      "Novos biomarcadores moleculares em investigação: DNA tumoral circulante (ctDNA com mutação BRAF ou TERT) como marcador de doença residual mínima; pode complementar ou eventualmente substituir tireoglobulina em pacientes anti-Tg positivos"
    ],
    radiopharmaceuticals: "131I-Iodeto de sódio (NaI) continua como agente terapêutico padrão para CDT iodo-ávido. O guideline ATA 2025 reforça a tendência de utilizar atividades mais baixas em baixo risco (30 mCi / 1,1 GBq para ablação, conforme ESTIMABL1/HiLo) e reservar atividades altas para doença de alto risco e metastática (100-200 mCi / 3,7-7,4 GBq). PET/CT com 18F-FDG é ferramenta complementar fundamental para avaliação de doença iodo-refratária e tumores desdiferenciados. 124I-PET/CT (beta+ emissor, meia-vida 4,18 dias) permite dosimetria pré-terapêutica precisa com resolução PET, disponível em centros acadêmicos especializados. O documento menciona ainda 99mTc-pertecnetato e 123I para cintilografia diagnóstica, e traçadores PSMA-PET como potenciais ferramentas emergentes em CDT desdiferenciado.",
    practicalAspects: "A ATA 2025 enfatiza a personalização como princípio central: não existe abordagem única para todos os pacientes com CDT. A decisão sobre RAI deve integrar estratificação de risco anatômica (TNM/ATA), histopatologia detalhada (variante, grau, invasão linfovascular), dados moleculares quando disponíveis (BRAF, TERT, fusões), níveis pós-operatórios de Tg e anti-Tg, preferência do paciente informado, e expectativa de impacto em desfechos. O fluxo prático pós-cirúrgico inclui: avaliação anatomopatológica completa com perfil molecular (quando disponível e indicado), classificação de risco ATA atualizada, decisão multidisciplinar sobre RAI, preparo (rhTSH preferido em baixo/intermediário sem doença estrutural, suspensão hormonal aceitável), administração, PCI pós-dose com SPECT/CT, e reclassificação pela resposta ao tratamento em 6-12 meses. Para doença iodo-refratária, o guideline recomenda testagem molecular tumoral (BRAF, RET, NTRK, fusões) para seleção de terapia-alvo, discussão em tumor board multimodal, e encaminhamento para centro de referência oncológica quando disponível. O seguimento a longo prazo baseia-se em Tg seriada (basal e estimulada), US cervical de alta resolução, e exames complementares conforme risco e resposta. Desintensificação do seguimento é explicitamente encorajada após 5-10 anos de resposta excelente mantida, alinhando prática com o baixo risco de recorrência tardia nesse subgrupo.",
    limitations: "O guideline reflete predominantemente a realidade e prática norte-americana, e algumas recomendações podem divergir de diretrizes europeias (EANM/ETA) ou latino-americanas, particularmente em relação a indicações de RAI em baixo risco, limites de atividade para tratamento ambulatorial e regulamentação de radioproteção. Dados de biologia molecular (sequenciamento de painel, ThyroSeq, Afirma) podem não estar disponíveis ou não ser financeiramente acessíveis em centros fora dos EUA e Europa Ocidental, limitando a aplicação da estratificação de risco genômica. Terapias-alvo moleculares (lenvatinibe, selpercatinibe, larotrectinibe) têm custo extremamente elevado e acesso restrito em muitos países, incluindo o Brasil. Dados de vigilância ativa sem RAI em baixo risco, embora robustos, provêm de seguimento de 5-10 anos; recorrências tardias (>10 anos) são raras mas documentadas, requerendo seguimento prolongado mesmo após reclassificação como resposta excelente. O conceito de redifferentiation therapy com inibidores de MEK/BRAF é promissor mas experimental, com dados de fase 2 em amostras pequenas e sem confirmação em ensaios randomizados. A dosimetria com 124I-PET/CT, embora precisa, requer produção local de 124I (ciclotron) e não está disponível na maioria dos centros. Anticorpos anti-Tg interferem no ensaio de tireoglobulina em 15-25% dos pacientes com CDT, comprometendo o seguimento bioquímico e exigindo monitoramento por tendência de títulos e imagem funcional.",
    reference: "2025 American Thyroid Association Management Guidelines for Adult Patients with Differentiated Thyroid Cancer. Thyroid. 2025."
  },
'''

with open(target, 'a', encoding='utf-8') as f:
    f.write(content)

print("Batch B written: 6 guidelines (TARE + Tireoide)")
