#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
write_gl_batch_a.py
Generates the opening of guidelines-data.js with 7 deeply expanded guideline objects:
  - 4 PRRT guidelines
  - 3 PSMA guidelines
Run: python write_gl_batch_a.py
"""

import os

target = r"C:\Users\marco\Desktop\TheraTrials Oncology\site\assets\js\guidelines-data.js"

content = r'''window.GUIDELINES_DATA = [
  // ═══════════════════════════════════════════════
  //  1. TNE / PRRT
  // ═══════════════════════════════════════════════
  {
    id: "prrt-eanm-iaea-snmmi-2026",
    title: "Joint EANM, IAEA, and SNMMI practical guidance on somatostatin receptor-targeted radionuclide therapy of neuroendocrine tumours",
    year: "2026",
    society: "EANM · IAEA · SNMMI",
    type: "Practical guidance",
    badges: ["recent","essential"],
    category: "prrt",
    categoryName: "TNE / PRRT",
    categoryColor: "#34D399",
    scope: "Documento multissociedade que representa a mais abrangente e atualizada orientacao pratica sobre PRRT com analogos de somatostatina radiomarcados em tumores neuroendocrinos. Incorpora toda a evidencia acumulada dos estudos pivotais NETTER-1 (177Lu-DOTATATE vs octreotide LAR 60 mg em TNE de intestino medio), NETTER-2 (primeira linha em TNE G2-G3 de alto grau), COMPETE (177Lu-Edotreotide vs Everolimus) e series institucionais maduras com seguimento superior a 10 anos. Substitui e expande significativamente o guidance de 2013, refletindo a evolucao regulatoria (aprovacao do Lutathera em 2018), a incorporacao de PET/CT com 68Ga-DOTATATE como padrao de selecao, e a crescente importancia da dosimetria individualizada. Posiciona a PRRT no contexto terapeutico atual, incluindo discussao sobre sequenciamento com terapias-alvo (everolimus, sunitinib), quimioterapia (CAPTEM) e o papel emergente de novos radionuclideos como 225Ac-DOTATATE. Oferece recomendacoes graduadas conforme nivel de evidencia e consenso dos tres orgaos.",
    indications: [
      "TNE gastroenteropancreaticos bem diferenciados (G1-G2, Ki-67 ate 20%) progressivos sob analogo de somatostatina em dose otimizada por pelo menos 3-6 meses",
      "TNE G3 (Ki-67 20-55%) com captacao SSTR preservada em PET/CT com 68Ga-DOTATATE, conforme dados do NETTER-2 e series retrospectivas",
      "TNE bronquicos atipicos (carcinoides atipicos) com expressao SSTR confirmada por PET e progressao documentada",
      "Retratamento (re-PRRT) apos resposta inicial (parcial ou completa) e progressao tardia (intervalo livre de progressao superior a 18 meses), com funcao renal e medular preservadas",
      "Cenarios de primeira linha em TNE de alto volume tumoral, sintomaticos ou com progressao rapida, conforme evidencia do NETTER-2",
      "Feocromocitoma/paraganglioma SSTR-positivo como alternativa a 131I-MIBG quando captacao SSTR excede captacao MIBG",
      "Carcinoma medular de tireoide SSTR-positivo em contexto de pesquisa ou uso compassivo",
      "TNE de origem primaria desconhecida (CUP) com captacao SSTR demonstrada em PET/CT",
      "TNE de intestino medio com sindrome carcinoide refrataria a terapia com octreotide/lanreotide em dose maxima",
      "TNE pancreaticos funcionantes (insulinoma maligno, glucagonoma, VIPoma) com doenca metastatica irressecavel SSTR-positiva"
    ],
    keyPoints: [
      "Criterios de elegibilidade atualizados: captacao tumoral em PET/CT com 68Ga-DOTATATE superior a captacao hepatica normal (score de Krenning modificado para PET >= 3) em todas as lesoes-indice; lesoes PET-negativas maiores que 1 cm devem ser avaliadas com 18F-FDG para excluir desdiferenciacao",
      "Esquema posologico padrao: 7,4 GBq (200 mCi) de 177Lu-DOTATATE IV por ciclo, total de 4 ciclos com intervalo de 8 semanas (variacao aceitavel de 6-12 semanas conforme recuperacao hematologica)",
      "Dosimetria individualizada recomendada como ferramenta complementar: limite cumulativo renal de 23 Gy (ajustado para 18-20 Gy em pacientes com fatores de risco como diabetes, hipertensao ou nefropatia previa) e limite de corpo inteiro de 2 Gy para seguranca medular",
      "Evidencia do NETTER-1: PFS mediana de 28,4 meses vs 8,5 meses com octreotide LAR 60 mg (HR 0,21); beneficio de OS confirmado em analise final com HR 0,84",
      "Evidencia do NETTER-2: em TNE G2-G3 de primeira linha, 177Lu-DOTATATE associado a octreotide de longa duracao versus octreotide isolado demonstrou PFS mediana de 22,8 vs 8,5 meses (HR 0,27)",
      "Protocolo de nefroproteao com aminoacidos: solucao de lisina 25 g + arginina 25 g em 1-2 L de solucao fisiologica, infusao iniciada 30 minutos antes da PRRT e mantida por 4 horas; alternativas comerciais (Argininlysine) disponiveis em alguns paises",
      "Monitoramento pre-ciclo obrigatorio: hemograma completo (neutrofilos >= 1.500/mm3, plaquetas >= 75.000/mm3, Hb >= 8 g/dL), creatinina serica, clearance de creatinina ou TFG estimada (>= 50 mL/min), bilirrubina total e albumina",
      "SPECT/CT pos-dose em 24h recomendado para todos os ciclos: verificacao de biodistribuicao tumoral, deteccao de deposicao nao-alvo e calculo dosimetrico simplificado (single-timepoint method)",
      "Criterios de suspensao: toxicidade hematologica grau 3-4 persistente (mais de 12 semanas), nefrotoxicidade com queda de TFG superior a 40% do basal, progressao tumoral confirmada por RECIST 1.1 ou criterios SSTR-PET",
      "Re-PRRT: intervalo minimo recomendado de 12-18 meses apos ultimo ciclo; re-elegibilidade requer captacao SSTR preservada, funcao renal e medular adequadas, e dose cumulativa renal abaixo de 23 Gy (idealmente monitorada por dosimetria)",
      "Manejo de toxicidade hematologica tardia: monitorar hemograma a cada 4-6 semanas nos primeiros 3 meses pos-PRRT, depois trimestral por 2 anos; risco de SMD/LMA estimado em 1-2% com dados de seguimento superior a 5 anos",
      "Avaliacao de resposta: PET/CT com 68Ga-DOTATATE + TC com contraste (ou RM) em 3-6 meses apos completar 4 ciclos; criterios RECIST 1.1 para avaliacao anatomica, criterios moleculares (reducao de captacao SSTR) como complemento",
      "Integracao com terapias sistemicas: manter octreotide/lanreotide de longa duracao durante PRRT para controle sintomatico; sequenciamento com everolimus ou sunitinib apos PRRT com base em progressao e perfil de toxicidade",
      "Cuidados com radiacao: taxa de dose a 1 metro medida antes da alta; orientacoes escritas ao paciente sobre distancia de gestantes e criancas (tipicamente 3-5 dias para 177Lu); manejo de residuos radioativos conforme norma local",
      "Consideracoes sobre novos radionuclideos: 225Ac-DOTATATE em investigacao para TNE refratarios a 177Lu, com perfil de alfa-emissor (maior LET); dados preliminares promissores porem sem ensaios fase 3 publicados",
      "Manejo da sindrome carcinoide peri-PRRT: octreotide subcutaneo de resgate (100-500 mcg) disponivel para crises carcinoides durante ou apos infusao; risco aumentado em pacientes com alta carga tumoral hepatica"
    ],
    radiopharmaceuticals: "O radiofarmaco padrao e o 177Lu-DOTATATE (Lutathera, oxodotreotide marcado com 177Lu), aprovado pela FDA em 2018 e EMA em 2017, com atividade de 7,4 GBq (200 mCi) por ciclo. O 177Lu-DOTATOC e o 177Lu-Edotreotide (investigacional, usado no estudo COMPETE) sao alternativas com afinidade ligeiramente diferente pelos subtipos de receptores SSTR. O 177Lu decai por emissao beta (Emax 497 keV, alcance maximo 2 mm em tecido) com emissao gama concomitante (113 e 208 keV) que permite imageamento SPECT pos-dose. Meia-vida fisica de 6,65 dias. O 90Y-DOTATOC foi historicamente utilizado em centros europeus, com maior alcance beta (Emax 2,28 MeV, 11 mm) e ausencia de emissao gama imagenologica direta (monitorado por PET via bremsstrahlung ou aniquilacao de pares internos). Preparacao do Lutathera: reconstituicao conforme bula do fabricante, controle de qualidade com pureza radioquimica superior a 95% por HPLC ou TLC.",
    practicalAspects: "O fluxo terapeutico inicia com avaliacao multidisciplinar (oncologista, endocrinologista e medico nuclear) incluindo confirmacao histologica do TNE, grau tumoral (Ki-67) e estadiamento com PET/CT com 68Ga-DOTATATE realizado dentro de 8-12 semanas antes do primeiro ciclo. A avaliacao laboratorial pre-tratamento inclui hemograma completo, creatinina serica com calculo de TFG (valor minimo de 50 mL/min/1,73m2), bilirrubina total (valor maximo de 3x limite superior da normalidade), albumina, cromogranina A serica e 5-HIAA urinario de 24h (quando indicado). O paciente deve suspender octreotide LAR 4-6 semanas antes do PET de selecao e do primeiro ciclo; lanreotide deve ser suspenso por 4 semanas; octreotide subcutaneo pode ser mantido ate 24h antes. No dia do tratamento, o paciente chega em jejum de 4h; um acesso venoso periferico calibroso (18-20G) e obtido e inicia-se pre-medicacao com ondansetrona 8 mg IV e dexametasona 8 mg IV para prevencao de nausea (os aminoacidos sao altamente emetogenicos). A infusao de aminoacidos (lisina 25 g + arginina 25 g em 1-2 L de solucao fisiologica) e iniciada 30 minutos antes da PRRT e mantida a 250-500 mL/h por 4 horas. O 177Lu-DOTATATE e administrado por bomba peristaltica ou por gravidade em 20-30 minutos, com monitoramento de sinais vitais a cada 15 minutos durante a infusao. Apos a infusao, o paciente permanece em observacao por 1-4 horas conforme protocolo institucional e regulacao local de radioprotecao. A imagem SPECT/CT pos-dose e realizada preferencialmente em 24h (janela aceitavel de 4-24h para primeiro timepoint) com protocolo dedicado para 177Lu (fotopico 208 keV, colimador de media energia). O paciente recebe orientacoes escritas de radioprotecao domiciliar: manter distancia de pelo menos 1 metro de gestantes e criancas por 3-7 dias, evitar compartilhar cama por 3 noites, lavar roupas separadamente, higiene adequada de banheiro. O seguimento entre ciclos inclui hemograma completo a cada 2-4 semanas, funcao renal a cada ciclo, e avaliacao clinica de toxicidade e sintomas. Apos completar 4 ciclos, reestadiamento completo com PET/CT com 68Ga-DOTATATE e TC/RM em 3-6 meses para avaliacao de resposta.",
    limitations: "A PRRT depende fundamentalmente da expressao de receptores de somatostatina demonstrada por PET/CT com 68Ga-DOTATATE; pacientes com tumores SSTR-negativos (como TNE pouco diferenciados com Ki-67 acima de 55% ou NEC) sao excluidos e devem ser direcionados para quimioterapia baseada em platina. A mielotoxicidade e cumulativa e representa o principal fator limitante para o numero de ciclos e retratamentos, com risco de 1-2% de sindromes mielodisplasicas ou leucemia aguda em seguimento de longo prazo. A nefrotoxicidade e rara (incidencia inferior a 2%) quando a nefroproteao com aminoacidos e realizada adequadamente, mas monitoramento seriado de funcao renal e mandatorio, especialmente em diabeticos e hipertensos. A sindrome carcinoide pode ser exacerbada durante a infusao em pacientes com alta carga tumoral hepatica, requerendo octreotide de resgate. Nao existem dados comparativos diretos entre PRRT e quimioterapia (CAPTEM) em TNE pancreaticos, e o sequenciamento otimo entre estas modalidades permanece uma lacuna de evidencia. A dosimetria personalizada, embora recomendada, nao esta amplamente disponivel em todos os centros, e muitos ainda utilizam atividades fixas. O acesso ao 177Lu-DOTATATE permanece limitado em paises de baixa e media renda devido a custo, logistica de transporte e infraestrutura de radioprotecao. Estudos em andamento avaliam a combinacao de PRRT com inibidores de checkpoint imunologico e com alfa-emissores (225Ac-DOTATATE) para tumores refratarios a beta-terapia.",
    reference: "Joint EANM, IAEA, and SNMMI practical guidance on somatostatin receptor-targeted radionuclide therapy of neuroendocrine tumours. Eur J Nucl Med Mol Imaging. 2026."
  },
  {
    id: "prrt-iaea-eanm-snmmi-2013",
    title: "The joint IAEA, EANM, and SNMMI practical guidance on peptide receptor radionuclide therapy in neuroendocrine tumours",
    year: "2013",
    society: "IAEA · EANM · SNMMI",
    type: "Practical guidance",
    badges: [],
    category: "prrt",
    categoryName: "TNE / PRRT",
    categoryColor: "#34D399",
    scope: "Documento fundacional da era moderna de PRRT, publicado antes da aprovacao regulatoria do Lutathera, que estabeleceu os padroes praticos para administracao de analogos de somatostatina radiomarcados em tumores neuroendocrinos. Baseou-se predominantemente em dados retrospectivos de centros europeus pioneiros (Basileia, Roterdao, Bad Berka, Bolonha) com experiencia acumulada em mais de 5.000 pacientes tratados com 90Y-DOTATOC e 177Lu-DOTATATE. Este guidance definiu os fundamentos de selecao de pacientes, nefroproteao com aminoacidos, limites de dose cumulativa e protocolos de monitoramento que permanecem relevantes e foram incorporados nas recomendacoes subsequentes. Representa o consenso pre-NETTER-1 e pre-era PET com 68Ga, quando a selecao ainda era baseada predominantemente em cintilografia com 111In-Octreoscan.",
    indications: [
      "TNE gastroenteropancreaticos inoperaveis ou metastaticos com captacao SSTR positiva demonstrada por 111In-Octreoscan (Krenning >= 2) ou PET/CT com 68Ga-DOTATATE",
      "Progressao tumoral documentada por metodos de imagem sob terapia com analogo de somatostatina em dose maxima por pelo menos 6 meses",
      "Tumores carcinoides secretores com sindrome carcinoide refrataria a octreotide/lanreotide em dose otimizada",
      "Feocromocitoma e paraganglioma irressecaveis com expressao SSTR demonstrada",
      "TNE bronquicos com captacao SSTR positiva apos falha de terapias sistemicas convencionais",
      "Carcinoma medular de tireoide SSTR-positivo em casos selecionados",
      "TNE timicos com captacao SSTR confirmada",
      "Criterios laboratoriais minimos: hemoglobina >= 8 g/dL, leucocitos >= 2.000/mm3, plaquetas >= 75.000/mm3, creatinina serica dentro de 1,5x limite superior da normalidade"
    ],
    keyPoints: [
      "Criterios de selecao baseados em cintilografia com 111In-Octreoscan: escala de Krenning >= 2 (captacao tumoral igual ou superior a captacao hepatica); este foi o padrao ate a disseminacao do PET com 68Ga-DOTATATE que oferece sensibilidade e resolucao superiores",
      "Esquema posologico para 177Lu-DOTATATE: 7,4 GBq (200 mCi) por ciclo, 4 ciclos com intervalo de 6-10 semanas; atividade cumulativa maxima sugerida de 29,6 GBq (800 mCi)",
      "Esquema posologico para 90Y-DOTATOC: 3,7 GBq/m2 (100 mCi/m2) por ciclo, 3-5 ciclos; maior potencia beta mas maior nefrotoxicidade comparado ao 177Lu",
      "Protocolo de nefroproteao com aminoacidos detalhado: infusao de lisina (25 g) e arginina (25 g) diluidos em 1 L de solucao fisiologica, iniciada 30 min antes do radiofarmaco, mantida por 4h; reducao de dose renal em 20-50%",
      "Limites de dose cumulativa: 23 Gy para rins (BED, considerando fator de reparacao alfa/beta = 2,6 Gy), 2 Gy para medula ossea (dose a corpo inteiro como proxy); ajuste para fatores de risco renais (diabetes, hipertensao)",
      "Recomendacoes de radioproteao e isolamento: quarto dedicado com monitoramento de taxa de dose, criterios de liberacao baseados em atividade residual e taxa de dose a 1 metro, orientacoes domiciliares escritas",
      "Monitoramento laboratorial pre e pos-PRRT: hemograma completo a cada 4-6 semanas, creatinina serica e clearance de creatinina a cada ciclo, cromogranina A serica como marcador tumoral, provas de funcao hepatica",
      "Efeitos adversos documentados: nausea e vomito (relacionados aos aminoacidos, em 25-30%), fadiga transitoria (em 30-40%), toxicidade hematologica grau 3-4 (em 3-10%), nefrotoxicidade clinicamente significativa (inferior a 5% com nefroproteao adequada)",
      "Discussao sobre dosimetria: modelo MIRD com imagens planares e SPECT/CT seriadas; reconhecimento de que a maioria dos centros utilizava atividades fixas por limitacoes praticas",
      "Avaliacao de resposta: TC ou RM a cada 3-6 meses; cintilografia SSTR para avaliacao funcional; cromogranina A como marcador bioquimico de acompanhamento",
      "Contraindicacoes absolutas: gestacao, lactacao, expectativa de vida inferior a 3 meses, insuficiencia renal grave (clearance inferior a 30 mL/min), mielossupressao grave nao recuperada",
      "Contraindicacoes relativas: metastases cerebrais com risco de edema, insuficiencia hepatica grave, performance status ECOG >= 4",
      "Este documento representou o primeiro consenso formal entre tres sociedades internacionais sobre PRRT, harmonizando praticas que eram heterogeneas entre centros academicos europeus e estabelecendo a base para os ensaios clinicos que se seguiram"
    ],
    radiopharmaceuticals: "Os principais radiofarmacos cobertos sao 177Lu-DOTATATE (peptideo Tyr3-octreotate marcado com 177Lu, que se tornou o padrao apos aprovacao como Lutathera) e 90Y-DOTATOC (peptideo Tyr3-octreotide marcado com 90Y, utilizado extensivamente em centros europeus). O 177Lu possui meia-vida de 6,65 dias, emissao beta com Emax de 497 keV (alcance maximo de 2 mm em tecido) e emissao gama de 113 e 208 keV adequada para imageamento SPECT. O 90Y possui meia-vida de 2,67 dias, emissao beta pura com Emax de 2,28 MeV (alcance maximo de 11 mm), sem emissao gama direta (monitorado por bremsstrahlung SPECT ou PET com resolucao limitada). O 111In-Octreotide era utilizado como agente diagnostico (Octreoscan) para selecao de pacientes, com captacao avaliada pela escala de Krenning.",
    practicalAspects: "A avaliacao pre-terapia inicia com confirmacao histologica do TNE, estadiamento com cintilografia SSTR (Octreoscan ou PET/CT com 68Ga-DOTATATE quando disponivel), TC ou RM para avaliacao anatomica de referencia, e avaliacao laboratorial completa incluindo hemograma (plaquetas >= 75.000/mm3, Hb >= 8 g/dL, neutrofilos >= 1.500/mm3), funcao renal (clearance de creatinina >= 50 mL/min, preferencialmente por coleta de urina de 24h ou DTPA), funcao hepatica (bilirrubina, albumina, transaminases), e marcadores tumorais (cromogranina A, 5-HIAA urinario 24h quando indicado). A descontinuacao de octreotide LAR e recomendada por 4-6 semanas antes do exame de selecao e antes de cada ciclo de PRRT; octreotide subcutaneo deve ser suspenso por 24h. No dia do tratamento, acesso venoso periferico de bom calibre, pre-medicacao com antiemeticos (ondansetrona 8 mg IV) e dexametasona 4-8 mg IV. A infusao de aminoacidos e iniciada 30 min antes da PRRT e mantida por 4h. O radiofarmaco e administrado em 20-30 min IV por bomba peristaltica ou gravidade. Monitoramento de sinais vitais durante e apos a infusao. Cintilografia pos-dose (corpo inteiro planar e SPECT/CT) em 24h para verificacao de captacao tumoral e dosimetria. Hidratacao oral e venosa adequada no dia do tratamento e nas 24h seguintes. Criterios de alta conforme regulamentacao local de radioprotecao. Seguimento ambulatorial com hemograma a cada 4-6 semanas e funcao renal a cada ciclo.",
    limitations: "Este documento foi publicado antes da era PET com 68Ga-DOTATATE como padrao de selecao, e seus criterios de elegibilidade baseados em Octreoscan (111In) apresentam menor sensibilidade (70-80% vs 95% do PET), podendo subestimar a carga tumoral e identificar incorretamente pacientes como SSTR-negativos. Os dados de eficacia disponiveis na epoca eram majoritariamente retrospectivos, de centros unicos e com heterogeneidade significativa de populacao e protocolo, antes da publicacao dos resultados do NETTER-1 em 2017. O cenario de primeira linha nao era abordado, pois toda a experiencia era em pacientes pre-tratados com progressao documentada. A dosimetria individualizada era mencionada como desejavel mas nao amplamente implementada, e a maioria dos centros utilizava atividades fixas por questoes praticas. O papel do 90Y-DOTATOC vs 177Lu-DOTATATE nao era completamente esclarecido, com preferencia institucional guiando a escolha. A mielotoxicidade de longo prazo (risco de SMD/LMA) nao era completamente caracterizada por insuficiencia de seguimento maduro. Apesar destas limitacoes, este documento permanece como referencia historica fundamental e seus principios basicos (nefroproteao, limites de dose, selecao por captacao SSTR) foram validados por toda a evidencia subsequente.",
    reference: "Zaknun JJ, et al. The joint IAEA, EANM, and SNMMI practical guidance on peptide receptor radionuclide therapy (PRRNT) in neuroendocrine tumours. Eur J Nucl Med Mol Imaging. 2013;40(5):800-816."
  },
  {
    id: "prrt-nanets-snmmi-dotatate",
    title: "NANETS/SNMMI Procedure Guidelines for Somatostatin Receptor-Based Peptide Receptor Radionuclide Therapy with 177Lu-DOTATATE",
    year: null,
    society: "NANETS · SNMMI",
    type: "Procedure guideline",
    badges: ["essential"],
    category: "prrt",
    categoryName: "TNE / PRRT",
    categoryColor: "#34D399",
    scope: "Guideline procedimental norte-americano focado especificamente no uso do 177Lu-DOTATATE (Lutathera) aprovado pela FDA, com enfase no fluxo operacional completo desde a selecao ate o seguimento de longo prazo. Publicado apos a aprovacao regulatoria, reflete a pratica clinica pos-NETTER-1 e serve como referencia para centros americanos e canadenses que implementaram programas de PRRT. Diferencia-se dos guidelines europeus por maior enfase nos aspectos regulatorios do FDA, requisitos de REMS (Risk Evaluation and Mitigation Strategy) e aspectos praticos de administracao conforme bula aprovada. Inclui discussao sobre retratamento (re-PRRT), dosimetria simplificada e integracao com guidelines de imagem SSTR-PET da SNMMI.",
    indications: [
      "TNE gastroenteropancreaticos bem diferenciados (G1-G2) SSTR-positivos em adultos, conforme indicacao aprovada pela FDA e EMA",
      "Progressao tumoral documentada por criterios RECIST 1.1 apos terapia com analogo de somatostatina em dose otimizada",
      "Captacao SSTR positiva confirmada em PET/CT com 68Ga-DOTATATE (NETSPOT ou Detectnet): captacao tumoral superior a captacao hepatica normal em pelo menos uma lesao-indice",
      "Criterios laboratoriais conforme bula: TFG >= 30 mL/min (ajustada), hemoglobina >= 8 g/dL, leucocitos >= 2.000/mm3, plaquetas >= 75.000/mm3",
      "Indicacao expandida para TNE de alto grau (G2-G3 com Ki-67 10-55%) com captacao SSTR preservada, conforme resultados do NETTER-2",
      "TNE de intestino medio (jejuno, ileo, apendice, ceco) como principal indicacao baseada no NETTER-1",
      "TNE pancreaticos SSTR-positivos com progressao documentada",
      "TNE bronquicos com captacao SSTR confirmada (uso off-label da indicacao FDA, aceito por NANETS)",
      "Retratamento apos resposta inicial documentada (minimo resposta parcial ou doenca estavel superior a 12 meses) e nova progressao tardia"
    ],
    keyPoints: [
      "Protocolo de selecao por SSTR-PET conforme standard SNMMI: captacao tumoral em pelo menos uma lesao superior a captacao hepatica; ausencia de lesoes significativas SSTR-negativas em FDG-PET (quando indicado) ou TC que possam indicar desdiferenciacao",
      "Atividade padronizada conforme bula aprovada: 7,4 GBq (200 mCi) de 177Lu-DOTATATE IV por ciclo, tolerancia de +/- 10%, total de 4 ciclos administrados a cada 8 semanas (+/- 2 semanas)",
      "Protocolo de aminoacidos conforme bula: solucao contendo lisina 25 g e arginina 25 g (ou solucao comercial equivalente), inicio 30 min antes da infusao do radiofarmaco, infusao continua por 4 horas, com antiemeticos profilaticos obrigatorios (ondansetrona 8 mg IV 30 min antes dos aminoacidos)",
      "Criterios de retratamento apos resposta e nova progressao: re-PET SSTR para confirmar manutencao de captacao, reavaliar funcao renal (TFG >= 50 mL/min ideal para re-PRRT), hemograma adequado, intervalo minimo de 12-18 meses desde ultimo ciclo",
      "Dosimetria simplificada vs personalizada: dosimetria completa (SPECT/CT em multiplos timepoints) recomendada quando disponivel; dosimetria simplificada (single-timepoint a 24h) aceitavel como alternativa pratica; dose de atividade fixa conforme bula permanece padrao regulatorio",
      "Manejo de nausea e vomito: aminoacidos sao a principal causa (incidencia 60-70%); ondansetrona 8 mg IV pre-infusao obrigatoria; considerar dexametasona 8 mg IV como adjuvante; doses adicionais de antiemeticos conforme necessidade",
      "Criterios de suspensao de tratamento: toxicidade hematologica grau 3 persistente por mais de 8 semanas (especialmente trombocitopenia), nefrotoxicidade com queda de TFG superior a 40% do basal, progressao tumoral confirmada durante terapia (RECIST 1.1), toxicidade hepatica grave (grau 3-4)",
      "Manejo de fadiga pos-PRRT: ocorre em 30-40% dos pacientes, tipicamente auto-limitada em 1-2 semanas; orientar sobre expectativas e medidas de suporte",
      "Imagem pos-dose: SPECT/CT em 24h pos-administracao recomendado para todos os ciclos; avaliacao de biodistribuicao tumoral, captacao renal, captacao gastrintestinal fisiologica e deteccao de possivel extravasamento no sitio de infusao",
      "Medicacoes concomitantes: octreotide/lanreotide de longa duracao deve ser suspenso 4-6 semanas antes de cada ciclo; octreotide subcutaneo de resgate pode ser utilizado ate 24h antes; outras terapias sistemicas (everolimus, sunitinib) podem ser combinadas em contexto de pesquisa",
      "Seguimento de longo prazo: hemograma completo a cada 4 semanas nos primeiros 3 meses apos cada ciclo, depois trimestral por 2 anos; funcao renal a cada 3 meses por 1 ano, depois semestral; avaliacao de resposta com PET/CT e TC/RM em 3-6 meses apos 4o ciclo",
      "Aspectos regulatorios FDA/REMS: Lutathera possui REMS com elementos para garantir uso seguro; centros devem estar certificados; profissionais devem completar treinamento especifico; documentacao de consentimento informado padronizada",
      "Populacoes especiais: cautela em pacientes com metastases osseas difusas (maior risco de mielotoxicidade), insuficiencia hepatica moderada (ajustar monitorizacao), idosos (sem ajuste de dose mas monitoramento mais frequente)",
      "Biomarcadores de resposta: PSA nao aplicavel; cromogranina A util mas inespecifica; 5-HIAA urinario em tumores carcinoides secretores; NSE (enolase neuronio-especifica) pode elevar-se em desdiferenciacao",
      "Documentacao do tratamento: registro de atividade administrada, horarios de infusao, taxa de dose na liberacao, eventuais intercorrencias, resultados da imagem pos-dose"
    ],
    radiopharmaceuticals: "O 177Lu-DOTATATE (Lutathera, nome generico: lutetium Lu 177 dotatate, nome quimico: oxodotreotide marcado com 177Lu) e o unico radiofarmaco para PRRT com aprovacao regulatoria completa pela FDA e EMA. A formulacao comercial e fornecida em dose unica pronta para uso de 7,4 GBq (200 mCi) em 25 mL de solucao, com prazo de validade definido pela data de calibracao. A atividade especifica minima e definida pelo fabricante para garantir concentracao peptidica adequada. O controle de qualidade pre-administracao inclui verificacao de atividade no calibrador de dose (variacao aceitavel de +/- 10%), inspecao visual para particulas e coloracao, e registro do numero de lote. A meia-vida fisica do 177Lu e de 6,65 dias, com emissao beta (Emax 497 keV) e gama (113 e 208 keV).",
    practicalAspects: "O fluxo operacional completo inicia com encaminhamento por oncologista ou endocrinologista, seguido de consulta pre-PRRT com medico nuclear para avaliacao de elegibilidade. O PET/CT com 68Ga-DOTATATE deve ser realizado dentro de 12 semanas antes do primeiro ciclo e interpretado conforme criterios SNMMI (captacao tumoral vs hepatica). A avaliacao laboratorial pre-tratamento inclui hemograma completo com diferencial, perfil metabolico completo (creatinina, ureia, TFG calculada, eletrolitos, bilirrubina, transaminases, albumina), cromogranina A e 5-HIAA urinario 24h quando aplicavel. O octreotide/lanreotide LAR deve ser suspenso 4-6 semanas antes do primeiro ciclo. No dia do tratamento, o paciente chega em jejum de 4 horas. Acesso venoso periferico 18-20G e obtido, preferencialmente em membro superior. Pre-medicacao: ondansetrona 8 mg IV 30 min antes dos aminoacidos, dexametasona 8 mg IV opcional. Infusao de aminoacidos (lisina 25 g + arginina 25 g em 1 L de solucao fisiologica) iniciada 30 min antes do radiofarmaco, mantida a 250 mL/h por 4 horas. O Lutathera e administrado por bomba peristaltica (metodo preferido) ou por gravidade em 20-30 minutos, com flush de 100 mL de solucao fisiologica apos infusao. Monitoramento de sinais vitais a cada 15 min durante infusao e a cada 30 min por 2 horas apos. A imagem SPECT/CT pos-dose e realizada em 24h (+/- 4h) com protocolo dedicado para 177Lu: fotopico de 208 keV (+/- 20%), colimador de media energia geral (MEGP), 60 projecoes de 30 segundos, matriz 128x128, reconstrucao iterativa OSEM com correcao de atenuacao por TC. Criterios de alta: taxa de dose a 1 metro inferior a 25 microSv/h (variavel conforme regulacao local), orientacoes escritas de radioprotecao entregues ao paciente. Acompanhamento: hemograma a cada 2-4 semanas nos primeiros 3 meses, funcao renal a cada ciclo, consulta medica antes de cada ciclo subsequente para avaliacao clinica e laboratorial.",
    limitations: "Este guideline e focado exclusivamente na formulacao comercial aprovada Lutathera (177Lu-DOTATATE) e nao aborda diretamente o uso de compostos academicos (177Lu-DOTATOC, 177Lu-PSMA-I&T ou outros peptideos experimentais) que podem ter perfis farmacocineticos e de seguranca ligeiramente diferentes. A cobertura do cenario de primeira linha era limitada na publicacao original, antes dos dados do NETTER-2 demonstrarem beneficio neste contexto. A dosimetria personalizada e mencionada como opcional, refletindo a realidade norte-americana onde a maioria dos centros utiliza atividade fixa conforme bula. O documento nao aborda extensivamente a combinacao de PRRT com outras terapias sistemicas (CAPTEM, imunoterapia), que e area de intensa investigacao. A populacao de TNE G3 com captacao SSTR preservada era considerada off-label na epoca, mas dados subsequentes (NETTER-2) expandiram esta indicacao. O retratamento (re-PRRT) e discutido de forma geral sem criterios rigidos validados prospectivamente. A questao do sequenciamento otimo entre PRRT, everolimus, sunitinib e quimioterapia permanece nao resolvida por ausencia de estudos comparativos diretos.",
    reference: "NANETS/SNMMI Procedure Guidelines for Somatostatin Receptor-Based Peptide Receptor Radionuclide Therapy with 177Lu-DOTATATE. J Nucl Med / Pancreas."
  },
  {
    id: "prrt-sstr-pet-imaging-2023",
    title: "SNMMI Procedure Standard/EANM Practice Guideline for SSTR PET: Imaging Neuroendocrine Tumors",
    year: "2023",
    society: "SNMMI · EANM",
    type: "Procedure standard / Practice guideline",
    badges: ["imaging"],
    category: "prrt",
    categoryName: "TNE / PRRT",
    categoryColor: "#34D399",
    scope: "Documento central e definitivo para padronizacao de PET/CT com radiotracadores direcionados a receptores de somatostatina (SSTR-PET) na avaliacao de tumores neuroendocrinos e tumores que expressam SSTR. Substitui as orientacoes anteriores baseadas em cintilografia com Octreoscan (111In) e estabelece o PET/CT com 68Ga-DOTATATE como padrao-ouro para deteccao, estadiamento, selecao para PRRT e monitoramento de TNE. Abrange os tres radiotracadores aprovados (68Ga-DOTATATE, 68Ga-DOTATOC e 64Cu-DOTATATE), seus protocolos de aquisicao especificos, criterios de interpretacao padronizados e armadilhas diagnosticas. Incorpora evidencia de estudos prospectivos multicenetricos que demonstraram superioridade do SSTR-PET sobre Octreoscan em sensibilidade (95% vs 70%), especificidade e impacto no manejo clinico, com mudanca de conduta em 30-40% dos casos.",
    indications: [
      "Estadiamento inicial de TNE confirmados histologicamente (G1, G2 e G3 selecionados) para determinacao de extensao de doenca e elegibilidade a terapias sistemicas ou locorregionais",
      "Reestadiamento de TNE com suspeita de progressao clinica, bioquimica (elevacao de cromogranina A ou 5-HIAA) ou radiologica",
      "Avaliacao de elegibilidade para PRRT: demonstracao de captacao SSTR tumoral superior a captacao hepatica normal como pre-requisito para 177Lu-DOTATATE",
      "Localizacao de tumor primario oculto em pacientes com sindrome carcinoide ou sindrome hormonal confirmada bioquimicamente e sem lesao identificavel em TC/RM",
      "Monitoramento de resposta pos-PRRT: avaliacao de mudancas na captacao SSTR entre ciclos ou apos completar tratamento",
      "Avaliacao de meningioma SSTR-positivo para planejamento de radioterapia e monitoramento",
      "Avaliacao de paraganglioma e feocromocitoma, especialmente quando 123I-MIBG e negativo ou inconclusivo",
      "Deteccao de tumor neuroendocrino em biopsia de sitio metastatico com primario desconhecido",
      "Avaliacao de TNE timico e TNE pulmonar para estadiamento e selecao terapeutica",
      "Complemento ao 18F-FDG PET/CT na abordagem dual-tracer (SSTR + FDG) para avaliacao de heterogeneidade tumoral e prognistico (NETPET score)"
    ],
    keyPoints: [
      "Protocolos de aquisicao por radiotracador: 68Ga-DOTATATE: 100-200 MBq IV, aquisicao em 60 min (+/- 10 min); 68Ga-DOTATOC: 100-200 MBq IV, aquisicao em 60 min; 64Cu-DOTATATE: 148 MBq IV, aquisicao em 60-90 min (meia-vida de 12,7h permite logistica flexivel e imagem tardia)",
      "Parametros de reconstrucao PET recomendados: algoritmo iterativo OSEM (2-3 iteracoes, 8-16 subsets), matriz 256x256, filtro gaussiano 3-5 mm, correcao de atenuacao por TC, correcao de scatter e randoms; calibracao SUV obrigatoria com phantom padronizado",
      "Escala de captacao modificada de Krenning para PET (SSTR-RADS-like): grau 1 = captacao inferior a hepatica normal, grau 2 = captacao igual a hepatica, grau 3 = captacao superior a hepatica, grau 4 = captacao superior a esplenica ou renal; graus 3-4 considerados positivos para elegibilidade a PRRT",
      "Armadilhas diagnosticas - captacao fisiologica que pode simular doenca: processo uncinado do pancreas (captacao difusa, nao focal), adrenal (captacao bilateral simetrica), hipofise (captacao leve), corpo vertebral (pos-radioterapia), prostata (hiperplasia benigna), utero (fase secretoria), articulacoes (artrite), ganglia simpaticos (cadeia para-aortica, celiaco)",
      "Integracao com RM e TC multifasica: RM hepatica com contraste hepatoespecifico (primovist) superior para lesoes hepaticas pequenas; TC pancreatica multifasica para avaliacao de relacao vascular; fusao PET/RM disponivel em centros selecionados com beneficio em estadiamento hepatico e pelvico",
      "Criterios de positividade para elegibilidade a PRRT: captacao tumoral superior a captacao hepatica normal (Krenning PET >= 3) em TODAS as lesoes-alvo; lesoes maiores que 1 cm em TC sem captacao SSTR devem ser investigadas com 18F-FDG para avaliar desdiferenciacao",
      "Papel na avaliacao de TNE de alto grau (G3): captacao SSTR pode ser heterogenea ou ausente em Ki-67 elevado; correlacao com 18F-FDG PET/CT essencial; score NETPET (combinando SSTR e FDG) como ferramenta prognostica emergente",
      "Campo de visao recomendado: vertice craniano ate raiz de coxa (padrao); extensao ate membros inferiores apenas se clinicamente indicado; SPECT/CT de campo limitado nao substitui PET/CT corpo inteiro",
      "Impacto no manejo clinico: estudos prospectivos demonstram mudanca de conduta em 30-40% dos pacientes comparado a imagem convencional; upstaging em 25% e downstaging em 5-10%",
      "Quantificacao: SUVmax e SUVpeak como metricas padrão; SUVmax tumoral/SUVmax hepatico como indice para selecao PRRT; tumor-to-liver ratio >= 1,5 considerado positivo por muitos centros",
      "Padronizacao de laudo: descricao de todas as lesoes com localizacao anatomica, tamanho, SUVmax e grau de captacao (escala Krenning-PET); comparacao com exames previos quando disponivel; conclusao com avaliacao de elegibilidade para PRRT",
      "Controle de qualidade do PET: calibracao cruzada PET-calibrador de dose, verificacao de linearidade, phantom ACR ou NEMA regularmente; participacao em programas de acreditacao (EARL, SNMMI PETCTP)",
      "Timing de suspensao de analogos: octreotide LAR deve ser suspenso 4-6 semanas antes do PET SSTR para evitar competicao pelo receptor; lanreotide 4 semanas; octreotide subcutaneo 24h antes; a nao-suspensao reduz captacao tumoral e pode levar a falso-negativo",
      "Consideracoes de radiacao: dose efetiva tipica de 3-5 mSv para 68Ga-DOTATATE e 4-7 mSv para TC de baixa dose associada; inferior a TC com contraste convencional",
      "Integracao com medicina nuclear terapeutica: PET SSTR e componente essencial do conceito teranostico (diagnostico + terapia com o mesmo alvo molecular); a demonstracao de captacao SSTR confirma a presenca do alvo terapeutico para PRRT"
    ],
    radiopharmaceuticals: "O 68Ga-DOTATATE (NETSPOT, aprovado FDA 2016; Detectnet/64Cu-DOTATATE, aprovado FDA 2020) e o radiotracador mais amplamente utilizado, com alta afinidade por SSTR subtipo 2 (Ki 0,2 nM). Atividade administrada tipica de 100-200 MBq (2,7-5,4 mCi) IV em bolus. Meia-vida do 68Ga de 68 minutos, produzido por gerador 68Ge/68Ga ou ciclotron. O 68Ga-DOTATOC tem afinidade por SSTR2 e SSTR5, com perfil de biodistribuicao semelhante e aprovacao em paises europeus. O 64Cu-DOTATATE (Detectnet) utiliza 64Cu (meia-vida 12,7h), permitindo distribuicao centralizada e logistica mais flexivel, com atividade de 148 MBq IV e aquisicao em 60-90 min. O 18F-SiTATE e o 18F-NOTA-Octreotide sao compostos emergentes marcados com 18F (meia-vida 110 min) que combinam alta afinidade SSTR com logistica de distribuicao tipo FDG.",
    practicalAspects: "O protocolo de preparo do paciente inclui suspensao obrigatoria de octreotide LAR 4-6 semanas antes (ou lanreotide 4 semanas antes) para maximizar disponibilidade de receptores; octreotide subcutaneo pode ser mantido ate 24h antes com suspensao no dia do exame. O paciente nao necessita jejum prolongado, mas hidratacao moderada (500 mL de agua 1-2h antes) e recomendada para reducao de atividade urinaria e melhora da qualidade de imagem pelvica. Miccao imediatamente antes da aquisicao e mandatoria para reduzir artefatos vesicais no leito prostatico. A atividade administrada e de 100-200 MBq (1,5-2,5 MBq/kg) de 68Ga-DOTATATE IV em bolus por acesso venoso periferico, com flush de 10-20 mL de solucao fisiologica. O tempo de captacao padrao e de 60 minutos (aceitavel 45-90 min para 68Ga; 60-90 min para 64Cu). A aquisicao PET/CT e realizada de vertice craniano a raiz de coxa, com TC de baixa dose (120 kVp, 30-80 mAs, modulacao automatica) para correcao de atenuacao e localizacao anatomica. O laudo deve incluir descricao sistematica de todos os sitios de captacao anormal, comparacao com fisiologico, SUVmax de lesoes representativas, grau de captacao pela escala modificada de Krenning, e conclusao clinica incluindo avaliacao de elegibilidade para PRRT quando pertinente. Para avaliacao de resposta pos-PRRT, o mesmo protocolo e radiotracador devem ser utilizados, com comparacao direta de SUVmax e numero/localizacao de lesoes. Armazenamento de imagens em formato DICOM para comparacao futura e dosimetria retrospectiva.",
    limitations: "A principal limitacao intrinseca e a dependencia de expressao de SSTR: tumores neuroendocrinos pouco diferenciados (G3 com Ki-67 acima de 55%, carcinomas neuroendocrinos/NEC) podem ter expressao SSTR reduzida ou ausente, resultando em falso-negativos; nestes casos, 18F-FDG PET/CT e o exame de escolha. A abordagem dual-tracer (SSTR + FDG) e recomendada em TNE de alto grau para avaliacao completa de heterogeneidade tumoral. Analogos de somatostatina (LAR) podem reduzir significativamente a captacao tumoral se nao descontinuados conforme protocolo (reducao de SUVmax de 30-50% relatada em alguns estudos), levando a falso-negativos e subestimacao de carga tumoral. A especificidade pode ser comprometida por captacao em processos inflamatorios, pos-radioterapia, ganglia simpaticos e estruturas fisiologicas (processo uncinado pancreatico e uma armadilha classica). Lesoes menores que 5-7 mm podem nao ser detectadas devido a resolucao espacial do PET (3-5 mm no isocentro). Disponibilidade de radiotracadores SSTR varia por regiao: 68Ga requer gerador local ou ciclotron com logistica de producao diaria; 64Cu-DOTATATE resolve parcialmente este problema com distribuicao centralizada. A padronizacao da quantificacao (SUV) entre diferentes equipamentos e centros permanece um desafio, dificultando comparacoes multicentrices e uso de limiares absolutos de SUV para decisao clinica.",
    reference: "Hope TA, et al. SNMMI Procedure Standard/EANM Practice Guideline for SSTR PET: Imaging Neuroendocrine Tumors. J Nucl Med. 2023;64(2):204-210."
  },

  // ═══════════════════════════════════════════════
  //  2. Prostata / PSMA-RLT
  // ═══════════════════════════════════════════════
  {
    id: "psma-rlt-eanm-snmmi-2023",
    title: "Joint EANM/SNMMI procedure guideline for the use of 177Lu-labeled PSMA-targeted radioligand therapy - 177Lu-PSMA-RLT",
    year: "2023",
    society: "EANM · SNMMI",
    type: "Procedure guideline",
    badges: ["essential"],
    category: "psma",
    categoryName: "Prostata / PSMA-RLT",
    categoryColor: "#3B82F6",
    scope: "Guideline procedimental definitivo e mais abrangente para terapia com radioligantes direcionados ao PSMA marcados com 177Lu (177Lu-PSMA-617/Pluvicto) em cancer de prostata metastatico resistente a castracao (mCRPC). Publicado apos a aprovacao regulatoria pelo FDA e EMA baseada nos resultados do estudo de fase 3 VISION, que demonstrou beneficio significativo em sobrevida global e sobrevida livre de progressao radiografica. Este documento representa o consenso entre as duas principais sociedades internacionais de medicina nuclear e cobre todo o espectro do tratamento: selecao de pacientes por PET-PSMA, criterios laboratoriais, protocolo de administracao, manejo de toxicidades, monitoramento pos-dose com SPECT/CT, criterios de resposta e suspensao, e consideracoes sobre radioproteao. Incorpora tambem dados emergentes do estudo PSMAfore (pre-taxano) e discussao sobre cenarios em expansao como mHSPC, oligometastatico e combinacoes terapeuticas.",
    indications: [
      "mCRPC PSMA-positivo ao PET, apos terapia com inibidor de via androgenica (enzalutamida, abiraterona, apalutamida ou darolutamida) E apos pelo menos uma linha de quimioterapia com taxano (docetaxel ou cabazitaxel), conforme indicacao aprovada baseada no VISION",
      "mCRPC PSMA-positivo apos inibidor de via androgenica, sem quimioterapia previa com taxano (cenario pre-taxano), conforme resultados do PSMAfore que demonstraram rPFS superior a mudanca de ARPi (HR 0,41)",
      "Cenarios off-label em avaliacao clinica ativa: mCRPC em primeira linha (combinacao com ARPi), cancer de prostata metastatico hormonossensivel (mHSPC), doenca oligometastatica, combinacao com imunoterapia (pembrolizumab), combinacao com PARP-inibidores (olaparib)",
      "Criterio de positividade ao PET-PSMA obrigatorio: pelo menos uma lesao metastatica com captacao PSMA superior a captacao hepatica normal; ausencia de lesoes PSMA-negativas significativas (visceral superior a 1 cm ou linfonodal superior a 2,5 cm em eixo curto)",
      "Criterios laboratoriais: clearance de creatinina >= 30 mL/min, hemoglobina >= 8 g/dL, plaquetas >= 50.000/mm3, neutrofilos >= 1.000/mm3",
      "Performance status ECOG 0-2 (ECOG 3 considerado individualmente)",
      "Expectativa de vida superior a 6 meses",
      "Sem quimioterapia ou radioterapia externa de campo extenso nas ultimas 4 semanas"
    ],
    keyPoints: [
      "Selecao por PET-PSMA: criterios VISION adaptados exigem captacao tumoral superior a captacao hepatica em pelo menos uma lesao metastatica; lesoes PSMA-negativas devem ser menores que 1 cm (visceral) ou 2,5 cm (linfonodal); doenca PSMA-negativa predominante exclui o paciente; avaliacao por medico nuclear experiente",
      "Atividade: 7,4 GBq (+/- 10%) de 177Lu-PSMA-617 (Pluvicto/vipivotide tetraxetan) IV a cada 6 semanas (+/- 1 semana), ate 6 ciclos (4 ciclos obrigatorios conforme protocolo VISION + 2 ciclos opcionais se beneficio clinico sem toxicidade proibitiva)",
      "Resultados do VISION: OS mediana 15,3 vs 11,3 meses (HR 0,62, p<0,001); rPFS mediana 8,7 vs 3,4 meses (HR 0,40); reducao de PSA >= 50% em 46% vs 7%; resposta confirmada RECIST em 30% (lesoes mensuraveis)",
      "Resultados do PSMAfore: rPFS mediana 12,0 vs 5,6 meses com mudanca de ARPi (HR 0,41); crossover permitido; dados de OS imaturos na publicacao primaria",
      "Elegibilidade laboratorial detalhada: TFG >= 30 mL/min (limiar minimo; >= 50 mL/min preferido), Hb >= 8 g/dL (considerar transfusao se sintomatico), plaquetas >= 50.000/mm3 (>= 75.000 preferido), neutrofilos >= 1.000/mm3; bilirrubina total <= 3x LSN; AST/ALT <= 5x LSN em presenca de metastases hepaticas",
      "Manejo de xerostomia: resfriamento glandular salivar externo (ice packs/compressas geladas sobre parotidas e submandibulares) por 30-60 min antes e 4h apos a infusao; evidencia limitada mas amplamente praticado em protocolos clinicos; toxina botulinica em pesquisa",
      "Monitoramento com SPECT/CT pos-dose em 24h: confirmacao de biodistribuicao tumoral, avaliacao de captacao em glandulas salivares, rins, figado; deteccao de deposicao nao-alvo; util para dosimetria simplificada; recomendado nos primeiros 2 ciclos (minimo) e quando houver suspeita clinica de progressao",
      "Criterios de suspensao: progressao tumoral confirmada (criterios PCWG3: PSA rising confirmado com progressao radiografica OU nova lesao sintomatica); toxicidade hematologica grau 4 persistente por mais de 6 semanas; insuficiencia renal aguda (queda de TFG superior a 50%); toxicidade grade 3-4 nao-hematologica nao resolvida entre ciclos",
      "Radioproteao: 177Lu tem meia-vida de 6,65 dias; paciente pode ser liberado quando taxa de dose a 1 metro for inferior a 25 microSv/h (tipicamente no mesmo dia ou dia seguinte); orientacoes escritas: distancia de gestantes e criancas menores de 12 anos por 7 dias, evitar contato corporal prolongado, cuidados com urina (sentar para urinar, dar descarga dupla por 1 semana)",
      "Avaliacao de resposta: PSA seriado a cada ciclo (queda >= 50% considerada resposta bioquimica significativa); PET-PSMA a cada 2-3 ciclos ou conforme indicacao clinica; TC/RM conforme PCWG3; atencao a flare de PSA (elevacao transitoria nos primeiros 2 ciclos sem significado de progressao)",
      "Medicacoes concomitantes: manutencao de ADT (agonista/antagonista LHRH) obrigatoria; enzalutamida/abiraterona — controversia sobre manter ou suspender (abiraterona pode aumentar expressao PSMA; enzalutamida pode reduzir; manter conforme decisao multidisciplinar ate dados definitivos)",
      "Dosimetria para PSMA-RLT: rins e glandulas salivares como orgaos criticos; medula ossea frequentemente comprometida por infiltracao tumoral direta; correlacao dose-resposta tumoral menos estabelecida que em PRRT; limite renal cumulativo de 23 Gy aplicado por analogia",
      "Toxicidades principais: fadiga (43%), nausea (35%), boca seca (39%), anemia (32%), trombocitopenia (17%), linfopenia (21%); toxicidade grau 3-4 hematologica em 23% (dados VISION); toxicidade renal grau 3-4 rara (menos de 3%)",
      "Consideracoes sobre 225Ac-PSMA-617: alfa-emissor em investigacao para mCRPC refratario a 177Lu-PSMA; atividade tipica de 4-8 MBq; xerostomia grave dose-limitante (grau 3-4 em ate 30%); dados de fase 1-2 promissores em pacientes pos-177Lu; desafio de imageamento (baixa estatistica de contagem)",
      "Sequenciamento terapeutico: posicao ideal de PSMA-RLT na cascata terapeutica do mCRPC em evolucao; relacao com 223Ra (sem dados prospectivos de combinacao); integracao com novos agentes (olaparib em BRCA+, pembrolizumab em MSI-high)"
    ],
    radiopharmaceuticals: "O 177Lu-PSMA-617 (Pluvicto, nome generico: vipivotide tetraxetan Lu-177) e o radiofarmaco aprovado pelo FDA (marco/2022) e EMA (dezembro/2022) para mCRPC PSMA-positivo. Trata-se de um ligante de baixo peso molecular direcionado ao antigeno de membrana especifico da prostata (PSMA), acoplado ao quelante DOTA e marcado com 177Lu. A atividade aprovada e de 7,4 GBq (200 mCi) por ciclo, fornecida pelo fabricante em dose unitaria pronta para uso com prazo de validade determinado pela data de calibracao. O 177Lu possui meia-vida de 6,65 dias, emissao beta (Emax 497 keV) com alcance maximo de 2 mm em tecido, e emissao gama (113 keV, 6,2%; 208 keV, 11%) permitindo imageamento SPECT pos-dose. O 177Lu-PSMA-I&T e um radioligante alternativo de producao academica, com quelante DOTAGA e linker diferente, perfil farmacocinetico comparavel e utilizado em centros europeus e australianos (estudo TheraP), porem sem aprovacao regulatoria formal. Atividades tipicas de 6,0-7,4 GBq por ciclo foram utilizadas em estudos com PSMA-I&T.",
    practicalAspects: "O fluxo inicia com PET/CT com radiotracador PSMA (68Ga-PSMA-11, 18F-DCFPyL ou 18F-PSMA-1007) realizado dentro de 12 semanas antes do primeiro ciclo, interpretado por medico nuclear experiente segundo criterios de elegibilidade VISION (captacao tumoral superior a hepatica, ausencia de doenca PSMA-negativa significativa). A avaliacao laboratorial completa inclui hemograma com diferencial, funcao renal (creatinina, TFG estimada, preferencialmente >= 50 mL/min), funcao hepatica (bilirrubina, transaminases, albumina), PSA total, testosterona (confirmacao de castracao), fosfatase alcalina, DHL e calcio. O paciente nao necessita jejum prolongado, mas hidratacao adequada (1-2 L de agua nas 4h pre e pos-infusao) e fortemente recomendada para reducao de dose renal e vesical. No dia do tratamento, acesso venoso periferico de bom calibre e obtido. O Pluvicto e administrado como bolus lento IV direto ou por bomba peristaltica em 5-10 minutos, seguido de flush com 10-20 mL de solucao fisiologica. O uso de ice packs sobre glandulas salivares (parotidas e submandibulares) e iniciado 30 min antes da infusao e mantido por 4h apos, embora a evidencia seja limitada. Antiemeticos profilaticos (ondansetrona 8 mg VO) sao administrados em pacientes com historia de nausea. Monitoramento de PA e FC a cada 15 min durante infusao. Apos a infusao, repouso em area dedicada com monitoramento de taxa de dose ate atingir criterios de liberacao (tipicamente 1-4 horas para 177Lu). A imagem SPECT/CT pos-dose e realizada preferencialmente em 24h (campo de visao incluindo pelve e abdome, com extensao para torax e cranio quando clinicamente indicado) para verificacao de biodistribuicao e dosimetria. O PSA e coletado antes de cada ciclo como principal marcador de resposta bioquimica. Reestadiamento com PET-PSMA e TC/RM conforme indicacao clinica (tipicamente apos 2-3 ciclos ou na suspeita de progressao). Hemograma a cada 2 semanas nos primeiros 3 meses, depois mensalmente. Funcao renal monitorada a cada ciclo.",
    limitations: "A dependencia absoluta de captacao PSMA ao PET e a principal limitacao: pacientes com doenca PSMA-negativa (transformacao neuroendocrina, carcinoma de pequenas celulas) nao se beneficiam e representam 5-15% dos mCRPC, especialmente apos multiplas linhas de terapia antiandrogencia. A mielotoxicidade cumulativa e o principal orgao dose-limitante, particularmente em pacientes com infiltracao ossea difusa, quimioterapia previa com taxano ou radioterapia pelvica, podendo limitar o numero de ciclos administrados. A xerostomia pode ser clinicamente significativa em 5-10% dos pacientes (grau 2-3) e afetar qualidade de vida, ingesta alimentar e saude dental a longo prazo, sem estrategia profilática ou terapeutica definitivamente eficaz. Os dados de OS maduros do VISION foram obtidos contra standard-of-care que nao incluia cabazitaxel, Ra-223 ou olaparib como comparadores ativos, levantando questoes sobre a magnitude do beneficio versus opcoes terapeuticas completas. O estudo TheraP com 177Lu-PSMA-I&T vs cabazitaxel demonstrou superioridade em PSA response rate mas OS semelhante, sugerindo que cabazitaxel e um comparador valido. A dosimetria tumoral para PSMA-RLT esta menos estabelecida que para PRRT, com correlacao dose-resposta ainda em investigacao. O sequenciamento otimo entre PSMA-RLT, quimioterapia (cabazitaxel), Ra-223, PARP-inibidores e imunoterapia permanece uma area de intensa pesquisa sem consenso definido. Dados sobre retratamento (re-PSMA-RLT) apos progressao pos-Pluvicto sao limitados.",
    reference: "Kratochwil C, et al. Joint EANM/SNMMI procedure guideline for the use of 177Lu-labeled PSMA-targeted radioligand-therapy (177Lu-PSMA-RLT). Eur J Nucl Med Mol Imaging. 2023;50(9):2830-2845."
  },
  {
    id: "psma-pet-imaging-v2-2023",
    title: "PSMA PET/CT: Joint EANM procedure guideline/SNMMI procedure standard for prostate cancer imaging - version 2.0",
    year: "2023",
    society: "EANM · SNMMI",
    type: "Procedure guideline / Procedure standard",
    badges: ["imaging"],
    category: "psma",
    categoryName: "Prostata / PSMA-RLT",
    categoryColor: "#3B82F6",
    scope: "Segunda versao do guideline conjunto para PET/CT com radiotracadores PSMA no cancer de prostata, representando uma atualizacao substancial em relacao a versao 1.0 de 2017. Incorpora a evidencia acumulada de estudos prospectivos multicenetricos (proPSMA, CONDOR, OSPREY) que demonstraram superioridade do PET-PSMA sobre imagem convencional em todas as indicacoes clinicas. Abrange todo o espectro de indicacoes: estadiamento primario de alto risco, recidiva bioquimica, mCRPC e selecao para PSMA-RLT. Introduz formalmente o sistema de interpretacao PSMA-RADS versao 1.1, padroniza protocolos de aquisicao para os quatro radiotracadores clinicamente disponiveis (68Ga-PSMA-11, 18F-DCFPyL, 18F-PSMA-1007, 18F-rhPSMA-7.3), e discute o impacto da terapia antiandrogencia sobre a expressao PSMA. Representa o estado da arte na imagem molecular do cancer de prostata.",
    indications: [
      "Estadiamento primario de cancer de prostata de risco intermediario-desfavoravel e alto risco (ISUP grau >= 3 ou Gleason >= 4+3, PSA >= 20 ng/mL, estagio clinico >= cT3, envolvimento de ductos ou invasao linfovascular) conforme estudos proPSMA e guidelines NCCN/EAU 2023",
      "Recidiva bioquimica pos-prostatectomia radical: PSA detectavel e em elevacao (>= 0,2 ng/mL; taxa de deteccao do PET-PSMA de 30-40% para PSA 0,2-0,5 ng/mL e 60-75% para PSA 0,5-1,0 ng/mL)",
      "Recidiva bioquimica pos-radioterapia definitiva: PSA nadir + 2 ng/mL (criterio Phoenix); PET-PSMA para localizacao de recidiva local vs sistemica para guiar terapia de resgate",
      "Avaliacao de extensao de doenca em mCRPC: estadiamento completo para planejamento terapeutico, incluindo selecao para PSMA-RLT, quimioterapia, Ra-223 ou terapia dirigida a metastases",
      "Selecao de pacientes para 177Lu-PSMA-RLT (Pluvicto): demonstracao de captacao PSMA tumoral conforme criterios VISION (captacao superior a hepatica, ausencia de doenca PSMA-negativa significativa)",
      "Avaliacao de doenca oligometastatica para terapia dirigida a metastases (MDT): radioterapia estereotaxica (SBRT) ou cirurgia de lesoes isoladas identificadas por PET-PSMA",
      "Planejamento de radioterapia: definicao de volume-alvo biologico (BTV) para boost ou campo de tratamento",
      "Monitoramento de resposta terapeutica em cenarios selecionados (uso crescente mas sem padronizacao de criterios de resposta por PET-PSMA)"
    ],
    keyPoints: [
      "Protocolos de aquisicao padronizados: 68Ga-PSMA-11: 1,8-2,2 MBq/kg (maximo 250 MBq) IV, aquisicao em 60 min (+/- 10); 18F-DCFPyL (PYLARIFY): 333 MBq (9 mCi) IV, aquisicao em 60-120 min (120 min preferido para melhor contraste); 18F-PSMA-1007: 200-300 MBq IV, aquisicao em 60-120 min; 18F-rhPSMA-7.3: 296 MBq IV, 60-120 min",
      "Sistema PSMA-RADS v1.1 para padronizacao de interpretacao: PSMA-RADS 1 = benigno (sem captacao); PSMA-RADS 2 = provavelmente benigno (captacao leve em sitio atipico); PSMA-RADS 3 = equivoco (captacao moderada em sitio indeterminado); PSMA-RADS 4 = provavelmente maligno (captacao intensa em sitio tipico de metastase); PSMA-RADS 5 = definitivamente maligno (captacao muito intensa com correlacao anatomica)",
      "Armadilhas diagnosticas detalhadas: ganglia simpaticos (celiaco, sacral) simulam linfonodos; NTI (non-tumor intracraniana) em meningioma, schwannoma; hiperplasia prostatica benigna (captacao difusa, PSMA-RADS 2); captacao em fraturas, Paget, displasia fibrosa; captacao inespecifica hepatica com 18F-PSMA-1007 (excrecao hepatobiliar); glandulas salivares, lacrimais e adrenais com captacao fisiologica intensa",
      "Criterios quantitativos para selecao a PSMA-RLT: SUVmax tumoral / SUVmax hepatico >= 1,5 como limiar minimo; todas as lesoes superiores a 1 cm devem ter captacao PSMA acima de hepatica; doenca PSMA-negativa avaliada por TC/RM correlata e 18F-FDG PET quando indicado",
      "Papel do PET-PSMA na doenca oligometastatica: identificacao de ate 5 lesoes metastaticas para MDT com SBRT; impacto na decisao terapeutica demonstrado em estudos prospectivos (ORIOLE); deteccao de doenca nao-oligometastatica em 15-20% dos pacientes considerados oligometastaticos por imagem convencional",
      "Impacto da terapia androgenica sobre expressao PSMA: ADT e ARPi (enzalutamida, abiraterona, apalutamida, darolutamida) aumentam expressao PSMA em 30-50% (upregulation via via AR); implicacao pratica: nao suspender ADT/ARPi antes do PET-PSMA para selecao terapeutica; em estadiamento primario, PET-PSMA pre-ADT pode subestimar carga tumoral",
      "Integracao com mpMRI pelvica: PET-PSMA nao substitui RM multiparametrica para avaliacao local (estagio T, envolvimento capsular, invasao de vesiculas seminais); fusao PET/RM disponivel em centros selecionados para estadiamento otimo",
      "Estudo proPSMA (2020): PET/CT com 68Ga-PSMA-11 vs imagem convencional (TC + cintilografia ossea) em estadiamento primario de alto risco — acuracia 92% vs 65% (p<0,001); mudanca de conduta em 28% dos pacientes",
      "Estudo CONDOR (2021): 18F-DCFPyL PET/CT em recidiva bioquimica apos imagem convencional negativa — taxa de deteccao de 59% (PSA mediano 0,8 ng/mL); mudanca de conduta em 64%",
      "Reproducibilidade: variabilidade de SUV entre equipamentos PET requer calibracao local; comparacoes entre exames devem ser realizadas no mesmo equipamento quando possivel; EARL harmonization aplicavel",
      "Laudo padronizado: incluir todos os sitios de captacao com PSMA-RADS, SUVmax, tamanho da lesao em TC, comparacao com exames previos; conclusao com TNM molecular (miTNM) quando aplicavel; avaliacao explicita de elegibilidade para PSMA-RLT quando este e o contexto clinico",
      "Consideracoes sobre 18F vs 68Ga: tracadores 18F (DCFPyL, PSMA-1007, rhPSMA-7.3) oferecem producao centralizada via ciclotron, distribuicao tipo FDG, maior volume de pacientes por lote e imagem de maior resolucao (meia-vida 110 min vs 68 min); 68Ga requer gerador local ou ciclotron dedicado",
      "Excrecao urinaria: 68Ga-PSMA-11 e 18F-DCFPyL tem excrecao renal predominante (atividade vesical intensa); 18F-PSMA-1007 tem excrecao hepatobiliar predominante (menor atividade vesical, vantajoso para leito prostatico); diuretico oral (furosemida 20 mg 30 min antes) pode melhorar avaliacao pelvica com tracadores renais"
    ],
    radiopharmaceuticals: "Quatro radiotracadores PSMA estao clinicamente disponiveis: (1) 68Ga-PSMA-11 (Locametz/Illuccix, aprovado FDA 2021): atividade de 1,8-2,2 MBq/kg, meia-vida de 68 min, producao por gerador 68Ge/68Ga ou ciclotron, excrecao renal predominante; (2) 18F-DCFPyL (PYLARIFY, aprovado FDA 2021): atividade de 333 MBq, meia-vida de 110 min, producao centralizada via ciclotron, excrecao renal predominante; (3) 18F-PSMA-1007 (disponivel em centros europeus e australianos, nao aprovado FDA): atividade de 200-300 MBq, excrecao hepatobiliar predominante (vantagem na pelve), mas maior taxa de achados inespecificos osseos; (4) 18F-rhPSMA-7.3 (Posluma, aprovado FDA 2023): atividade de 296 MBq, excrecao renal predominante, producao tipo radiofarmacia centralizada (kit). Todos sao ligantes de baixo peso molecular que se ligam ao dominio extracelular do PSMA com alta afinidade (Ki sub-nanomolar). O PSMA e uma glicoproteina transmembrana tipo II superexpressa em 85-95% dos canceres de prostata, com expressao crescente conforme grau histologico e resistencia a castracao.",
    practicalAspects: "O preparo do paciente e simples comparado a outros radifarmacos: nao ha necessidade de jejum (exceto 4h para hidratacao oral com 500 mL de agua para 68Ga-PSMA-11 e 18F-DCFPyL). Nao ha necessidade de suspender nenhuma medicacao, incluindo hormonoterapia (ADT/ARPi), que na verdade aumenta a expressao PSMA e pode melhorar a deteccao. Atividade administrada varia por tracador (veja secao radiopharmaceuticals). Injecao IV em bolus com flush de 10-20 mL de solucao fisiologica. Tempo de captacao de 60 min para 68Ga, 60-120 min para compostos 18F (120 min preferido para melhor relacao contraste-ruido com 18F-DCFPyL). Hidratacao moderada e miccao obrigatoria imediatamente antes da aquisicao para reduzir artefato vesical. Furosemida 20 mg VO 30 min antes da injecao pode ser administrada para acelerar clearance vesical e melhorar avaliacao do leito prostatico (opcional, mais util com tracadores de excrecao renal). Aquisicao PET/CT de vertice craniano a raiz de coxa (inclusao de cranio controversa — indicada em mCRPC com sintomas neurologicos ou doenca de alto volume). TC de baixa dose (120 kVp, 30-80 mAs, modulacao automatica de corrente) para correcao de atenuacao e localizacao. TC diagnostica com contraste pode ser combinada (protocolo venoso) em centros que oferecem PET/CT one-stop-shop. O laudo estruturado deve incluir: contexto clinico, tracador utilizado, tempo de captacao, parametros de aquisicao, descricao sistematica de todos os sitios de captacao (prostata/leito, linfonodos, osseo, visceral), classificacao PSMA-RADS de cada achado, SUVmax de lesoes representativas, correlacao com TC, comparacao com exames previos, e conclusao clinica com avaliacao de elegibilidade para PSMA-RLT quando pertinente.",
    limitations: "Aproximadamente 5-10% dos canceres de prostata sao PSMA-negativos, especialmente histologias neuroendocrinas, carcinoma de pequenas celulas e alguns tumores desdiferenciados apos multiplas linhas de terapia antiandrogencia — nestes casos, 18F-FDG PET/CT pode ser complementar. A expressao PSMA pode ser heterogenea dentro do mesmo paciente (lesoes PSMA-positivas e negativas coexistentes), refletindo heterogeneidade tumoral biologica que tem implicacoes prognosticas e terapeuticas. Captacao inespecifica em fraturas, Paget, ganglia, processos inflamatorios e HPB pode gerar falso-positivos, especialmente com 18F-PSMA-1007 que tem maior taxa de achados osseos inespecificos (ate 15%). A taxa de deteccao em recidiva bioquimica precoce (PSA menor que 0,5 ng/mL) permanece subotima (30-40%), e resultados negativos nao excluem doenca microscopica. A disponibilidade de radiotracadores PSMA varia significativamente por regiao: tracadores 68Ga requerem gerador local ou ciclotron, e tracadores 18F requerem ciclotron com capacidade de producao de radiofluor e modulos de sintese dedicados. A padronizacao da quantificacao (SUV) entre equipamentos permanece um desafio para estudos multicentricos e uso de limiares absolutos. Criterios de resposta por PET-PSMA nao estao formalmente validados (PERCIST/PSMA-PET progression criteria em desenvolvimento). A relacao custo-efetividade em estadiamento primario de risco intermediario permanece em debate em alguns sistemas de saude.",
    reference: "Fendler WP, et al. PSMA PET/CT: Joint EANM procedure guideline/SNMMI procedure standard for prostate cancer imaging 2.0. Eur J Nucl Med Mol Imaging. 2023;50(5):1466-1486."
  },
  {
    id: "psma-eanm-2019",
    title: "EANM procedure guidelines for radionuclide therapy with 177Lu-PSMA ligands",
    year: "2019",
    society: "EANM",
    type: "Procedure guideline",
    badges: [],
    category: "psma",
    categoryName: "Prostata / PSMA-RLT",
    categoryColor: "#3B82F6",
    scope: "Primeiro guideline procedimental europeu formal para terapia com radioligantes direcionados ao PSMA marcados com 177Lu, publicado antes da aprovacao comercial do Pluvicto e baseado exclusivamente na experiencia academica acumulada de centros pioneiros na Alemanha (Heidelberg, Essen, Munich), Australia (Peter MacCallum) e outros paises. Este documento historicamente significativo compilou pela primeira vez as melhores praticas para 177Lu-PSMA-617 e 177Lu-PSMA-I&T em contexto de uso compassivo e acesso expandido, cobrindo producao local, controle de qualidade, selecao de pacientes, administracao, dosimetria e radioproteao. Serviu como base tecnica para o desenho do estudo de fase 3 VISION e influenciou diretamente os protocolos clinicos que levaram a aprovacao regulatoria. Reflete a heterogeneidade da pratica academica europeia da epoca, com atividades variaveis, intervalos flexiveis e producao local de radiofarmaco.",
    indications: [
      "mCRPC com captacao PSMA confirmada por PET/CT (68Ga-PSMA-11 ou 18F-PSMA-1007), refratario a pelo menos uma linha de quimioterapia com taxano e uma linha de ARPi",
      "Uso compassivo e acesso expandido pre-aprovacao regulatoria: pacientes sem opcoes terapeuticas convencionais disponiveis",
      "Criterios minimos de captacao: captacao tumoral superior a captacao hepatica basal em pelo menos uma lesao metastatica ao PET-PSMA",
      "Ausencia de doenca PSMA-negativa predominante (avaliada por TC ou 18F-FDG PET)",
      "Funcao organica minimamente preservada: TFG >= 30 mL/min, hemograma com plaquetas >= 50.000 e Hb >= 8 g/dL",
      "Performance status adequado para tolerar o tratamento (ECOG 0-2, selecionados com ECOG 3)",
      "Expectativa de vida superior a 3 meses (criterio mais liberal que em VISION dado contexto compassivo)",
      "Pacientes previamente tratados com 223Ra (sem contra-indicacao para sequenciamento, embora dados fossem limitados)"
    ],
    keyPoints: [
      "Criterios de selecao por PET-PSMA: captacao tumoral superior a captacao hepatica basal em pelo menos uma lesao metastatica; interpretacao visual por medico nuclear com experiencia em PSMA-PET; ausencia de doenca PSMA-negativa predominante (lesoes maiores que 1 cm em TC sem correspondencia de captacao PSMA sugerem desdiferenciacao)",
      "Atividades entre 3,7-7,4 GBq por ciclo (100-200 mCi): flexibilidade deliberada refletindo pratica variavel entre centros; maioria dos centros alemanes utilizava 6,0 GBq; centros australianos e italianos frequentemente 7,4 GBq; reducao de atividade em pacientes com funcao renal limitada ou carga tumoral ossea extensa",
      "Intervalo entre ciclos: 6-8 semanas como padrao (variacao de 4-12 semanas aceita conforme recuperacao hematologica e logistica); numero de ciclos nao fixo — baseado em resposta clinica e tolerabilidade (tipicamente 3-6 ciclos)",
      "Comparacao PSMA-617 vs PSMA-I&T: ambos sao ligantes ureicos de baixo peso molecular com afinidade subnanomolar pelo PSMA; PSMA-617 usa quelante DOTA, PSMA-I&T usa quelante DOTAGA; perfis farmacocineticos comparaveis com captacao tumoral, excrecao renal e clearance sanguineo semelhantes; maior base de dados clinica para PSMA-617 (base do VISION), PSMA-I&T utilizado no TheraP",
      "Aspectos de producao e controle de qualidade para ligantes academicos: sintese local em radiofarmacia hospitalar com certificacao GMP (ou sob protocolo de uso compassivo conforme regulacao nacional); precursores peptidicos comerciais; marcacao com 177Lu-cloreto (no-carrier-added preferido); controle de qualidade obrigatorio antes da liberacao: pureza radioquimica superior a 95% (HPLC ou TLC), pH 4-7, esterilidade (teste post-hoc), endotoxinas, inspecao visual",
      "Dosimetria como ferramenta opcional mas encorajada: SPECT/CT quantitativo em multiplos timepoints (24h e 48-96h) para calculo de dose absorvida em rins, glandulas salivares e tumores; single-timepoint dosimetry em 24h como alternativa simplificada; limites de dose renal de 23 Gy (cumulativo) aplicados por analogia com PRRT",
      "Radioproteao: paciente liberado quando taxa de dose a 1 metro inferior a 25 microSv/h; orientacoes escritas para paciente e familiares; distancia de gestantes e criancas por 5-7 dias; cuidados com urina e fluidos corporais por 1 semana; 177Lu tem menor emissao gama que 131I, permitindo liberacao mais precoce",
      "Manejo de toxicidades: xerostomia (30-40%, geralmente grau 1-2); fadiga (30-50%); nausea leve (15-25%); trombocitopenia (10-20%, geralmente grau 1-2); nefrotoxicidade clinica rara; PSA flare em 5-10% (elevacao transitoria sem significado de progressao); monitoramento com hemograma a cada 2-4 semanas e funcao renal a cada ciclo",
      "Avaliacao de resposta: queda de PSA como principal biomarcador (reducao >= 50% considerada resposta); PET-PSMA para reestadiamento a cada 2-3 ciclos; TC/RM para avaliacao anatomica; ALP como marcador auxiliar em doenca ossea; criterios de resposta PCWG3 adaptados",
      "Experiencia clinica acumulada na epoca da publicacao: mais de 1.000 pacientes tratados em centros academicos globais com taxas de resposta de PSA >= 50% em 40-60% dos pacientes e toxicidade grau 3-4 hematologica em 10-15%",
      "Perspectivas futuras (na epoca): necessidade de estudos de fase 3 randomizados (VISION e TheraP em andamento), validacao de dosimetria como ferramenta de otimizacao, investigacao de alfa-emissores (225Ac-PSMA), combinacoes terapeuticas, e uso em cenarios mais precoces (pre-taxano, mHSPC)"
    ],
    radiopharmaceuticals: "Os dois radioligantes cobertos sao o 177Lu-PSMA-617 e o 177Lu-PSMA-I&T, ambos produzidos localmente em radiofarmacias hospitalares na epoca da publicacao. O PSMA-617 (desenvolvido no DKFZ Heidelberg) utiliza o quelante DOTA acoplado a um farmacoforo baseado em ureia (Glu-ureia-Lys) via linker AHEX; e o composto que deu origem ao Pluvicto comercial. O PSMA-I&T (desenvolvido na TU Munich) utiliza o quelante DOTAGA com linker diferente e moiety de ligacao iodo-bifenilalanina; base do estudo TheraP. Ambos sao marcados com 177Lu na forma de cloreto (no-carrier-added, atividade especifica alta), com rendimento de marcacao tipicamente superior a 98%. A pureza radioquimica minima aceitavel e de 95%, verificada por cromatografia (HPLC ou TLC). O 177Lu (meia-vida 6,65 dias, beta Emax 497 keV, gama 113 e 208 keV) e fornecido por reatores nucleares (IDB Holland, ITG Munich, ANSTO Australia) em forma de cloreto ou como complexo pre-marcado.",
    practicalAspects: "Este guideline foi desenhado para centros academicos que produzem radifarmacos PSMA internamente, com infraestrutura de radiofarmacia hospitalar, celulas quentes (hot cells) para marcacao, e licenca para manipulacao de radionuclideos terapeuticos. O fluxo inicia com selecao do paciente em junta multidisciplinar (urologista, oncologista, medico nuclear), seguido de PET-PSMA para confirmacao de elegibilidade. Avaliacao laboratorial: hemograma completo, funcao renal (creatinina, TFG), funcao hepatica, PSA, testosterona, ALP, DHL. No dia do tratamento, producao do radiofarmaco na radiofarmacia (tipicamente 2-4h antes da administracao), controle de qualidade (pureza radioquimica superior a 95% por HPLC ou TLC, pH 4-7, esterilidade post-hoc, ausencia de particulas por inspecao visual), calibracao da atividade no calibrador de dose. Administracao IV lenta (bolus lento em 5-10 min ou infusao por bomba peristaltica em 20-30 min, conforme pratica do centro). Alguns centros realizam pre-medicacao com dexametasona 4-8 mg; antiemeticos conforme necessidade. Hidratacao com 1-2 L de solucao fisiologica ou oral. Ice packs sobre glandulas salivares (parotidas e submandibulares) em alguns protocolos. Imagem SPECT/CT pos-dose em 24h para verificacao de biodistribuicao e dosimetria quando disponivel. Monitorizacao de taxa de dose para liberacao. Protocolos variam significativamente entre centros academicos em relacao a atividade por ciclo, numero de ciclos, intervalo, uso de aminoacidos concomitantes (nao padrao em PSMA-RLT diferente de PRRT), e criterios de resposta.",
    limitations: "Publicado antes dos dados definitivos do VISION (fase 3, publicado em 2021) e PSMAfore (publicado em 2023), as recomendacoes eram baseadas em series retrospectivas, estudos de fase 1-2 e experiencia institucional, com nivel de evidencia limitado para varias recomendacoes. O cenario pre-taxano nao era abordado, pois toda a experiencia era em pacientes multi-tratados como ultima opcao terapeutica. As atividades variaveis entre 3,7-7,4 GBq por ciclo refletem a heterogeneidade da pratica academica sem padronizacao baseada em evidencia de fase 3. A producao local de radiofarmaco introduz variabilidade de qualidade entre centros, dependente de infraestrutura de radiofarmacia, experiencia do radiofarmaceutico e rigor de controle de qualidade. A dosimetria era apresentada como opcional, e a maioria dos centros utilizava atividades empiricas ou baseadas em experiencia local. Os dados de toxicidade de longo prazo eram limitados pelo tempo de seguimento relativamente curto na epoca (mediana inferior a 2 anos na maioria das series). A comparacao formal entre PSMA-617 e PSMA-I&T nao foi realizada em estudo randomizado, e a escolha entre os dois era guiada por preferencia e experiencia institucional. Este documento permanece historicamente relevante como referencia da era pre-aprovacao e como base tecnica para os protocolos que definiram a pratica atual.",
    reference: "Kratochwil C, et al. EANM procedure guidelines for radionuclide therapy with 177Lu-labelled PSMA-ligands (177Lu-PSMA-RLT). Eur J Nucl Med Mol Imaging. 2019;46(12):2536-2544."
  },
'''

os.makedirs(os.path.dirname(target), exist_ok=True)
with open(target, 'w', encoding='utf-8') as f:
    f.write(content)

print(f"Batch A written: 7 guidelines (4 PRRT + 3 PSMA)")
print(f"Target: {target}")
print(f"Size: {len(content):,} characters")
